### ISSUE TITLE
new folder and collection view template: list of titles

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#100]
A simple list of titles of contained objects, each linked to the corresponding content object, in folder content order.

**Comment by paregorios** [comment]
To clarify: we would like to have the option of using this title-only view for either folders or collections.

**Comment by cewing** [comment]
This is implemented, awaiting review so it can be merged and deployed to staging.

**Comment by skleinfeldt** [comment]
@alecpm is going to review

**Comment by alecpm** [comment]
This change is live on staging now. Sorry for the delay.

**Comment by k2soule** [comment]
looks good on staging!

**Comment by alecpm** [comment]
This is merged and deployed
