### ISSUE TITLE
improve style on "summary" folder template: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#101]
title text is too large, too much whitespace, what to do when there is no content in the summary field on the subordinate item?

**Comment by paregorios** [comment]
Changes (this view only):

- Keep current behavior when there is no summary (i.e., do nothing)
- For an `h2` elements followed by a summary paragraph in this view only, change bottom margin to "0px"
- Following a summary paragraph, maintain 28px vertical space before subsequent `h2`
- When two `h2` elements follow each other without an intervening summary paragraph, maintain 28px vertical margin.
- Remove all "read more" lines and links
- Do not display lead images

**Comment by paregorios** [comment]
https://isaw.nyu.edu/members/te20-40nyu.edu
![Screen Shot 2022-04-25 at 12 12 35 PM](https://user-images.githubusercontent.com/263285/165139508-f33332a0-558f-4848-bc44-7395200ba09d.png)

**Comment by silviot** [comment]
[Visible on staging](https://isaw.jazkarta.com/members/te20-40nyu.edu)

**Comment by silviot** [comment]
@paregorios I also realized I used a CSS feature not supported by Firefox.

Images should be hidden though (I see them missing).

**Comment by paregorios** [comment]
@silviot Ah, I see what is going on. Some of the items in the folder are "image" objects, and thumbnails of them are showing up. I think that's ok so let's leave it as it is. From my perspective this is ready to be merged to master and deployed to production.

![Screen Shot 2022-11-10 at 1 50 24 PM](https://user-images.githubusercontent.com/263285/201192686-76298a90-1594-4783-9162-c07d20acf985.png)

**Comment by paregorios** [comment]
@silviot this looks great on production, thanks!
