### ISSUE TITLE
owners and Editors must not be able to modify an item in "pending" or "published" state

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#103]
At present, in the context of the standard ISAW process for web content curation with the isaw_standard workflow, users who are content owners or who have "can add" and "can edit" assigned via sharing are able to make certain modifications to pending and published content that we would like restricted. Specifically, the following capabilities should be denied to them:

* Deleting an item in "pending" state
* Deleting an item in "published" state
* Checkin of a working copy to a baseline item in "pending" state
* Checkin of a working copy to a baseline item in "published" state

I note that owners and users with "can add" + "can edit" presently cannot directly edit a "pending" or "published" item. This is a good thing, and should stay that way. We just need to bring these other forms of modification into line.

**Comment by paregorios** [comment]
This ticket should be applied not only to the "standard" workflow but also the "intranet" workflow where tests reveal the same behaviors.

**Comment by cewing** [comment]
The ability to delete items is controlled by the `Delete objects` permission, which is granted by default to the editor, owner and manager roles.  I will add this permission to the list of permissions controlled by the intranet and standard workflows and will ensure that it is not granted to the `editor` or `owner` role when content is in the `pending` or `published` state.

**Comment by cewing** [comment]
I am still unable to satisfactorily explain the issue of being able to check in working copies of objects where the baseline is `pending` or `published`.  The permission to check things in is actually controlled not by the special permission established by the `plone.app.iterate` permission, but rather by the `Modify portal contents` permission.  I would therefore expect this problem to appear in any context where a person who should not have had the ability to edit an item did have that ability.  

I will need to spend a bit more time looking at this.

**Comment by cewing** [comment]
@paregorios as I explained on the phone, there is no distinction in base Plone between deleting an object and deleting the items an object contains, and the ability to delete things is tied to the state of the parent of the things being deleted.  This means that without significantly interfering in how the right to delete stuff is determined, we cannot achieve a solution to those two bullet points from the original issue report.

However, the working copy checkin issues are entirely resolved now.

**Comment by cewing** [comment]
@paregorios excepting the two bullets regarding deletion, this issue is fixed and deployed.  You can run your selenium tests and you should expect all tests to pass **except** those for preventing owners from deleting content in the pending or published state.

**Comment by skleinfeldt** [comment]
For all these tickets, deployed = staging

**Comment by paregorios** [comment]
Selenium testcases for "standard" suite exhibit the following failures:

* in testcase jcarberry:
  * user is given a "checkin" option on own working copy of a "pending" item (unexpected failure)
  * user is given a "delete" option (expected failure)
* in testcase alee:
  * user is given a "checkin" option on own working copy of a "published" item (unexpected failure)
  * user is given a "delete" option (expected failure)

I've verified the unexpected checkin behavior manually using the same user accounts. Please advise.

**Comment by skleinfeldt** [comment]
@cewing i think this is a question for you...

**Comment by cewing** [comment]
@paregorios, can you check a few things for me. 

First, let's verify that the workflow is correct. Go to Site Setup, and from there to the Zope Management Interface.  Find the `portal_workflow` tool and click on it.  Then click on the contents tab and select the isaw_standard_workflow.  From there, select the permissions tab and verify that the `iterate : Check in content` permission is in the list of managed permissions.  Then click the `states` tab and verify that in `pending` and `published` the permission is **not** granted to the `Owner` role.  All of those things should be true assuming that the workflow as I modified it is installed.  

Next, can you verify that the intranet tests do not suffer the unexpected failures above?  I ask because the workflow definition for both is exactly the same in terms of who has the right to check in content in various states, so if the owner *can* check in to published or pending items under the standard workflow and *cannot* do so under the intranet workflow, something odd is going on.

**Comment by cewing** [comment]
One last thing, @paregorios, it occurs to me that the tests for checkin might use objects that are already in existence and have been for a long time.  If this is the case, then it is possible that even though the workflow is correct, the permissions have not been properly re-indexed.  You might try 'editing' and then saving the folder in which the standard workflow tests are run.  This should cause a security re-indexing for the folder and its contents.  Then re-run the tests and see if they start passing.

**Comment by paregorios** [comment]
@cewing it looks as if the workflow is not correctly deployed (or something) on staging. I got as far in your instructions above as the step to check that ```iterate : Check in content``` is in the list of managed permissions. It is not:

![standard-workflow-permissions](https://cloud.githubusercontent.com/assets/263285/12340274/7fa780c2-badf-11e5-97be-8b20b0eeb92b.jpg)

**Comment by cewing** [comment]
@paregorios: that would certainly be a problem, and would explain the failure we are seeing.  

Can you check in the add-on control panel to see if there is an upgrade step available for isaw.policy?  Maybe we didn't run the upgrade step after pushing the changes to staging?

**Comment by paregorios** [comment]
After running the upgrade step on isaw.policy, I can confirm that tests for both standard and intranet workflow are passing as originally described above. Closing this ticket as resolved.
