### ISSUE TITLE
remove selective visibility from items in the intranet workflow

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#104]
Back in August, under the rubric of issue #42, we asked @alecpm "to limit viewability for items in folders under the "isaw intranet workflow" that are in the "internally published state" to particular groups of users." [Alec wisely queried the sense and consistency of this decision](https://github.com/isawnyu/isaw.web/issues/42#issuecomment-135901246), but went ahead and implemented as requested.

We have now changed our minds and would like this customization removed. 

Specifically, in folders governed by the "isaw-internal" workflow, we would like all authenticated users to be able to view items in the "internally published" state.

**Comment by cewing** [comment]
I've reverted the changed lines that removed viewing from all authenticated members in the intranet workflow.  An upgrade step will be needed to apply the changes.  Not yet ready for review.

**Comment by cewing** [comment]
This will be repaired once #106 is merged and deployed.

**Comment by cewing** [comment]
This is merged and deployed and you may expect all selenium tests related to it to pass.

**Comment by paregorios** [comment]
All tests passing. Closing as resolved.
