### ISSUE TITLE
prevent editing "pending" items in isaw-intranet workflow

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#105]
In the isaw standard workflow, we're setup so that neither owners nor those with "can edit" role are able to "edit" an item in the "pending" state of the workflow. In the isaw intranet workflow, only owners are prohibited from editing items in "pending" state. We would like to see these rules harmonized: i.e., "can edit" should not give users the ability to edit directly items in "pending" state.

**Comment by cewing** [comment]
Now that we know what is causing the problem with image/file upload, we can take this permission away in the intranet workflow and not worry about it removing the ability to upload images and files.  Done.

**Comment by cewing** [comment]
This will be repaired when #106 is merged and deployed.

**Comment by cewing** [comment]
This is deployed to staging and can be tested.  You should expect all tests related to this in your selenium suite to pass.

**Comment by paregorios** [comment]
Tests passing. Close as resolved.
