### ISSUE TITLE
Empower Tom and Kristen to do deployments

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#109]
The new and improved merged repo stack is now running on production, so deployments are much easier to do. This ticket is intended to give @paregorios  and @k2soule  the knowledge to be able to do future deployments. I'm assigning to @alecpm to provide the cookbook. Feel free to ask questions, and when you're ready, you can do the next deployment. Schedule it at a time when we can be standing by on Skype to make sure things go smoothly.

**Comment by paregorios** [comment]
+1 all over this :)

**Comment by alecpm** [comment]
Deploying should be pretty straightforward.  Once the master branch is in a state that you feel is ready to deploy to production, check the current tags in your local working copy:

    git tag

Pick a new release number (e.g. 3.3.4) then create and push the new tag:

    git tag 3.3.4
    git push origin 3.3.4

Login to the production server and checkout the new tag:

    git fetch --all
    git checkout 3.3.4

That will ensure you the server is pinned to your new revision (you can run ``git status`` to ensure there aren't any unexpected local changes on the server).  Then just run the buildout and restart the services as usual.

**Comment by skleinfeldt** [comment]
Over to @paregorios for review.

**Comment by paregorios** [comment]
I've successfully stepped through this procedure on my local instance with no difficulties.

**Comment by paregorios** [comment]
Just a couple of questions to make sure I understand everything aright (I'm mainly used to restarting my local development instance according to steps in the readme). After making jazkarta my primary group and then checking out the new tag as discussed above, I'll need to:

* ```bin/buildout``` (no need to run bootstrap, right? no arguments to buildout, right?)
* if there are any permissions errors (e.g., because of checkout wonkiness), fix them
* use ```bin/supervisorctl``` to restart clients 1-3 and the zeoserver (no longer need sudo for this, right?)
* issue ```sudo service varnish restart```

@alecpm ok?

**Comment by alecpm** [comment]
That's about right. You need to be in the jazkarta group, but it doesn't have to be your primary group.  There's probably no need for a varnish restart unless you want to clear the cache for some reason. There's also generally no need to restart the zeoserver, unless there's a significant zope upgrade.

**Comment by paregorios** [comment]
Thanks @alecpm

**Comment by paregorios** [comment]
Keeping this open for now as a reminder to document details, but this is substantively done and good.

**Comment by paregorios** [comment]
we've been able to do this repeatedly and have produced internal documentation, which should in future be consulted instead of this ticket thread. Closing as resolved.
