### ISSUE TITLE
Bylines not appearing in blog items

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#110]
When a person's name is listed in the "creators" field for a blog post, that name appears in the news blog tile view, but not inside the blog post itself. (Whereas a byline is displayed in both places if a valid username is entered in the "creators" field.) If two or more creators are listed, only the first one appears.

The byline should be able to display more than one author, and ideally it should also be able to display the name of a creator who does not have a web site login. If we can't display more than one name (or the contents of one line) from the Creators field, then the explanatory text for filling out that field should be adjusted accordingly.

Assigning to Tom for a patch suggestion.

**Comment by k2soule** [comment]
The current text for the Creators field is:
"Creators
Persons responsible for creating the content of this item. Please enter a list of user names, one per line. The principal creator should come first."

**Comment by paregorios** [comment]
We might want to try adapting some of [this code from the Pleiades skin](https://github.com/isawnyu/PleiadesEntity/blob/master/skins/PleiadesEntity/citationAuthors.py) to override the default Plone 4 byline behavior (which just picks up the first creator as author) in [the viewlet document_byline.pt at v. 2.3.x](https://github.com/plone/plone.app.layout/commit/b1d1ea7071c6ed606d9fbb8cee66fe892557f52f) (which is what we're currently using).

**Comment by paregorios** [comment]
But see also:

* http://stackoverflow.com/questions/8827304/can-more-than-one-author-be-listed-in-the-byline

**Comment by paregorios** [comment]
And see: http://docs.plone.org/4/en/old-reference-manuals/plone_3_theming/elements/visibleelements/plone.belowcontenttitle.documentbyline.html

**Comment by paregorios** [comment]
I have a modified template, applied via the ZMI, for this capability now in stakeholder review via staging. If no major objections, I'd hope to deploy (via ZMI) on production shortly, then follow-up by incorporating in code.

**Comment by skleinfeldt** [comment]
[Don't forget to remove it from the custom skin when the code's been deployed!]

**Comment by paregorios** [comment]
in work in branch issue110

**Comment by paregorios** [comment]
bumping to medium priority as there's a workaround in place, but there's a downstream gotcha lurking until it's been incorporated in code.

**Comment by cewing** [comment]
I've got this one licked, @paregorios, but I'd like some eyes on the pull request before merging it.  

We must also remember that to properly close this, once the code is deployed you will need to delete the customized version of this byline viewlet template from the ZMI.  Otherwise, that version will take precedence over this one.

**Comment by cewing** [comment]
@alecpm I thought I'd pinged you on this, but looking back, I clearly failed to do so.  Wondering if you'd do a bit of code review, and then merge/deploy to staging if ready?

**Comment by cewing** [comment]
@paregorios this is now merged, but it is not yet deployed.  Will assign to you when I'm sure it's ready on staging for review.

**Comment by cewing** [comment]
Deployed.  Marking as reviewable and assigning to @paregorios

**Comment by paregorios** [comment]
@cewing this is very close, but it looks like we're trapping whitespace somewhere between the end of each creator string and the trailing comma:

<img width="417" alt="screen shot 2016-06-08 at 7 51 11 am" src="https://cloud.githubusercontent.com/assets/263285/15894858/d40a67ac-2d4d-11e6-9111-d05bf806a94d.png">

```
Jacco Dieleman</a>
        </span>,
```
I think we need something that ends without whitespace between the closing of the ```a``` element and the closing of the surrounding ```span``` element (without introducing any between the closing of the ```<span>``` element and the comma, like:
```
Jacco Dieleman</a></span>,

**Comment by cewing** [comment]
I'll see if I can't squash that. I thought I had. Thanks

**Comment by cewing** [comment]
Yep, found it.  As soon as we can get this deployed, I'll re-assign back for review.

**Comment by paregorios** [comment]
That's got it! Please deploy to production.

**Comment by k2soule** [comment]
The functionality appears to be correct on production, but did the customized version of the byline viewlet template get deleted from the ZMI?

**Comment by skleinfeldt** [comment]
@k2soule I imagine it did, or should have been (the idea being to keep everything in code and minimize the use of the ZMI), but we'll have to wait until @cewing is back from vacation next week to ask.

**Comment by alecpm** [comment]
This has been deployed and the TTW customized byline has been removed.

**Comment by k2soule** [comment]
Thanks! Closing ticket.
