### ISSUE TITLE
build a better publications experience

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#114]
We now have so many publications, both in print and online, that we need a better experience than the two pages we've had so far: [Publications](http://isaw.nyu.edu/publications) and [Online Resources](http://isaw.nyu.edu/online-resources). This need is further heightened by the fact that we dropped Online Resources from the main navigation in order to simplify and on the assumption that we could do something better that treated all such things as publications, regardless of media. 

@rogerbagnall has recently proposed the following re-organization scheme: 
1. ISAW Books
   - Individual items
   - Amheida
2. ISAW Journals
   - ISAW papers
   - JIAAN
3. Exhibition publications
4. Rostovtzeff Lectures (only those actually appeared)
5. ISAW Institutional communications
   - Newsletters
   - ISAW at Five

I think that some combination of [collective.cover](https://github.com/collective/collective.cover), collections + some tagging, and individual page content items could give us an excellent and scaleable solution.

**Comment by paregorios** [comment]
@sfsheath and @k2soule will want to be part of this discussion

**Comment by paregorios** [comment]
now experimenting with collective.cover in branch issue114

**Comment by paregorios** [comment]
bumping to high priority as it's an issue of concern for the director

**Comment by paregorios** [comment]
a mockup:

![img_0906](https://cloud.githubusercontent.com/assets/263285/12895669/2ed47910-ce63-11e5-81b6-d64bf5d32e39.JPG)

**Comment by rogerbagnall** [comment]
Promising. I think I'd put Exhibitions in the top line in place of 
Journals.

-- 
Roger S. Bagnall
Leon Levy Director
Institute for the Study of the Ancient World
New York University

**Comment by k2soule** [comment]
In progress.

**Comment by paregorios** [comment]
blocked for resolution of #199, #200, #202

**Comment by k2soule** [comment]
also needs resolution of #221

**Comment by paregorios** [comment]
Despite the fact that we couldn't get #221 completed in the most recent tranche of work, we were able to put together a new publications experience on the website (the main page is manually constructed). So, closing this ticket as complete.
