### ISSUE TITLE
bylines appear to all logged-in users even on content they can only read

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#117]
unverified user report; is causing confusion

**Comment by k2soule** [comment]
Adding details: a user pointed out that the visible bylines on certain internal documents only confuse the reader (they reflect the person who created the initial draft document, and not the person who "owns" the content, and anyway the person who owns the content is referenced in contact information within the page - so the byline doesn't need to appear at all. Yet, we do want all users to be able to see the bylines in certain special areas of the web site, such as News Blog.

We need to identify options for hiding the byline from logged-in users who don't need to see it (primarily those who only have can-view permission), and then determine which option makes the most sense - and the least headaches elsewhere.

**Comment by skleinfeldt** [comment]
Could use a Diazo rule to hide selectively based on path.

Or if it only makes sense on the news blog, incorporate the needed byline info into the custom view (IIRC there is a custom view.)

**Comment by paregorios** [comment]
I have decided that this is not a bug; rather it is a feature. Won't fix.
