### ISSUE TITLE
isaw logo has white border in some chrome versions on Mac

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#123]
![whitewall](https://cloud.githubusercontent.com/assets/263285/14109736/22bf3ec4-f589-11e5-85d2-6fce26c94d16.png)

**Comment by paregorios** [comment]
In-browser testing seems to indicate that the way to deal with this is to replace "contain" in the css style specification for the background image with "100%".
![no-whitewalls](https://cloud.githubusercontent.com/assets/263285/14209982/8f14f874-f7ec-11e5-81af-86c641f23e58.png)

**Comment by paregorios** [comment]
above tested in chrome on Mac; needs testing in other browsers then implementation in code

**Comment by cewing** [comment]
@paregorios, I am unable to reproduce this issue. 

Here's what I see in Safari, Firefox and Chrome (from left to right) on my Mac on the live site.  Is this specific to some other browser?  I am also unable to see the problem using a local dev instance.

![isaw_logo](https://cloud.githubusercontent.com/assets/417109/15833308/067b5b52-2bdb-11e6-81fa-2b4f2ceb162d.png)

**Comment by paregorios** [comment]
This only occurs for me in Chrome 50.0.2661.102 (64 bit) under El Capitan 10.11.5, even after clearing all cache etc. This is a new computer from the one I saw it on when I originally opened the ticket. It does not occur for me Safari or Firefox. Please defer more work on this issue until I can verify that it occurs on someone else's machine. I will downgrade priority label and take assignment meantime.

**Comment by k2soule** [comment]
I have duplicated what Tom is reporting; the white border artifact appeared in my Chrome browser (version 50.0.2661.102, 64-bit), on my MacOS 10.9.5 machine. It did not appear in Firefox or Safari.

**Comment by paregorios** [comment]
So, perhaps this is an issue only in certain versions of chrome? I've retitled the ticket accordingly and am pinging @skleinfeldt here to see to whom this should be assigned for further investiagtion. 

To clarify: if it turns out to be a chrome *bug* for which there is at present no known workaround, then I don't want to spend a bunch of time poking at this; however, if some citizens of the web have figured out a CSS-ish way to get around the problem that doesn't involve tons of work to implement, I'd be interested in squashing this.

**Comment by cguardia** [comment]
I don't have a Mac, so I'm unable to look at this. @skleinfeldt maybe you need to reassign?

**Comment by paregorios** [comment]
Can you check to see if it happens in chrome on your os?

On Thursday, June 9, 2016, Carlos de la Guardia <notifications@github.com>
wrote:

> I don't have a Mac, so I'm unable to look at this. @skleinfeldt
> <https://github.com/skleinfeldt> maybe you need to reassign?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/isawnyu/isaw.web/issues/123#issuecomment-225051365>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQEdVeXZkc9TiT3elYU91S5amphhtAYks5qKJqRgaJpZM4H6ujT>
> .
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by skleinfeldt** [comment]
@cguardia see tom's request above that you test chrom on your OS - is an ubuntu version available?

**Comment by cguardia** [comment]
@paregorios @skleinfeldt looks fine on Chrome (and Firefox too) for Linux.

**Comment by paregorios** [comment]
Thanks

On Thursday, June 9, 2016, Carlos de la Guardia <notifications@github.com>
wrote:

> @paregorios <https://github.com/paregorios> @skleinfeldt
> <https://github.com/skleinfeldt> looks fine on Chrome (and Firefox too)
> for Linux.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/isawnyu/isaw.web/issues/123#issuecomment-225059088>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQEdYLvISHTT3-1H23mnItV40PjGG-tks5qKKXNgaJpZM4H6ujT>
> .
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cewing** [comment]
FYI, my chrome version is 51.0.2704.84 (64-bit), so it appears my chrome is more update than yours?  This would seem to suggest that perhaps this issue is isolated to a particular version(s) of chrome

**Comment by paregorios** [comment]
latest chrome update seems to have fixed this.
