### ISSUE TITLE
In Events listing view, lead images should be clickable links

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#134]
When viewing a list of events displayed in Event Listing view, the lead image for an event (if there is one) should be a clickable link through to the event item.

**Comment by alecpm** [comment]
This is in place on staging:

http://isaw4-dev.atlantides.org/events/archive/ay-2015-2016

**Comment by k2soule** [comment]
Looks good! Please deploy to production.

**Comment by alecpm** [comment]
This is now merged to master and will be deployed with the next tagged release.

**Comment by alecpm** [comment]
This is deployed

**Comment by paregorios** [comment]
This can't be tested on production until #95 has been deployed, since there are no upcoming events.

**Comment by paregorios** [comment]
looks good on production
