### ISSUE TITLE
new exhibitions views do not work on collections

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#136]
[The original scrumdo story](https://www.scrumdo.com/projects/story_permalink/1095959) specifies that the new "checklist" and "highlights" views should work on collections, but a test on staging does not work. See: ```/exhibitions/foobition/highlights/highlights-collector```.

**Comment by alecpm** [comment]
This should be working on staging now, there was an issue with the macro setup for new-style collections.
