### ISSUE TITLE
exhibition object view shows summary/description field

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#140]
Standard behavior for other content on the ISAW website is to suppress this field in base view, using it only for search and listings and the like. Exhibition objects should behave the same way.

e.g. http://isaw4-dev.atlantides.org/exhibitions/foobition/checklist/second-item

**Comment by alecpm** [comment]
This is on staging.

**Comment by paregorios** [comment]
This looks good on staging, and on production as well. I assume that means it has already been deployed. Is that correct @alecpm ?
