### ISSUE TITLE
new exhibitions checklist and highlights views missing on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#141]
On staging, one sees:

![screen shot 2016-07-21 at 12 55 02 pm](https://cloud.githubusercontent.com/assets/263285/17031483/6f3f1acc-4f42-11e6-96db-b7999b0f0539.png)

But these display views are missing on production:

![screen shot 2016-07-21 at 12 56 00 pm](https://cloud.githubusercontent.com/assets/263285/17031500/84b405ca-4f42-11e6-8705-283031a65130.png)

**Comment by alecpm** [comment]
These are now deployed

**Comment by paregorios** [comment]
Thanks!
