### ISSUE TITLE
lead image cropping options missing for new exhibition materials

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#142]
Not on staging, nor on production, the "cropping" tab doesn't appear on exhibition objects. Isn't it needed in order to get uniform image display on the checklist and highlights views?

**Comment by alecpm** [comment]
This is on staging.

**Comment by paregorios** [comment]
Cropping affordances are appearing and seem operable, but I can discern no effect in the checklist view. Example:

http://isaw4-dev.atlantides.org/exhibitions/foobition/objects

http://isaw4-dev.atlantides.org/exhibitions/foobition/objects/gem-engraved-with-selene-moon-holding-torch-and-driving-two-horse-chariot

**Comment by alecpm** [comment]
Those listings use the "tile" size (64x64) rather than the "thumbnail" (128x128) size. I've now enabled cropping for all the scales on staging, it was limited to a few default sizes previously.

**Comment by alecpm** [comment]
I've made this configuration change on production as well since it is helpful and harmless. I've also included the configuration change in the policy profile.

**Comment by paregorios** [comment]
thanks
