### ISSUE TITLE
zotero import should behave the same on isaw.web as it does on pleiades

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#144]
*reviewing [Scrumdo story 124](https://www.scrumdo.com/projects/story_permalink/1098338)*

Differences that need to be addressed:
-----------------------------------------

 * do not populate the "citation detail" field at all under any circumstances from Zotero 
 * when "short title" is absent in the Zotero record, copy the value from Zotero:title into the isaw.web:bibliographicItem:short_title field (see [pleiades-gazetteer/issues/208](https://github.com/isawnyu/pleiades-gazetteer/issues/208))

**Comment by alecpm** [comment]
I had fixed this along with the Pleiades fixes, but had not deployed to isaw. Should be live now.

**Comment by paregorios** [comment]
looks good
