### ISSUE TITLE
August security patch

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#146]
Security patch coming out 8/30: https://plone.org/security/announcements/20160830-preannounce

Plus minor security fixes if not already done: https://plone.org/news/2016/minor-plone-security-fixes

**Comment by cguardia** [comment]
Security patch done. Minor fixes pending.

**Comment by skleinfeldt** [comment]
@paregorios or @k2soule please review and close. I will open a new ticket for the minor fixes.

**Comment by paregorios** [comment]
I'm assuming that the "minor fixes" mentioned by @cguardia above are now complete. Yes? 

We're not entirely sure what would constitute a comprehensive review of this, but we have poked around on the production site and not noticed any obvious content problems. We have also verified that login and logout and creation of draft content (at least by administrative users) is all working as expected. So, we're going to close this issue. If there's something else that @cguardia or @skleinfeldt thinks we should check, please reopen the ticket and provide guidance.

**Comment by skleinfeldt** [comment]
@paregorios no, the "minor fixes" were deferred to #149, that's the one that will need more careful testing. What you described above seems fine for the hotfix.
