### ISSUE TITLE
new "locations" not recognized by "Map View" on enclosing folder

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#147]
*reviewing [scrumdo story 135](https://www.scrumdo.com/projects/story_permalink/1099488)*

To reproduce:
-----------------

- Login to staging.
- Navigate to http://isaw4-dev.atlantides.org/exhibitions/foobition/checklist
- Note that there is only one symbol on the map (for exhibition object "Conical sundial ..."
- View contents of the folder and note that there is also a "location" object at http://isaw4-dev.atlantides.org/exhibitions/foobition/checklist/theatre-of-palmyra but it is not showing up on the map.

**Comment by paregorios** [comment]
reassigning to @alecpm since he implemented the story

**Comment by alecpm** [comment]
Looks like I missed an adapter registration for the new type. Should be fixed on staging now.

**Comment by paregorios** [comment]
Looks goo don staging. Please deplyo to production.

**Comment by alecpm** [comment]
Deployed.
