### ISSUE TITLE
make credit line and copyright statement more discreet

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#148]
*reviewing [scrumdo story 133](https://www.scrumdo.com/projects/story_permalink/1099469)*

Please make the following changes to the presentation/formatting of these fields in the object base view:

- make text style "discreet"
- do not display field labels for these two fields

Otherwise, please leave them where they are in the layout.

**Comment by paregorios** [comment]
reassigning to @cguardia since it's his story

**Comment by alecpm** [comment]
I'm gonna steal this one since it's blocking deployment of Story 132 (which is on the same branch as 133)

**Comment by alecpm** [comment]
This is fix is implemented and deployed to both staging and production (because I had already deployed Story 132 to production without realizing this was a blocker for 133).
