### ISSUE TITLE
Upgrade to 4.3.10

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#149]
In addition to the 8/30 hotfix, #146, it is recommended to upgrade to Plone 4.3.10 to take advantage of the latest minor security fixes: https://plone.org/news/2016/minor-plone-security-fixes.

**Comment by paregorios** [comment]
@skleinfeldt I would like to prioritize getting this upgrade process tested with an up-to-date copy of the filestorage and basestorage on staging. Once we know what hiccups we might face, then we can talk about scheduling for production. Does that make sense?

**Comment by cguardia** [comment]
Copied data from production and updated staging to 4.3.10.

**Comment by paregorios** [comment]
OK, so @cguardia is this ready for me to review on staging?

**Comment by skleinfeldt** [comment]
@paregorios Yes.

**Comment by paregorios** [comment]
Thanks @cguardia. This looks good to me. Please plan for a nighttime deployment to production, with extra care on versions tagging etc. so that we can step back to a known good version if something goes wrong in the upgrade.

**Comment by cguardia** [comment]
This has been tagged and deployed to production.

**Comment by paregorios** [comment]
This appears to have gone without a hitch. Thanks @cguardia
