### ISSUE TITLE
add location with Pleiades URI fails on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#150]
Steps to reproduce:

 * Login to production
 * Navigate to a draft, temporary folder somewhere
 * Add a location object
 * Enter any Pleiades URI in the "Fetch coordinates from Pleiades URL" box
 * Select the "Fetch" button
 * Get a modal error pop-up like this one:

![screen shot 2016-09-06 at 10 54 44 am](https://cloud.githubusercontent.com/assets/263285/18280877/6591a334-7420-11e6-97b5-d8e66469ace1.png)

**Comment by paregorios** [comment]
I have tested on production and Pleiades import fails in this manner on all location-enabled content types.

**Comment by alecpm** [comment]
Hm, I just tried this here:

http://isaw.nyu.edu/copy_of_online-resources/temp-folder/++add++isaw.policy.location?_authenticator=19ff54346f8561f732e0960234f565b54c35a880

It worked though the response from pleiades was quite slow in coming.

**Comment by alecpm** [comment]
I used this pleiades url: http://pleiades.stoa.org/places/393473

What browser are you using? I'm wondering if there might be an issue with the Accept header that jQuery is sending out on some browsers.

**Comment by paregorios** [comment]
Chrome 52.0.2743.116 (64-bit) under OSX 10.11.6 (15G1004).

I'll test on FF and Safari too.

**Comment by paregorios** [comment]
Tested with 3 browsers, using http://pleiades.stoa.org/places/393473 every time. All running under Mac OSX 10.11.6 (15G1004). Results as follows:

- Chrome  53.0.2785.89 (64-bit): error pop-up as described above
- Firefox 48.0: error pop-up as described above
- Safari 9.1.3 (11601.7.8): error pop-up as described above

**Comment by alecpm** [comment]
Hm, I'm going to assign to @cguardia temporarily in hopes that he can reproduce the issue. So far, under the exact same browsers and OS, I have not been able to reproduce the issue. I did see an issue in Firefox the first time I tried where the pleiades server returned a 304 Not Modified when the browser didn't seem to have a valid cached value, but that didn't cause a popup alert as you describe.

It seems possible that the browser is asking making an If-None-Match request with an Etag if it has visited the Pleiades HTML page, and Pleiades is returning a 304 even though the request was not for the HTML page.

@paregorios Does it work for you if you clear your browser cache? If so, that will give a big hint about how to proceed. The simple solution on the ISAW side would be to disable caching of the AJAX request/response, though there's probably a more general fix that could be done on the Pleiades side to ensure 304 responses are only sent for matching Accept requests.

**Comment by paregorios** [comment]
@alecpm and @cguardia clearing browser cache seems to have no effect for me. I still get the pop-up error. Are you testing while connected over https?

**Comment by alecpm** [comment]
No, and I bet that's the problem (the only way to login to the site via SSL is with Shibboleth, which I don't have a login for). It looks like Pleiades doesn't support SSL, which means a client side connection from an SSL page won't work in most browsers. If Pleiades supported SSL, then we could detect SSL and alter the url scheme, otherwise we'll have to make the request on the ISAW server side and proxy it.

**Comment by paregorios** [comment]
This is blocked for adding HTTPS support on Pleiades.

**Comment by paregorios** [comment]
Implementation of Pleiades HTTPS has fixed this on production, as hoped.
