### ISSUE TITLE
help needed on event slide query on home page slider

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#151]
We have a query embedded in the overlay text for one of the slides on the home-page slider. It pulls in three future events, as desired, but these events are not the *next* three events ... they seem to be random. We could use some help tweaking the query to get the expected result.

**Comment by alecpm** [comment]
This should be fixed. The query just needed a "sort_on": "start" to fix the index that it was being sorted on.

**Comment by paregorios** [comment]
that's it, thanks!
