### ISSUE TITLE
bibliographic item summary not populated from Zotero

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#153]
**Reviewing [Scrumdo Story 134](https://www.scrumdo.com/projects/story_permalink/1099470) on staging**

Two of the three specifications for this story seem to be working as expected. What's missing is the third one, i.e.:

- When importing from Zotero, populate summary with a copy of the formatted citation text, stripped of all HTML formatting.

An example, freshly imported from Zotero, may be seen (by appropriately authenticated users) here: http://isaw4-dev.atlantides.org/members/paregorian/remembering-the-mycenaeans/view. Inspection of the "edit" view will demonstrate that the "summary" field is blank.

**Comment by alecpm** [comment]
Sorry, needed to refresh the JS cache. Should be working now.

**Comment by paregorios** [comment]
this is now fixed.
