### ISSUE TITLE
batch biblio creation script fails with AttributeError on staging

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#154]
**reviewing [scrumdo story 125](https://www.scrumdo.com/projects/story_permalink/1098339)**

Steps to recreate:

- ssh into staging
- change user to "plone"
- ```cd /srv/isaw.web/```
- ```bin/client1 run scripts/batch_bibliography.py /home/telliott/bibitems.txt members/paregorian/fooberts --title "Fun with biblio again" --site isaw```
- get the following output and traceback (plone startup warnings omitted):

```

Starting batch content creation...

Created new folder isaw/paregorian
Created new folder isaw/paregorian/fooberts
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scripts/batch_bibliography.py", line 91, in <module>
    print "Error fetching {}: {}".format(bib_url, data.error)
AttributeError: 'dict' object has no attribute 'error'
```

**Comment by alecpm** [comment]
Ooh, you got an error back from the Zotero fetcher and my error handling code was not well tested. Should be fixed now so we can see what the error was.

**Comment by paregorios** [comment]
this has been addressed
