### ISSUE TITLE
in bibliographic listing, tags in formatted citation are escaped instead of rendered

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#156]
*reviewing [scrumdo story 123](https://www.scrumdo.com/projects/story_permalink/1098337)*

I may not have been clear enough about this in the story: I would like any and all HTML tags in the formatted citation to be rendered in page as HTML. Right now they are passed through and displayed in the browser as part of a text block. E.g., http://isaw4-dev.atlantides.org/members/paregorian/bibliographic-list-view-test

**Comment by cguardia** [comment]
No, it was an oversight on my part. Fixed.

**Comment by paregorios** [comment]
Fixed!
