### ISSUE TITLE
some news item lead images have lost their cropping

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#158]
Evident in /news, the following seem to be not using the "blog tile" cropping:

- http://isaw.nyu.edu/news/publication-from-isaw-neugebauer-conference
- http://isaw.nyu.edu/news/phd-program-application-fall-2016 (I tried to fix this one by recropping, and now the image doesn't show up at all in the /news page!)
- http://isaw.nyu.edu/news/epidig
- http://isaw.nyu.edu/news/elliott-neh
- http://isaw.nyu.edu/news/pleiades-grant-2015
- http://isaw.nyu.edu/news/website-upgrades
- http://isaw.nyu.edu/news/research-associate-spotlight-yehudah-cohn
- http://isaw.nyu.edu/news/visiting-research-scholar-spotlight-juan-manuel-tebes
- http://isaw.nyu.edu/news/upcoming-fall-isaw-exhibition-1
- http://isaw.nyu.edu/news/isaw-hosts-the-academy-for-teachers
- http://isaw.nyu.edu/news/isaw-search-for-new-director
- http://isaw.nyu.edu/news/excavation-findings-at-kinik-hoyuk

and more

**Comment by skleinfeldt** [comment]
Oh goody, image cropping issues - assigning to @alecpm

**Comment by alecpm** [comment]
That view appears to be showing the "preview" crop rather than the blogtile. Should we switch it to use the blogtile crop?

**Comment by alecpm** [comment]
The blogtile crop does appear to be intact.

**Comment by paregorios** [comment]
I don't know why it shoud have been using preview. It was always my/our understanding that it used "blogtile"; indeed, blogtile was specifically created for that view.

**Comment by paregorios** [comment]
@alecpm it looks like we've misunderstood each other. The problem is in the news listing, with the items in question. I didn't mean for the image shown with the news item base view to change. 

For example:

![screen shot 2016-09-19 at 10 52 04 am](https://cloud.githubusercontent.com/assets/263285/18638867/4a434e66-7e57-11e6-8fc0-371e81567d4f.png)

and

![screen shot 2016-09-19 at 10 52 37 am](https://cloud.githubusercontent.com/assets/263285/18638873/50b87e56-7e57-11e6-9a00-cee9f4e029a9.png)

**Comment by paregorios** [comment]
@alecpm based on our discussion in IRC, I'm pleased with this remedy. Please deploy to production.

**Comment by alecpm** [comment]
This is deployed. It looks like some of the too small images are still in place on production though.

**Comment by paregorios** [comment]
looks good, thanks. too-small images noted and will address as a content issue
