### ISSUE TITLE
css is disproportionately scaling lead image on exhibition items base view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#159]
Consider, for example, https://isaw.nyu.edu/exhibitions/time-cosmos/objects/conical-sundial-with-oscan-dedicatory-inscription. 

Kitty Mao is being pulled width-wise like taffy:

![screen shot 2016-09-16 at 4 02 49 pm](https://cloud.githubusercontent.com/assets/263285/18601191/0f4755b4-7c27-11e6-9fab-903869c94990.png)

She would prefer to retain her original aspect ratio:

![screen shot 2016-09-16 at 4 04 10 pm](https://cloud.githubusercontent.com/assets/263285/18601225/3fabaa20-7c27-11e6-803f-203aebb02f53.png)

I think this may be caused by a CSS rule on the selector ```#content .ExhibitObjectImage img``` that sets ```width``` to a specific pixel value instead of "auto".

**Comment by alecpm** [comment]
I've deployed a fix to staging that keeps the the max-width and height while still respecting the aspect ratio and responsive behavior.

**Comment by paregorios** [comment]
@alecpm this looks good. Please deploy to production.

**Comment by alecpm** [comment]
Deployed.

**Comment by paregorios** [comment]
looks good, thanks
