### ISSUE TITLE
inventory number has been omitted from the exhibition object base view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#160]
It's not addressed by the template: https://github.com/isawnyu/isaw.web/blob/master/src/isaw.exhibitions/isaw/exhibitions/browser/exhibition_object.pt#L15

**Comment by cguardia** [comment]
Committed fix to master.

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
This looks good too. Please deploy to production.
