### ISSUE TITLE
batch update script does not cater for some fields on exhibition objects

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#162]
[Scrumdo story 133](https://www.scrumdo.com/projects/story_permalink/1099469) added two additional fields to the Exhibition Object type: "credits" and "copyright". The story failed to specify that support for loading these be [added to the batch update script](https://github.com/isawnyu/isaw.web/blob/master/scripts/batch_update.py#L15). They are needed.

**Comment by cguardia** [comment]
This one is fixed on master. Will deploy when I finish #161.

**Comment by paregorios** [comment]
this looks good. please deploy to production
