### ISSUE TITLE
Mosaic View is slow for large (but realistic) numbers of objects

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#165]
Consider how long it takes to load and flow the images in http://isaw4-dev.atlantides.org/exhibitions/time-cosmos/objects

**Comment by cguardia** [comment]
No way around it, I had to drop masonry.js and get something else. It's on staging now.

**Comment by paregorios** [comment]
@cguardia: thanks for jumping on this. Please deploy to production.

**Comment by paregorios** [comment]
Moving to review status as @cguardia emailed that it has been deployed to production.  I will test performance after my next batch upload test attempt.

**Comment by paregorios** [comment]
looks good, thanks
