### ISSUE TITLE
staging is down

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#166]
http://isaw4-dev.atlantides.org/ returns:

```
Error 503 Service Unavailable

Service Unavailable

Guru Meditation:

XID: 1147133779

Varnish cache server
```

This is blocking testing for our upcoming exhibitions content and features.

**Comment by alecpm** [comment]
This should be fixed. HAProxy had fallen over for unknown reasons.

**Comment by paregorios** [comment]
great, thanks!
