### ISSUE TITLE
location enhancements don't seem to work

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#168]
_reviewing scrumdo stories [144](https://www.scrumdo.com/projects/story_permalink/1100736) and [147](https://www.scrumdo.com/projects/story_permalink/1101139)_

I can't seem to get it to do anything other than what it was doing already, i.e., importing the latitude and longitude from Pleiades. I had expected to be able to add a new location, put a Pleiades URI in a text box, select a "fetch" button, and see the "title", "summary", "latitude", and "longitude" boxes filled in.

Steps to reproduce:

- Login to staging with a user with admin credentials
- Navigate to http://isaw4-dev.atlantides.org/members/paregorian/fun-with-maps
- Select "add new" from the green actions bar and select "location" from the drop-down menu
- On the "add location" form, enter "https://pleiades.stoa.org/places/432815" (without the quotation marks) in the text box under the latitude and longitude boxes labeled "Fetch coordinates from Pleiades URL" (not the field box with the same label text that has been added I guess to store the URI). 
- Select the "fetch" button.
- Observe that the "latitude" and "longitude" boxes are filled, but the "title", "summary", and field-level "Fetch coordinates from Pleiades URL" boxes remain empty.

**Comment by alecpm** [comment]
Sorry needed portal_javascript to be resaved in the ZMI to flush the cache.
