### ISSUE TITLE
author/contributor links in new publications view are incorrect

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#170]
_reviewing [scrumdo story 150](https://www.scrumdo.com/projects/story_permalink/1101334)_

When a username is included in the "authors" or "contributors" fields on a "publication" content item, a link is created in base view, but instead of going to the members' folders, they point to the current folder. See, for example, the links in the following page:

http://isaw4-dev.atlantides.org/members/paregorian/fun-with-publications/foobar

**Comment by cguardia** [comment]
It is actually trying to get the value for  the home_page property, but I see now that this property is mostly empty. Can you give me an example link please?

**Comment by cguardia** [comment]
You mean like this, right: /isaw/members/member

I initially thought you wanted the pages inside the people section.

I'll go with /isaw/members.

**Comment by paregorios** [comment]
Carlos:

Yeah, I don't think there's enough wiring up of the people pages against
the members right now for that to work. I'd love it if we did, but there
are some expensive stories that would have to be implemented to do it.

So, yes, /isaw/members is the way to go.

Thanks,
Tom

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
closing "won't fix" because I want to do something different.
