### ISSUE TITLE
images in news view do not scale proportionally

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#172]
Aspect ratio is ignored when scaling down images in the news tiled view. This is probably a CSS issue; these images should always retain their cropped aspect ratio, even when browser width forces a width scale-down.

**Comment by alecpm** [comment]
A fix for this issue has been deployed to staging.

**Comment by k2soule** [comment]
Looks good on staging.

**Comment by paregorios** [comment]
I cannot currently review this on staging. I'm getting: 

```
ImportError('cannot import name getCharset',) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: cannot import name getCharset)
```

**Comment by alecpm** [comment]
Looks like that error is SAML related @cewing ? (http://isaw4-dev.atlantides.org/prefs_error_log_showEntry?id=1479243656.480.791661126542)

**Comment by cewing** [comment]
This is related to the problems reported in #183.  I've disabled the saml2 plugins temporarily.  Please try again.

**Comment by paregorios** [comment]
agreed, this looks good. Please deploy to production

**Comment by alecpm** [comment]
Deployed.
