### ISSUE TITLE
columns scale too narrowly in exhibition objects mosaic view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#173]
Behavior should be to reflow below certain width breakpoints, just like the news tiled view. Note that aspect ratio of the images must be retained when resizing.

**Comment by cguardia** [comment]
You mean going from three columns to two or one as the page width shrinks?

**Comment by paregorios** [comment]
Yes

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
looks good

**Comment by alecpm** [comment]
Deployed
