### ISSUE TITLE
Remove press room from the isaw buildout: 1

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#174]
## When attempting to create a new "Press Room" under the current exhibition, (https://isaw.nyu.edu/exhibitions/time-cosmos) I encountered the following error:

We’re sorry, but there seems to be an error…

Here is the full error message:

[Display traceback as text] link reveals one line --> "Log entry not found or expired"

Traceback (innermost last):

```
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFFormController.FSControllerPythonScript, line 105, in __call__
Module Products.CMFFormController.Script, line 145, in __call__
Module Products.CMFCore.FSPythonScript, line 127, in __call__
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.PythonScripts.PythonScript, line 344, in _exec
Module script, line 37, in createObject
<FSControllerPythonScript at /isaw/exhibitions/time-cosmos/createObject>
Line 37
Module Products.ATContentTypes.lib.constraintypes, line 284, in invokeFactory
Module Products.CMFCore.TypesTool, line 833, in constructContent
Module Products.CMFCore.TypesTool, line 311, in constructInstance
Module Products.CMFCore.TypesTool, line 552, in _constructInstance
Module Products.PressRoom.content.PressRoom, line 7, in addPressRoom
Module Products.PressRoom.content.PressRoom, line 135, in initializeArchetype
Module Products.PressRoom.content.PressRoom, line 166, in _createSubFolders
Module Products.ATContentTypes.lib.constraintypes, line 280, in invokeFactory
```

ValueError: Disallowed subobject type: Topic

**Comment by cguardia** [comment]
The pressroom uses an old style collection (topic), which was not allowed on the site. I changed the types setting to allow it. You should be able to add the pressroom now.

**Comment by k2soule** [comment]
Thanks Carlos, I'll go try it out!
-Kristen

**Comment by k2soule** [comment]
Successfully created and edited a new Press Room. We can close this ticket.

**Comment by paregorios** [comment]
This error is back, and may be related in some way to #211

**Comment by paregorios** [comment]
@k2soule do you think we need the pressroom functionality?

**Comment by paregorios** [comment]
We no longer need Press Room. This ticket now is about removing press room from our buildout and handling any consequent messes.

**Comment by k2soule** [comment]
Kristen will take the content from the only two existing Press Rooms (T&C, EotS) and transfer it into other objects.

**Comment by alecpm** [comment]
Whoever does this, make sure to remove the `<dependency>` entry from `metadata.xml` in `isaw.policy`, and remove the one for `ftw.calendar` while you're in there.

**Comment by jessesnyder** [comment]
I deleted alecpm's comment about removing the ftw.calendar GS dependency, since I had to do this to test a different story (https://github.com/isawnyu/isaw.web/issues/310)

**Comment by jessesnyder** [comment]
I doesn't look like PressRoom content has been migrated yet:
http://isaw.nyu.edu/@@search?advanced_search=False&sort_on=&SearchableText=&portal_type%3Alist=PressClip&portal_type%3Alist=PressContact&portal_type%3Alist=PressRoom&created.query%3Arecord%3Alist%3Adate=1970-01-02&created.range%3Arecord=min

**Comment by k2soule** [comment]
I'll go through and convert those remaining pressroom instances.

**Comment by k2soule** [comment]
Finally getting back to this; the remaining Pressroom content has been migrated, and the old objects deleted.

**Comment by cguardia** [comment]
This is on staging now. The only noticeable effect is that PressRoom should not be available for install now.

**Comment by paregorios** [comment]
Looks good. Please deploy to production.

**Comment by paregorios** [comment]
I don't see this anywhere in the add-ons control panel on production, so I assume the change got deployed. Please verify.
