### ISSUE TITLE
change batch break point on "Mosaic Listing"

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#176]
It's currently set to 100 iirc. After experimenting with it and [our current folder of exhibition objects](http://isaw.nyu.edu/exhibitions/time-cosmos/objects), the consensus is our users would be better served if it were set to 21.

**Comment by alecpm** [comment]
This is deployed to staging.

**Comment by paregorios** [comment]
This looks good. Please deploy to production.

**Comment by alecpm** [comment]
Deployed
