### ISSUE TITLE
foaf.rdf links on profiles returning 404

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#178]
Every ISAW profile used to have a FOAF view, accessible by appending "/foaf.rdf" to the profile URL. The links for these are still in the header for each HTML base view (as follows), but trying to resolve that URL produces a 404. 

```html
<link rel="meta" type="application/rdf+xml" title="Profile FOAF data" href="foaf.rdf" />
```

**Comment by alecpm** [comment]
This is a bit mysterious, there's a template for this view, but as far as I can tell there's never been a registration for it. I've added a registration and deployed to staging:

http://isaw4-dev.atlantides.org/people/faculty/lorenzo-dalfonso/foaf.rdf

**Comment by paregorios** [comment]
That's the one. I wonder if it got stomped in the redesign and I just missed it until now ?!?

Anyhow, this would be great deployed to production. If it's not impossible to do first, I note the misspelling of the word "organization" in the ```rdf:ID``` attribute on ```<foaf:Organization>```. Would be nifty to fix that now if it's not a big hassle: 

```xml
    <foaf:Organization rdf:ID="orgranization">
```

**Comment by alecpm** [comment]
Deployed with spelling fix.

**Comment by alecpm** [comment]
I think we lost the registration in the initial merge of uncommitted code from the production server and ZMI code. There doesn't appear to be a commit where it was ever registered, but there was a lot of uncommitted code on production IIRC.
