### ISSUE TITLE
googlebot indexing port 8080: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#179]
Somehow the google bot has found its way into and has indexed content on the production website via the 8080 port. What can we do to tell bots to stay out of everything except port 80? 
- http://webmasters.stackexchange.com/questions/34239/how-do-i-disallow-robots-to-access-links-on-a-certain-port
- https://support.google.com/webmasters/topic/4598466?visit_id=1-636134329057129783-1014694583&rd=1

**Comment by alecpm** [comment]
I think we should possibly be firewalling off access to those ports to traffic other than from a few allowed IPs. Is there a reason to allow direct access to 8080 for isaw? We could adjust the dynamic robots.txt to restrict to a specific server port, but that could get a little tricky with the mix of proxies and virtualhosting in play (traffic generally goes 80/443 -> 6081 -> 8080 -> 808[1-3]). If we can just disallow public access to 6081 and 8080-8089 that would probably be the most secure solution.

**Comment by paregorios** [comment]
@alecpm I don't see any reason that we need to keep those ports open publicly. Let's lock it down.

**Comment by alecpm** [comment]
For ISAW, I think firewall changes might best be done by Tummy. I suspect the only ports you really want open to the public are 22, 80, and 443, but there may be some additional ports expected by the SSO implementation or some other external facing services on the machine I'm not aware of. @cewing?

**Comment by paregorios** [comment]
Right. I'll wait to hear @cewing's opinion and then move forward on this with Tummy.

**Comment by cewing** [comment]
I cannot see any reason we require direct access to 8080.  If we need to access instances directly we can use an ssh tunnel, so yeah, let's close that down.

**Comment by alecpm** [comment]
@cewing any other ports we might need open for auth stuff? Otherwise, I think keeping 22, 80, and 443 open and closing the rest down is probably the way to go.

**Comment by cewing** [comment]
No.  Shibboleth uses https as the transport layer, so 443 is sufficient.  Current setup requires port 80 for unauthenticated access, so that should remain open.  And 22 for ssl is obviously required.  Nothing else comes to mind.

**Comment by paregorios** [comment]
Since this is so old, I'm closing it. We'll open a new ticket if we spot problems in future.
