### ISSUE TITLE
publication base view does not match wireframe

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#181]
While reviewing [scrumdo story 150 (base view for new "publications" type)](https://www.scrumdo.com/projects/story_permalink/1101334) I encountered the following divergences from the wireframe ([see examples in this folder on staging](http://isaw4-dev.atlantides.org/members/paregorian/fun-with-publications-2)):

 - ```lead image``` is not styled properly. It presently occupies the full width of the content area and aspect ratio is not preserved. Wireframe suggests it should only occupy the left third of the content area.
 - ```access URIs``` do not appear even when they have been filled on the content type
 - ```review URIs``` do not appear even when they have been filled on the content type
 - ```order URIs``` do not appear even when they have been filled on the content types
 - when a username is converted to a full name with a link in ```authors```, ```editors```, and ```contributors``` the generated link points back to the current item.
 - line wrap on ```authors```, ```editors```, and ```contributors``` fields should use hanging indent.

For reference, here is the same wireframe that was provided in the scrumdo story:

![pubs-layout](https://cloud.githubusercontent.com/assets/263285/20154465/1a1a7ce2-a68d-11e6-8461-618d415363cb.jpg)

**Comment by cguardia** [comment]
I put in the wrong image scale, and apparently my test images are too small. Do you prefer to use one of the site scales or to set a fixed width and let the height scale accordingly?

**Comment by paregorios** [comment]
I just fiddled with CSS in my browser and I think the following might work. What do you think:

 * div.PublicationImage: width: 450px; max-width: 50%;
 * div.PublicationImage img: max-width: 100%; height: auto

But when we're below the mobile breakpoint, we should *not* use the 50% max-width on the div.PublicationImage

Thoughts?

**Comment by cguardia** [comment]
Seems to work fine with those settings. I fixed the other things too, except for the user link. This is because I believe the ideal thing would be to link to the user page and that is in a separate story, I think.
