### ISSUE TITLE
style new profile link icons

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#184]
[Scrumdo story 162](https://www.scrumdo.com/projects/story_permalink/1103863) implements an "external URIs list". After reviewing the initial implementation on staging, I would like to suggest a refinement of the layout and style. I think this will entail moving the ```<ul class="ProfileLinks">``` element and its content out of ```<div class="ProfileInfo">```, as well as some CSS fiddling. Here's sort of what I'd like to see:

<img width="880" alt="profile-icons-layout" src="https://cloud.githubusercontent.com/assets/263285/20223681/466084da-a800-11e6-9ea9-a9953d7dfbe0.png">

A couple of notes:

 - I think the spacing between these icons is 0.5em; 0.25 or 0.3em might be better
 - Right now the "blah blah profile" text is being put in a ```<span>``` right after the link. Let's get rid of that span and its contents and instead put that text in a "title" attribute on the ```<a>``` tag, which will cause it to appear in a pop-kite on hover.

**Comment by paregorios** [comment]
NB: the "personal website" line in this example is the first formatted line in the body text; it's not something I'm asking be implemented as part of story 162.

**Comment by alecpm** [comment]
These changes are now implemented on staging.

**Comment by paregorios** [comment]
@alecpm that's looking good. Can we cancel the mouseover CSS underline behavior on links in that list context only? It looks a little odd.

**Comment by alecpm** [comment]
This is updated on staging.

**Comment by alecpm** [comment]
This was deployed to production along with other fixes from master.

**Comment by paregorios** [comment]
@alecpm I don't see on production the CSS tweak to get rid of the underline mouseover effect [mentioned above](https://github.com/isawnyu/isaw.web/issues/184#issuecomment-260732271).

**Comment by alecpm** [comment]
Refreshing the registry seems to have fixed this.

**Comment by paregorios** [comment]
Unfortunately we are still seeing this in Chrome and Firefox (but not Safari) on OSX (on multiple machines).

**Comment by alecpm** [comment]
Fixed.

**Comment by paregorios** [comment]
Perfect! Thanks.
