### ISSUE TITLE
enhanced publication import from zotero not working on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#190]
Regarding [scrumdo story 153: import extra fields into "publications" item from zotero](https://www.scrumdo.com/projects/story_permalink/1101589):

Although the story is marked "deployed" in scrumdo, the additional field imports do not work as they did on staging. I just created a new publication at https://isaw.nyu.edu/members/te20-40nyu.edu/new-pub-experiments/amheida-i-ostraka-from-trimithis-1 and imported this Zotero record: https://www.zotero.org/groups/isaw_publications/items/itemKey/JCIQNFKW. The title, short title, summary, and formatted citation were imported correctly, but the following fields were not:

 - authors
 - place
 - publisher
 - date
 - ISBN
 - access URI

**Comment by alecpm** [comment]
Looks like there was an issue with that specific Zotero reference which had formatted author/editor/contributor names differently than the others I had looked at. I've implemented a more general solution and applied it to production.

**Comment by paregorios** [comment]
That's got it, thanks.
