### ISSUE TITLE
easytemplate errors are not surfaced in the UI

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#191]
collective.easytemplate advertises that template errors on a "Templated Document" will be surfaced to the user if the "Catch Errors" checkbox on the "Template" tab is selected. This does not seem to be the case (is a special div getting written that doesn't get passed through our theme chain?).

It would greatly help debugging some templates I'm trying to write if I could see errors, not least because I have reason to believe that the version of Jinja we're working with here doesn't implement everything found in the docs (e.g., trying to use aspects of the "loop" variable inside a for loop either produce an opaque 'there are errors' notice or just throw me back bizarrely into the base_edit view). Either that or there's some aspect of the syntax I don't have right and, without a specific error message, I'm hunting in the dark. 

This is blocking content development work.

**Comment by cguardia** [comment]
I fixed this, but the message is not very helpful from what I can see. Just tells you the type of error.

Would probably be more helpful to go to /prefs_error_log_form and hunt for the error there.

**Comment by cguardia** [comment]
This is on staging, by the way.
