### ISSUE TITLE
"button" portlets not available after deployment

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#192]
RE [scrumdo story 165](https://www.scrumdo.com/projects/story_permalink/1104854):

If this were fully deployed, I should see a "Button" portlet in the "Add Portlet" combo box pull-down, but I don't:

<img width="268" alt="screen shot 2016-12-08 at 5 58 45 am" src="https://cloud.githubusercontent.com/assets/263285/21009310/8fef29ec-bd0b-11e6-8e83-1350a0037dcf.png">

Compare behavior on staging, where this portlet is available in the pull down.

**Comment by cguardia** [comment]
Turns out the merge with staging caused upgrade steps to not show up on the control panel, due to the install profile version. Ran the steps manually and the portlet now show up in the list and works.

**Comment by paregorios** [comment]
I'm still not seeing it on production, e.g. here: https://isaw.nyu.edu/events/event-home/@@manage-portlets . I did shift-reload.

**Comment by cguardia** [comment]
Please try again. I ran the step only on staging before.

**Comment by paregorios** [comment]
That's got it! Thanks!
