### ISSUE TITLE
mosaic listing busted on staging

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#193]
Looks possibly like a CSS edit mistake:

https://isaw4-dev.atlantides.org/exhibitions/time-cosmos/objects

**Comment by cguardia** [comment]
I didn't make any changes to exhibition css. I doublechecked my css changes and there is no error. I do see a awld js error. @alecpm any ideas?

**Comment by cguardia** [comment]
We seem to have a weird error inside awld minified js from some pages.

**Comment by cguardia** [comment]
It looks like there’s some incompatibility between the requirejs setup that awld uses and the site’s jquery install. @alecpm is looking into that.

**Comment by alecpm** [comment]
This should be fixed now.

**Comment by paregorios** [comment]
yes, this appears to be fixed. Thanks.
