### ISSUE TITLE
error displaying a collection (production)

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#195]
When creating a collection on the production web, I encountered an unexpected error (copied below). It happened as I was trying out different display options. I can no longer edit the item.
https://isaw.nyu.edu/exhibitions/test-collection-kbs

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: /srv/isaw.web/src/isaw.theme/isaw/theme/browser/templates/tiled_view.pt
   - Line 62, Column 6
   - Expression: <PythonExpr (view.get_image(item))>
   - Names:
      {'args': (),
       'container': <Collection at /isaw/exhibitions/test-collection-kbs>,
       'context': <Collection at /isaw/exhibitions/test-collection-kbs>,
       'default': <object object at 0x7f5b40e074e0>,
       'here': <Collection at /isaw/exhibitions/test-collection-kbs>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f5b1af0c3c0>,
       'request': <HTTPRequest, URL=https://isaw.nyu.edu/exhibitions/test-collection-kbs/tiled-listing>,
       'root': <Application at >,
       'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f5b28f13ed0>,
       'traverse_subpath': [],
       'user': <PloneUser 'ks156@nyu.edu'>,
       'view': <Products.Five.metaclass.SimpleViewClass from /srv/isaw.web/src/isaw.theme/isaw/theme/browser/templates/tiled_view.pt object at 0x7f5b1ae601d0>,
       'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f5b1ae606d0>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.get_image(item))
  Module <string>, line 1, in <module>
  Module isaw.theme.browser.tiled_view, line 81, in get_image
  Module plone.app.imagecropping.browser.scalingdx, line 34, in scale
  Module plone4.csrffixes.patches, line 21, in namedfile_scale
  Module plone.namedfile.scaling, line 337, in scale
  Module plone.scale.storage, line 162, in scale
  Module plone.app.imagecropping.browser.scaling, line 88, in create
  Module plone.namedfile.scaling, line 256, in create
AttributeError: leadImage

**Comment by paregorios** [comment]
@skleinfeldt this bug is blocking active content creation.

**Comment by skleinfeldt** [comment]
@paregorios @k2soule sorry I didn't realize this was urgent last night.

@cguardia @alecpm @jessesnyder can whoever wakes up first fix this please?

**Comment by cguardia** [comment]
Looking into this now.

Carlos de la Guardia

**Comment by cguardia** [comment]
Fixed. apparently, some objects do not have image fields. Added a safeguard.

Carlos de la Guardia

**Comment by paregorios** [comment]
@k2soule please test and let us know if everything is now working as you expect. Thanks.

**Comment by paregorios** [comment]
appears resolved.
