### ISSUE TITLE
Publication Item Author list showing currently logged-in user

### ISSUE THREAD

**Issue by sfsheath** [isawnyu/isaw.web#196]
I have created https://isaw.nyu.edu/publications/newpubs/books/graffiti-from-the-basilica-in-the-agora-of-smyrna the our recently published Smyrna Graffiti volume. My name is listed in the "by:" field. It shouldn't as I am not an author of the volume, only the creator of its "item" (right term) in plone.

**Comment by paregorios** [comment]
This is actually even weirder than it appeared at first to @sfsheath. In the base view for publications on production, something is writing the username and link for the currently logged-in user in at the end of the "authors" field.

**Comment by alecpm** [comment]
@paregorios could you provide a screenshot? I'm not seeing this behavior. Probably because my logged-in user doesn't have an associated profile, or perhaps because my login isn't via shibboleth. Seeing how exactly it appears in-page may help me track it down though.

**Comment by paregorios** [comment]
@alecpm I cannot not re-create this error. @sfsheath can you see if you are still seeing this behavior?

**Comment by alecpm** [comment]
Hm, if it went away, then I have a good idea what the cause might be. Is it back now?

**Comment by paregorios** [comment]
@alecpm yes, yes it is back now

**Comment by paregorios** [comment]
Please let me know when this code fix is deployed and when and where I can test.

**Comment by alecpm** [comment]
Should be up on staging and production. Test by adding a blank line after the last author/editor/contributor, and confirm that it no longer displays the currently logged in user as the last entry (and if logged in without a profile link does not display a trailing comma).

**Comment by paregorios** [comment]
This does appear fixed to me. @sfsheath do you concur?

**Comment by sfsheath** [comment]
I concur.
