### ISSUE TITLE
both types of "collection" are back

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#198]
Something has brought back both types of collections (old and new style) as addable content items on both staging and production. I'd like to revert to what we had before (subject to accommodating whatever dependency in an add-on has presumably led to this); it's confusing as heck for our content creators (and me).

![screen shot 2016-12-20 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/263285/21366778/e3ce475a-c6c0-11e6-9859-55bf7d568426.png)

**Comment by paregorios** [comment]
If at all possible, I'd also like to see something put in place that will stop this from re-regressing in future. We've cleaned this up more than once iirc.

**Comment by alecpm** [comment]
I've fixed this manually, and also made a change to the add-on profiles to specifically disable old-style collections whenever the types profile step is re-run.

**Comment by paregorios** [comment]
Great, thanks! Looks good.
