### ISSUE TITLE
publication image viewer not loading

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#202]
When viewing a publication item on production, if I click on the thumbnails to see additional images, I get a spinning pinwheel instead. So far I've tried this in firefox and chrome on MacOS.

Here is an example object: 
https://isaw.nyu.edu/exhibitions/catalogues/time-and-cosmos-in-greco-roman-antiquity

**Comment by skleinfeldt** [comment]
Hi @k2soule - do you and @paregorios want us to use some of our little bit of remaining time (1.2 hours) on this?

**Comment by paregorios** [comment]
I'm doing a scrub on tickets and will have guidance tomorrow or Monday.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott


On Thu, Jan 26, 2017 at 11:53 AM, Sally Kleinfeldt <notifications@github.com

**Comment by paregorios** [comment]
hi @skleinfeldt sorry for the delay. Yes, I think we need to see if we can get this fixed with the money remaining. There are various other loose ends -- not least deployment of the SSO fix -- but I think those are bigger than the resource we have currently devoted to the work.

**Comment by skleinfeldt** [comment]
OK @paregorios I just rechecked, we have a little over an hour left so this will probably finish us off. We are maxed out this week, but hoping @alecpm can fix this next week.

**Comment by paregorios** [comment]
Hi @skleinfeldt @alecpm can you update me on status of this issue? Thanks.

**Comment by paregorios** [comment]
cc @k2soule

**Comment by skleinfeldt** [comment]
Very sorry for the delay @paregorios and thanks for the ping. @alecpm says he can work on this next week and I will remind him.

**Comment by paregorios** [comment]
OK thanks.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
Hi @alecpm and @skleinfeldt ... how are things looking for dealing with this issue this week as hoped?

**Comment by skleinfeldt** [comment]
@alecpm says today's the day...

**Comment by alecpm** [comment]
All fixed. There was a migration step for the theme (installing AWLD support) which hadn't been run on production. That resulted in some JS errors.

**Comment by paregorios** [comment]
Cool. @k2soule can you test on production at your earliest opportunity?

**Comment by k2soule** [comment]
The image viewer is loading, but I'm only seeing partial images for some of the landscape-oriented ones. Here is an example: https://isaw.nyu.edu/exhibitions/catalogues/designing-identity-the-power-of-textiles-in-late-antiquity

**Comment by paregorios** [comment]
This appears to be another case in which the CSS rules assigned are not robust enough to handle varying image sizes and responsive needs. Height of the image appears to be hard-set to 500px and the width is allowed to vary by inherited behavior. Given constraints (or lack thereof) on containing elements, this doesn't work well for landscape-oriented images (as in the example linked above), and things get worse with smaller viewports. CSS needs a rework on component.

**Comment by paregorios** [comment]
See also #200.

**Comment by paregorios** [comment]
See also #199

**Comment by paregorios** [comment]
hi @alecpm do you have a feel when/whether you will be able to look at [the "partial images" aspect of this problem described above](https://github.com/isawnyu/isaw.web/issues/202#issuecomment-284086350) by @k2soule ? 

Thanks (cc @skleinfeldt).

**Comment by alecpm** [comment]
I've got a fix up on staging now: https://isaw4-dev.atlantides.org/exhibitions/gallery-shop-test/greenery-with-helicopter

Let me know if/when you'd like me to push it to production. I think down the link you may want to consider using leaflet as a viewer for the images in the overlay (e.g. http://kempe.net/blog/2014/06/14/leaflet-pan-zoom-image.html).

**Comment by paregorios** [comment]
@k2soule at your earliest opportunity, please review the fixed version that @alecpm has posted to staging ...

**Comment by k2soule** [comment]
Looks good on staging; please deploy this fix to production.

**Comment by alecpm** [comment]
The style tweak is now deployed to production.

**Comment by k2soule** [comment]
Looks good - thanks! I'm closing this ticket.
