### ISSUE TITLE
Underlines appearing unexpectedly on mouse-over: 2

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#204]
I first noticed this on the home page image slider, after the most recent major update: there are underlines appearing beneath the dots when I mouse over them. I've since noticed that there are also underlines appearing in between thumbnails in the Publication objects. This appears to be a style glitch.

**Comment by paregorios** [comment]
Confirmed. I think this is a regression that we fixed previously. :(

**Comment by paregorios** [comment]
We've changed the way these controls look and work for accessibility reasons, so this is no longer a concern.
