### ISSUE TITLE
Event lead image blocks part of editing toolbar: 2

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#219]
There is a problem with the alignment of content in event objects for content editors; if there is a lead image in the event, it appears shifted upward when one is logged in - such that it partially obscures the right side of the editing toolbar and blocks access to some of the menus.

Here is an example: https://isaw.nyu.edu/events/the-prehistory-of-crete

**Comment by paregorios** [comment]
Note also #322

**Comment by alecpm** [comment]
I've deployed a fix for this and #322 to staging. I moved the image container above the title so it could be properly floated next to the title and also z-indexed it below the edit toolbar.

**Comment by paregorios** [comment]
See comment added to #322

**Comment by alecpm** [comment]
Margin fix is in place.

**Comment by paregorios** [comment]
Splendid! Please merge to master and deploy.

**Comment by paregorios** [comment]
works on production
