### ISSUE TITLE
Lost event images

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#22]
The images on the pre-upgrade custom event types should have become lead images on the post-upgrade [almost] stock Plone events. Troubleshoot why this did not happen and propose a solution, with estimate.

**Comment by paregorios** [comment]
see scrumdo stories 56 and 104

**Comment by cguardia** [comment]
The migration script did have code to deal with this, not sure why it failed. Can you give me an example of an event that you know for sure that had an image? I think I can write a script to get the images from the old server.

**Comment by paregorios** [comment]
So I guess I'd better ask Tummy not to turn this off tomorrow while we try to get this sorted? I won't have time to hunt down images until this afternoon at earliest.

**Comment by cguardia** [comment]
I should be able to do this tonight. I don't think we will need more time than that.

**Comment by paregorios** [comment]
Here's an example event (now expired) that we know had an image:

/events/king-and-courtiers

**Comment by cguardia** [comment]
The images have been restored.

**Comment by paregorios** [comment]
confirmed. closing: fixed
