### ISSUE TITLE
a test area for front-page slider image/overlay review is needed

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#222]
Preferably within the production site, rather than on dev, so as not to mix concerns and to reduce work.

**Comment by k2soule** [comment]
We can call it "home-staging", or just "staging" and locate it within the existing home-slides folder so that it's easy for content editors to find. Specifically, the News Editors group should have access to edit this front-page slider test area.

**Comment by paregorios** [comment]
deployed and working
