### ISSUE TITLE
cannot edit speaker name/subtitles on events

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#23]
In the "events" slider view on the ISAW home page and in the events main page (https://isaw.nyu.edu/events) we see information (in bold) about subtitle/speaker. But this information does not show up in the individual event view, nor in the edit view. We have had to retract at least one upcoming event because we cannot correct erroneous information. 

Example: on home page and /events you'll see under "Rostovtzeff Lecture Series: Sumer in the Mesopotamian World: Reading Traditions & Traditions of Reading, III" the following:

*Reading Early Economy Now: Bureaucracy & Administration in Sumer*
**Gonzalo Rubio, Pennsylvania State University**

Neither of these lines appears at https://isaw.nyu.edu/events/rostovtzeffthree nor is there a way to edit them that we can see at https://isaw.nyu.edu/events/rostovtzeffthree/edit

**Comment by cguardia** [comment]
Speaker and subtitle are not standard event fields. Looks like I mistakenly copied those fields when migrating. Should I just remove those lines from the template?

**Comment by paregorios** [comment]
According to stories number 56 and 104 in scrumdo, these fields should have been handed in an extended Plone event type. It looks like coding work on that was done, but not yet merged for deployment on production. See comments there?

**Comment by cguardia** [comment]
Sorry for the confusion. We thought we had somehow failed to merge that branch, but it turns out that the problem was just a missing upgrade step. Fixed.

**Comment by paregorios** [comment]
We can now see and edit these fields in the "edit" form (e.g. https://isaw.nyu.edu/events/rostovtzeffthree/edit ) but they do not appear in the view template at all (e.g., https://isaw.nyu.edu/events/rostovtzeffthree ). What would it take to get them to appear there too?

**Comment by cguardia** [comment]
That's pretty easy to do. Just tell me where you want them.

**Comment by paregorios** [comment]
Immediately after description. Prefer the following order:

subtitle
speaker
speaker affiliation

**Comment by cguardia** [comment]
Done.

**Comment by paregorios** [comment]
confirmed. closing.
