### ISSUE TITLE
Mark header/banner as such on all pages: 0.5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#232]
> The top most region is best encapsulated as a banner/header.
> role = banner (ARIA), header (HTML5)

Traceability: [Microassist Report 1 > Home Page Template > Landmarks](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.7rvkgwq4gpnr)

**Comment by paregorios** [comment]
![image](https://user-images.githubusercontent.com/263285/36857072-37bba942-1d3d-11e8-812c-1d7779259891.png)

**Comment by jessesnyder** [comment]
@paregorios Attempting to walk a single one of these all the way through before moving on. 

I changed the markup from:

`<div id="portal-top">`

to:

`<header id="portal-top" role="banner">`

**Comment by paregorios** [comment]
This looks ready to deploy to me!

**Comment by paregorios** [comment]
Verified fixed and live on production.
