### ISSUE TITLE
Mark search toggle on all pages for accessibility: 0.5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#235]
> role = button (ARIA), button (HTML5)
> Will need aria-label of “search toggle”

Traceability: [Microassist Report 1 > Home Page Template > Landmarks](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.7rvkgwq4gpnr)

**Comment by paregorios** [comment]
![image](https://user-images.githubusercontent.com/263285/36857144-616e3912-1d3d-11e8-88fa-b0e01ab28ad7.png)

**Comment by paregorios** [comment]
This looks good. Please:

 - [ ] merge to master
 - [ ] deploy to production

**Comment by alecpm** [comment]
Will make a deploy of all new features on master tonight.

**Comment by paregorios** [comment]
Confirmed deployed to production. Closing.
