### ISSUE TITLE
clicking on a day in the events portlet calendar throws a traceback

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#24]
Click on any linked date in the little calendar in the right-hand portlet under https://isaw.nyu.edu/events/ and you'll get an error, e.g., KeyError: 'portal_syndication' for https://isaw.nyu.edu/search?review_state=external&amp;review_state=internally_published&amp;review_state=published&amp;start.query:record:list:date=2015-3-17+23%3A59%3A59&start.range:record=max&end.query:record:list:date=2015-3-17+00%3A00%3A00&end.range:record=min from

**Comment by cguardia** [comment]
Fixed this one temporarily on custom skin. Will move fix to github later today.

**Comment by paregorios** [comment]
This does now appear to be working on production. But is that result of custom skin still, or has it been updated from repos?

**Comment by cguardia** [comment]
The code has been updated. The custom template was removed.

**Comment by paregorios** [comment]
Confirmed works! Thanks. Closing.
