### ISSUE TITLE
Mark "pager" elements for accessibility: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#241]
> role = navigation (ARIA), nav (HTML5)
> Will need aria-label of “pager” to distinguish it from other navigational elements.

**Comment by paregorios** [comment]
E.g., on the exhibitions object page:

![image](https://user-images.githubusercontent.com/263285/36857730-e9704aca-1d3e-11e8-9166-86be16559114.png)

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
looks good; please merge to master and deploy to production

**Comment by paregorios** [comment]
this is working on production
