### ISSUE TITLE
Mark event search form for accessibility: 0.5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#242]
> role = search (ARIA), no HTML5 equivalent
> Needs aria-label “event search” to distinguish from other search features.

Traceability: [Microassist Report 1 > 2-3 Template > Landmarks](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.nsr5zxa3y5m)

**Comment by paregorios** [comment]
See also #271

**Comment by paregorios** [comment]
This looks good. Please:

 - [ ] merge to master
 - [ ] deploy to production

**Comment by alecpm** [comment]
Put it back into doing and I'll make the change with the events search form styling adjustment.

**Comment by alecpm** [comment]
The search role is in place on staging.

**Comment by paregorios** [comment]
Great! Please merge to master and deploy to production.

**Comment by paregorios** [comment]
Verified deployed.
