### ISSUE TITLE
Ensure tab order in each media context/screen size facilitates accessibility: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#245]
When in desktop CSS layout:

> - “Skip to Main” link
> - NYU Institute for the Study of the Ancient World home logo link
> - Top Bar Menu
> - Main Menu
> - Breadcrumbs
> - Main Content Area
>   - Tab only to focusable elements. 
> - Sidebar
>   - Should focus top to bottom including the expand/collapse buttons.
> - Footer links

When in mobile CSS layout:

> Tab order for the mobile will be slightly different since the hamburger menu > is active.
> 
> - NYU Institute for the Study of the Ancient World home Link
> - Hamburger Menu
> - Menu Items 
>   - Should focus from top to bottom
>   - Includes search bar
> - Close button
> - Main Content Area
>   - Tab only to focusable elements. 
> - Footer links

![screen shot 2018-04-24 at 2 24 02 pm](https://user-images.githubusercontent.com/263285/39209328-30315ca4-47cb-11e8-9dde-bd36919196cc.png)

![screen shot 2018-04-24 at 2 22 00 pm](https://user-images.githubusercontent.com/263285/39209226-e7df6d06-47ca-11e8-9eba-20943674e640.png)

Traceability: [Microassist Report 1 > Tab Order > Desktop](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.eepwjm61ggl3)

Traceability: [Microassist Report 1 > Tab Order > Mobile](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.4mkj2hwc2atp)

**Comment by paregorios** [comment]
Regarding mobile view see also https://github.com/isawnyu/isaw.web/issues/234#issuecomment-369957983

**Comment by paregorios** [comment]
WCAG says:

"focusable components receive focus in an order that preserves meaning and operability."

So, I think our current behavior of tabbing through main nav (colorful) before we tab through secondary nav (top gray bar) is good.

**Comment by alecpm** [comment]
I think this is working well at this point, though we need better focus indications on the logo, search button, breadcrumbs, and navigation portlet among other things.

**Comment by paregorios** [comment]
OK. Merge and deploy to production. I'll create new ticket(s) for the remaining focus indication contexts.

**Comment by paregorios** [comment]
@alecpm @skleinfeldt can you verify that this has been merged to master and deployed to production? Thanks

**Comment by paregorios** [comment]
Sorry I got confused. Disregard previous comment.
