### ISSUE TITLE
editor drop-down menus show up in odd place

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#25]
The "style" and "font size" drop-downs on the content editor toolbar show up half-way down the page instead of immediately below the click point. See screen capture.

![wonky](https://cloud.githubusercontent.com/assets/263285/6676684/cbf2d490-cbf7-11e4-9731-2dc27f921d57.jpg)

**Comment by paregorios** [comment]
@skleinfeldt Still seeing this on production. Should I have assigned this to someone else?

**Comment by skleinfeldt** [comment]
No I'm the right person, sorry I didn't respond. I had moved into "no more hours on ISAW for now!" mode and was hiding my head in the sand. But we can fix it now if it is getting in the way - ?

**Comment by paregorios** [comment]
It doesn't seem to be bugging anyone but me. Let's defer unless there's howling.

**Comment by paregorios** [comment]
See now https://github.com/isawnyu/isaw.theme/issues/6

**Comment by paregorios** [comment]
This I think is because of the setting that puts the editor bar at the top of the browser window (which is now also clashing with the header). I'm going to try changing the editor settings and see what happens.

**Comment by paregorios** [comment]
I changed the settings and it's more workable to have the menu bar attached to the individual content boxes I think. There's still a bug IMO as described above, but I'm going to close this ticket "won't fix" anyway since this workaround works.
