### ISSUE TITLE
not seeing crop tools in editor on production 

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#26]
Apropos scrumdo story 96 (Image Editing Features), I don't see [a cropping tab](http://webmeisterei.com/news/image-cropping-for-everyone) or anything like that when editing or editing images on production, even though the plone.app.imagecropping product seems to be installed. What am I missing?

**Comment by alecpm** [comment]
I'm seeing the cropping tab for example here:

http://isaw.nyu.edu/library/copy_of_photooflibrarybookstacks.jpeg/@@croppingeditor

**Comment by paregorios** [comment]
Ah, thanks for that. I didn't understand that the cropping functionality showed up on the image page itself, rather than via the editor. All good! closing.
