### ISSUE TITLE
left-floated images don't wrap captions to match image width: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#261]
For example:

![screen shot 2018-04-27 at 7 22 38 am](https://user-images.githubusercontent.com/263285/39362414-fab33138-49eb-11e8-8352-6e71444a20ec.png)

**Comment by alecpm** [comment]
For reference: http://isaw.nyu.edu/news/isaw2019s-workshop-201cprogress-problems-and-possibilities-of-gis-in-the-south-caucasus201d-published-in-antiquity

**Comment by alecpm** [comment]
Hm, it seems like this might be a bad example. The "caption" text there was entered manually via some means I don't fully understand (it's got a bunch of div markup with `data-canvas-width` attributes and is not actually connected to the image in the HTML at all). I updated the image on staging to use the built-in captioning and it seems to align correctly, though it is styled quite differently:

https://isaw.jazkarta.com/news/isaw2019s-workshop-201cprogress-problems-and-possibilities-of-gis-in-the-south-caucasus201d-published-in-antiquity

**Comment by paregorios** [comment]
Closing cannot duplicate.
