### ISSUE TITLE
Syndication: need to include creator name in feed

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#27]
This appears to be a bug; when information about a news item is pulled into the RSS feed, it is omitting the creator; it looks like there are empty <dc:creator> fields in the feed. It would be great to find a fix for this.

**Comment by paregorios** [comment]
double-check to see if this is still (not) happening.

**Comment by paregorios** [comment]
* Atom feed has creator properly populated (although it would be nice if username were looked up and i nserted instead of plone username).
 * RSS 2.0 output has no field in it right now for the creator
 * RSS 1.0 has empty dc:creator fields as outlined above in issue thread.

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
Looks good. Please deploy to production at your convenience.

**Comment by alecpm** [comment]
This should be deployed to production now.

**Comment by k2soule** [comment]
Assigning to Tom for comment (if any) before closing.
