### ISSUE TITLE
Make “View More” link on the news page accessible: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#270]
> The “View More” link on the news page should also be a button instead of a link and also not a toggle. Links take a user to another page, buttons activate or submit functions. The functionality of the toggle is to open and close an interactive element on the page. The behavior pattern (causing a non navigatory change within the current page) is closer to the functional connotation of a button.

![screen shot 2018-04-27 at 3 08 54 pm](https://user-images.githubusercontent.com/263285/39382932-ef19c788-4a2c-11e8-97d1-8eecc1a4543d.png)

> Resource: https://marcysutton.com/links-vs-buttons-in-modern-web-applications/

WCAG 2.0 Compliance: ???

Traceability: [Microassist Report 1 > WCAG Compliance > Name, Role, Value](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.t8cmbkue4bcm)

**Comment by jessesnyder** [comment]
@paregorios I see similar (possibly identical) code in the template for listing events. Is there a story on the backlog about that also? Ah... just looked at the site, and there simply aren't enough events to expose the problem. If the solution is indeed the same, I'll fix both places.

**Comment by jessesnyder** [comment]
@paregorios The extendable listing on the events page doesn't seem to work at all currently. If you request all events (http://isaw.nyu.edu/events?SearchableText=&SearchAll=yes) and then hit the "View more" link/button, you get a JS error and the extension doesn't work. I'll see if I can get it working in the context of this ticket.

**Comment by jessesnyder** [comment]
OK, so a fix which works with the "search all events" option is going to be more involved, but it now works for batch-worthy quantities of future events (I tested locally only; you may want to throw some events in there and test on staging*).

*my preferred technique: make 3 future, published events, then copy and paste them several times in the /folder_contents view. Boom: many future events.

**Comment by k2soule** [comment]
I've made a bunch of future events on staging, and checked to confirm that the "view more" button is working in that context.

One oddity that I noticed in both News and Events on staging is that the pages only load two items at a time. It's preferred to have News load the first 6 or 9, so that it fills the 3-column grid. For Events, better to load 3 or more at a time.

**Comment by jessesnyder** [comment]
@k2soule Gah... I accidentally committed the change to batches of 2 I was using to making testing easier! I'll revert that, then we should be good to go.

**Comment by jessesnyder** [comment]
Fixed!

**Comment by k2soule** [comment]
Thanks!

**Comment by jessesnyder** [comment]
Merged to `master`
