### ISSUE TITLE
Eliminate repetition of empty "viewlet-below-content" elements: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#273]
> The ```<div>``` element with the id “viewlet-below-content” is empty and has already been defined (i.e., used elsewhere). An id is a unique identifier. Each time this attribute is used in a document it must have a different value. If you are using this attribute as a hook for style sheets it may be more appropriate to use classes.

![screen shot 2018-04-27 at 3 54 55 pm](https://user-images.githubusercontent.com/263285/39384698-5b8459b4-4a33-11e8-97a6-72800b8ffb9c.png)

> Resource: https://www.w3.org/TR/WCAG20-TECHS/H44.html

WCAG 2.0 Compliance: [4.1.1. Parsing](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

> In content implemented using markup languages, elements have complete start and tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features. (Level A)

Traceability: [Microassist Report 1 > WCAG Compliance > Parsing](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.9b291xk40aeb)

**Comment by jessesnyder** [comment]
@paregorios It looks like the second occurrence of this viewlet was added unnecessarily to the main theme template, one or two levels outside its correct container. Removed, and looking good now.

**Comment by paregorios** [comment]
Verified fixed and deployed to production.
