### ISSUE TITLE
exhibition objects need iterate support: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#274]
There is no option to "check out" a working copy on the "actions" menu for an exhibition object.

**Comment by alecpm** [comment]
This is now available on staging:

https://isaw.jazkarta.com/exhibitions/romance-reason/rrobjects/alexanders-wall

To enable this I also ended up enabling the related items behavior on the type along with versioning.

**Comment by paregorios** [comment]
This looks good. Related items is fine. Please:

 - [ ] merge to master
 - [ ] deploy to production

**Comment by paregorios** [comment]
Confirm deployed to production. Closing.
