### ISSUE TITLE
navigation portlet disappears when associated content is changed: 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#277]
Steps to recreate:

 - Assign navigation portlet in left slot on a folder
 - Notice the nav portlet is where you want it
 - Rename the short name of the folder
 - Look in vain for the nav portlet
 - Rename the folder back to its prior short name
 - The nav portlet magically reappears

It should not disappear ever, regardless.

**Comment by k2soule** [comment]
example folder:  https://isaw.nyu.edu/exhibitions/silver-roman/
At Alec's suggestion, I gave this test area a variety of different portlets. When I changed the shortname of the folder, *only the nav portlet* disappeared.

**Comment by alecpm** [comment]
I believe I see what's happening here. From what I can tell, it only occurs if the portlet has had an explicit "Root node" set. That "Root node" specifies a path that is saved with the portlet, and is not updated if the name of that path changes. If you then change the name of the item it looks for content under that path, finds none and doesn't render.

We could try to patch plone to update the portlet settings when a folder is renamed, but that seems like it would be a bit fiddly and bug prone. I would suggest not using the "Root node" feature and instead use the "Start level" to tell the portlet to show only items below a  certain tree depth (in the case of `/exhibitions/silver-roman` that would be 2).

**Comment by alecpm** [comment]
I think in Plone 4.3 the "Root node" feature is best reserved for cases where you wish to display a navigation tree for a section of the site other than the one currently being viewed. In Plone 5 the navigation portlet stores UIDs to mark the navigation root instead of the path, which removes this issue.

**Comment by paregorios** [comment]
We think we can make things work as is. Closing "won't fix". We'll resurrect if we get stuck in future.
