### ISSUE TITLE
make "filter results" functionality on search accessible: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#278]
> The “filter the results” option should not automatically update the results on the selection of the
checkbox to exclude the item type. This option should require a submit option or should have
the same submit button as the search text field and be placed visually before the search submit.

![screen shot 2018-06-06 at 9 50 30 am](https://user-images.githubusercontent.com/263285/41045956-165cc69a-696f-11e8-8ddc-16fafd7207d6.png)

Traceability: Microassist "Complex Interaction Plan"

**Comment by alecpm** [comment]
https://ux.stackexchange.com/questions/118488/does-faceted-search-fail-accessibility?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by cguardia** [comment]
@paregorios, according to the question linked above by @alecpm, one way to fix this would be to use an aria-live region (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). That would keep the functionality as it is, but would help users with accessibility issues. Do you think that's enough for this case?

**Comment by paregorios** [comment]
@cguardia I would be happy to see this issue resolved by using an aria-live region

**Comment by cguardia** [comment]
Deployed to staging.

**Comment by paregorios** [comment]
Please merge to master and deploy to production.

**Comment by cguardia** [comment]
Merged to master.
