### ISSUE TITLE
Improve front-page slider accessibility by adding more control and navigation options: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#281]
Additional requirements levied via the Microassist Complex Interaction Plan, as follows. 

> The carousel needs a pause/play option and previous/next arrows to navigate. All of these will
be button elements to provide semantic meaning and consistent keyboard behavior.

See also items generated from first Microassist audit report (#230, #253, #254, and #262).

**Comment by paregorios** [comment]
The basic functionality requested here was provided when @cguardia switched our easyslider settings to use "navigation buttons" in #262. That gave us these nifty controls, which work as described above:

![screen shot 2018-12-05 at 3 11 30 pm](https://user-images.githubusercontent.com/263285/49544286-107ec780-f8a0-11e8-842c-3951c6f206d3.png)

Unfortunately, the left/right arrows and numbered slide buttons are not implemented with the HTML5 ```<button>``` element and therefore do not meet WCAG accessibility guidelines. The pause/play button **is** implemented with ```<button>``` and so needs no HTML intervention.

## What's needed:

 - Change the ```<span><a>``` construct used for the left/right arrows and numbered slide buttons to actually use ```<button>```
  - Style the left/right arrowheads so they are aligned top-to-bottom with the numerals in the buttons in-between 
  - Style the play/pause button so that it has the same look and feel as the left/right arrows and numeric buttons
   - Style the play/pause button so it is located immediately to the right of the central controls instead of at the right-hand end of the slider

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
I think there are still two of the four things mentioned in [my comment above](https://github.com/isawnyu/isaw.web/issues/281#issuecomment-444651833) that do not seem to have been fully addressed:

# Change the ```<span><a>``` construct used for the left/right arrows and numbered slide buttons to actually use ```<button>```

I still see this in the HTML:

```html
<span id="leftb"><a class="leftright" href="javascript:void(0);"><img id="prev-bt" src="++resource++prevII.gif" title="" alt="previous_picture_alt"></a></span>
```

# Style the play/pause button so that it has the same look and feel as the left/right arrows and numeric buttons

This does not seem to be the case on staging:

![screen shot 2019-01-16 at 10 04 08 am](https://user-images.githubusercontent.com/263285/51261573-1e7f3800-1976-11e9-8ac3-e2c5e10b46ba.png)

**Comment by paregorios** [comment]
That's got it! Thanks, please merge to master and deploy to production.

**Comment by paregorios** [comment]
Looks good on production.
