### ISSUE TITLE
Remove/replace Voyant Tools word cloud with something more accessible

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#287]
> Widgets that are created by third parties will have to be remediated by the third party. There is
not much NYU will be able to do personally to remediate the Voyant widget.
> 
> Iframe must have a non-empty title.
> 
> The Voyant tool is currently not accessible for keyboard only users, Voyant would need to make all the menu options available by programming them as buttons. While some of the menus are open, showing the list of menu items, the edge of the Voyant tools space is interfering with the full visual of the list. This is causing cognitive issues.
>
> There should be a text alternative for the Word Cloud that is an ordered list of the words ascending in most used word to least used word. This, in combination with hiding the Word Cloud from screen readers will allow screen reader users to access the same information without the issues of the voyant tool.

I believe that this only affects the publications page for ISAW Papers, where the widget was added by @sfsheath 

![screen shot 2018-06-06 at 1 27 05 pm](https://user-images.githubusercontent.com/263285/41057669-5c9362b8-698d-11e8-8a08-82ac0b26a8fb.png)

**Comment by sfsheath** [comment]
Happy to see it go.

**Comment by paregorios** [comment]
Closing. Embed was removed.
