### ISSUE TITLE
Apply "people listing" display view to collections: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#288]
Currently the "people listing" is only available on folders, but we would like it available on collections so that we can create custom groupings of profiles hosted elsewhere in the portal (e.g., alumni year cohorts and staff serving as adjunct faculty).

**Comment by jessesnyder** [comment]
@paregorios This is on staging: https://isaw.jazkarta.com/people/faculty/isaw-faculty/regular-faculty-tagged-as-such/

It currently depends on the collection criteria to limit the displayed items to Profile objects. If you'd like me to add another layer of type-checking in the code to avoid nasty surprises, that's not hard to do.

**Comment by jessesnyder** [comment]
Paranoid type check added. :)

**Comment by paregorios** [comment]
This works perfectly. Please merge to master and deploy to production.

**Comment by paregorios** [comment]
Looks good on production.
