### ISSUE TITLE
footer "news link" points to /news/RSS instead of /news/collector/RSS

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#29]
Only news items should appear in the RSS feed.

**Comment by paregorios** [comment]
is this still happening?

**Comment by paregorios** [comment]
blocked for further testing until we are sure that staging is running the same code as production

**Comment by paregorios** [comment]
Actually, this was still happening, but I was able to resolve that issue and uncover a new one! Here's the deal: 

/news/RSS is the RSS feed for the folder. It seems to include any and all content that is contained in the folder (not sure why there are images in here, but there are). But turning off syndication at the folder level gets rid of that problem.

/news/collector/RSS is the RSS feed for the collection that is set as the default content item. As the collection limits itself to only the kind of things we want to see, only the news items show up, and that selectivity is reflected in the feed. So that's all good.

Link-based discovery of RSS feeds at /news works fine because the template populates the header with ```link``` elements pointing to the various feed formats we've enabled on the collection:

```html
<link rel="alternate" href="http://isaw.nyu.edu/news/collector/atom.xml" title="ISAW News Blog - Atom" type="application/rss+xml" />
<link rel="alternate" href="http://isaw.nyu.edu/news/collector/rss.xml" title="ISAW News Blog - RSS 2.0" type="application/rss+xml" />
<link rel="alternate" href="http://isaw.nyu.edu/news/collector/RSS" title="ISAW News Blog - RSS 1.0" type="application/rss+xml" />
```

**The only problem we have remaining** is that the "News RSS" link in the footer points directly to /news/RSS instead of to /news/collector/RSS. I tried to change this via the "Site RSS" field in ```/@@syndication-settings```, but that doesn't seem to have made any difference. 

I could use some advice on how to resolve this. Retitling to reflect the current issue.

**Comment by paregorios** [comment]
Also, wierdly, /news/RSS seems to redirect to /news-old/RSS after I turned off syndication on /news

**Comment by skleinfeldt** [comment]
Is the News RSS link in the footer related to #40 the ticket about editing the footer? In other words it is a value manually set in portal_actions or some such? Or maybe even set in the theme? Sorry I don't know, but those are some places to check.

**Comment by paregorios** [comment]
* @skleinfeldt we don't imagine needing to edit and re-edit the link for the RSS in the footer, so we hadn't imagined it being a part of the #40 tasks. 
 * The footer "news RSS" link magically appeared when I turned on syndication via ```/@@syndication-settings``` (i.e., login -> site settings -> syndication).
 * I had assumed that the URL slug for it is based on the selection in the "Site RSS" widget on the ```/@@syndication-settings``` page, so changed it to point at /news/collector (it was /news before) yesterday, but it made no difference, even after restarting varnish. 
 * I don't know if there's a manual setting somewhere in portal_actions or in the theme, but I will check to the best of my ability.

**Comment by skleinfeldt** [comment]
Of course, that makes sense. I'm totally out of my league here, but wonder if you should check for an errant customization to document actions - /portal_actions/document_actions/rss/manage_propertiesForm. But I really don't know how this works anymore...

**Comment by paregorios** [comment]
fixed via portal actions
