### ISSUE TITLE
deploy to production: completed tickets for iteration 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#300]
It is my impression that the following tickets have been completed, tested on staging, and the associated code merged to "master":

 - #232 
 - #234 
 - #237 
 - #238 
 - #239 
 - #240 
 - #256 
 - #273 
 - #296 

Request these be deployed to production at earliest convenient time, if possible on Monday 8/20.

**Comment by skleinfeldt** [comment]
Go for it @alecpm - if possible please deploy tonight.

**Comment by alecpm** [comment]
Master has been tagged as release `2.55` and deployed to production. Upgrade steps for `isaw.policy` have been run as well.

**Comment by paregorios** [comment]
Thanks! I'll look over everything today.

**Comment by paregorios** [comment]
I have looked over all of the associated tickets and moved all the ones that are complete and deployed to "done" status. I found a bug in the lead image ticket (#296), and have marked it accordingly and moved it back to "doing" in the iteration project board.
