### ISSUE TITLE
event listing does not construct alt attributes for lead images: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#301]
The same logic used to construct alt and title attributes for lead images needs to be applied to lead images that appear in the event listing. Right now we get no "alt" attributes, even when the underlying lead image object has the necessary information. Consider, for example:

https://isaw.nyu.edu/events/archive/2017

look for "Eleventh Annual Leon Levy Lecture" 

examine the associated lead image:

```html
<img src="https://isaw.nyu.edu/events/archive/2017/leon-levy-lecture-2017/leadImage_mini" title="">
```

but if you visit [the event item itself](https://isaw.nyu.edu/events/archive/2017/leon-levy-lecture-2017), you find:

```html
<img src="https://isaw.nyu.edu/events/archive/2017/leon-levy-lecture-2017/leadImage_mini" alt="Photograph of Mary Beard" title="" class="newsImage" width="200" height="160">
```

Marked high priority because this bug is blocking publication of the AY2018 events archive, which contains all the events from last year and there is currently no public browse path to them.

**Comment by paregorios** [comment]
Note: never use title attribute on img tags. See latest comments on #259 and #296

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
This looks good. Please deploy.
