### ISSUE TITLE
find out where SSO/PAS plugin work stands: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#302]

**Comment by paregorios** [comment]
Blocker for #299

**Comment by jessesnyder** [comment]
@paregorios I don't seem to have the URL of the NYU SSO IdP. Will there be a new one specifically for staging/testing as an outcome of your pending interactions with Yavor?

**Comment by paregorios** [comment]
@jessesnyder Last time we did this there was a “QA IdP” they had us use (with a test netid and password) for testing. We had to provide them with a URL from which to harvest our (dev) instance’s “metadata,” which they ingested into the QA IdP. I’ve been digging through old emails but haven’t found it yet. In any case, I need to get them to respond to go through the metadata handshake and also to reactivate the test netid. Hopefully I’ll get a response soon.

Are you blocked now without this information?

**Comment by jessesnyder** [comment]
@paregorios Not entirely. It just means I can't get the authentication set up on my local machine to verify that all the parts are working. I don't remember if my declared Service Provider location needs to be the URL of the actual server. For now I just pretended to be the staging server, so the metadata winds up looking like:
```
<ns1:EntityDescriptor xmlns:ns1="urn:oasis:names:tc:SAML:2.0:metadata" ID="_0fb33fb6-2efc-4246-bda2-ef12c1c681c2" entityID="ISAW-saml2-entity-id" validUntil="2018-09-01T19:23:34.177354Z">
<ns1:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<ns1:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://isaw.jazkarta.com/isaw/acl_users/saml2sp/post" index="1" isDefault="true"/>
<ns1:AttributeConsumingService index="0" isDefault="false">
<ns1:ServiceName xml:lang="en">SAML2 Attribute Consuming Service</ns1:ServiceName>
<ns1:ServiceDescription xml:lang="en">
Controls which attributes from the Identity Provider response will be extracted by the plugin for use when finding a corresponding Plone member.
</ns1:ServiceDescription>
<ns1:RequestedAttribute FriendlyName="sn" Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="false"/>
<ns1:RequestedAttribute FriendlyName="givenName" Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="false"/>
<ns1:RequestedAttribute FriendlyName="eduPersonPrincipalName" Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="false"/>
</ns1:AttributeConsumingService>
</ns1:SPSSODescriptor>
</ns1:EntityDescriptor>
```

**Comment by paregorios** [comment]
In the absence of guidance from NYU IDM, that seems like the best course. Given the time in NYC, it's pretty clear we've been pigeonholed till after Labor Day. I'll start escalating my efforts on Tuesday, so hopefully by next iteration I'll have the loop closed with them.

**Comment by paregorios** [comment]
Jesse:

Last time we did this there was a “QA IdP” they had us use (with a test netid and password) for testing. We had to provide them with a URL from which to harvest our (dev) instance’s “metadata,” which they ingested into the QA IdP. I’ve been digging through old emails but haven’t found it yet. In any case, I need to get them to respond to go through the metadata handshake and also to reactivate the test netid. Hopefully I’ll get a response soon.

Are you blocked now without this information?


Tom Elliott, Ph.D.
Associate Director for Digital Programs
Senior Research Scholar
Institute for the Study of the Ancient World
New York University
tom.elliott@nyu.edu

http://isaw.nyu.edu/people/staff/tom-elliott
pronouns: he, him
OrcId: http://orcid.org/0000-0002-4114-6677

**Comment by skleinfeldt** [comment]
@jessesnyder see above, and if possible can you update us on where you're at?

@paregorios Jesse is on vacation in Maine this week, so might not respond until next week.

**Comment by paregorios** [comment]
@skleinfeldt thanks. I thought I'd sent this email last week, but it looks like it was hiding in a window behind my email client until earlier today when I found it and kicked it through. Apologies to @jessesnyder for the delay; no need to address until returned from vacation, especially since I still have no traction with the Identity Services team at NYU.

**Comment by paregorios** [comment]
@jessesnyder see now Yavor's response to the concerns I laid out above:

https://github.com/isawnyu/isaw.web/issues/303#issuecomment-419181431

**Comment by paregorios** [comment]
@jessesnyder should this ticket now be closed?

**Comment by jessesnyder** [comment]
@paregorios Yes, I don't see why not.
