### ISSUE TITLE
event listing "more" button produces "bar" dialogue

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#305]
This appears to be new behavior on production following the most recent deployment.

Steps to recreate:

 - Visit events -> past events -> [academic year 2016-2017](https://isaw.nyu.edu/events/archive/2016)
 - Scroll to bottom of page
 - Select the "view more" button
 - Scroll to the bottom of the page after additional items are loaded
 - Select the "view more" button again
 - See an unexpected dialog box with content "bar" and an "OK" button (see screen capture below)

Expected behavior is to load additional events until there are no more available and then the "view more" button should be disabled or not shown.

![screen shot 2018-09-05 at 11 25 39 am](https://user-images.githubusercontent.com/263285/45107466-4b395e00-b0ff-11e8-93e4-7beac6fc3974.png)

**Comment by alecpm** [comment]
@cguardia !!

**Comment by cguardia** [comment]
This doesn't happen locally, but I removed the alert. If we get there somehow, the button is now hidden.

**Comment by paregorios** [comment]
This is fixed on production.
