### ISSUE TITLE
improve usability of "add/edit image" dialog: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#307]
When using the editor on a rich text field, one inserts or edits images by clicking on the "Insert/Edit Image" icon on the editor toolbar:

![screen shot 2018-09-05 at 2 37 02 pm](https://user-images.githubusercontent.com/263285/45116831-89437b80-b119-11e8-9b18-1d151fec4cba.png)

There are several behavior and layout problems with the "Insert/Edit Image Dialog Box" that make it hard to use (see screen captures, below):

 - [x] Some text fields are too wide for the details pane, causing the rest of the fields to scroll off to the left.
 - [x] There is an OK button that overlays the details pane, obscuring the final fields in the pane, even when one scrolls all the way to the bottom.
 - [x] There is a "Link Title" field in the details pane that does not seem to be used at all.

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
Moving to "review" column in project iteration 3

**Comment by paregorios** [comment]
Much better, thanks. Please merge to master and deploy.

**Comment by paregorios** [comment]
This is working on production
