### ISSUE TITLE
why do we have two "collection" types in the "add" action menu?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#31]
Unclear what the difference is or why we need both. Not distinguishable for users from the menu. Can we not consolidate and eliminate one of them?

**Comment by skleinfeldt** [comment]
I assume this would be "old style" and "new style" collections which were introduced in Plone 4.2. This page explains how to enable/disable either type: https://plone.org/documentation/manual/upgrade-guide/version/plone_4_2_upgrade_notes/upgrading-to-new-collections

I'm guessing that you've been using old style collections all along and decided when you upgraded to 4.2 to disable the new style ones? And that the 4.3 upgrade automatically enabled the new style ones? 

In any case, I suggest you give both types a whirl and decide which one you want to use. (New style ones are simpler, but not as flexible.) Then disable the one you don't want.

@alecpm let me know if I'm off base with any of this.

**Comment by paregorios** [comment]
I'm taking this to disable old-style collections if they are not already so disabled.

**Comment by paregorios** [comment]
What is the appropriate/best method to disable one of these?

**Comment by paregorios** [comment]
@skleinfeldt if I follow the ZMI method recommended above to disable "old style" collections (which don't show up the way it says they will), will they remain disabled across buildout runs, or is there something in our buildout code that "forces" them to be enabled?

**Comment by skleinfeldt** [comment]
I'm afraid I don't know - @alecpm can you answer Tom's question?

**Comment by alecpm** [comment]
A buildout run will definitely not re-enable old collections disabled via the ZMI.  It's possible that running an upgrade step via the control panel that includes types tool configuration would reset that, but I don't think that's the case for ISAW.

**Comment by alecpm** [comment]
It turns out that isaw.policy did set the global allow flag on Topics to true, so an upgrade step could have re-enabled them in the future.  I've removed that setting in the latest commit though.

**Comment by paregorios** [comment]
Thanks. So, I should go ahead and disable via the ZMI?

**Comment by alecpm** [comment]
Yup!

**Comment by paregorios** [comment]
On both production and staging, /portal_types/Topic has been set implicitly_addable=False.

Thanks all for the help.
