### ISSUE TITLE
Include "Full Name" field in user creation: 2

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#310]
When I create a new user account in the ISAW web site, I can't give the account a "Full Name" because the field doesn't appear on the creation page. I have to finish creating the user, and then go back to find it in the list, and edit the existing account in order to add a name. It would save time to have this field available in the creation page.

**Comment by jessesnyder** [comment]
@k2soule https://isaw.jazkarta.com/@@new-user

**Comment by k2soule** [comment]
@jessesnyder : the new "Full Name" field looks to be right where I need it - great! I can't test creation of a new user there on staging, though. Error 503 "Backend fetch failed"

**Comment by k2soule** [comment]
Looks good on production - closing ticket.
