### ISSUE TITLE
Steps toward running SAML2 on staging: 8

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#315]
Tasks:
 - [x] get isaw.policy test suite running
 - [x] setup handlers for installing, but not activating, PAS plugin, SAML Authority, Service Provider, etc.
 - [x] Create cert.der and cert.pem files based on data in shibboleth_metadata.xml
 - [x] metadata to NYU identity management

**Comment by jessesnyder** [comment]
@paregorios The URL I have to initiate a _logging out_ at NYU (for the staging environment) is:
'https://shibbolethqa.es.its.nyu.edu/idp/profile/Logout'

Wondering:
1. If this is still correct
2. If there will be a different URL for production

**Comment by paregorios** [comment]
response from IDM:

> The Prod Logout URL is https://shibboleth.nyu.edu/idp/profile/Logout

**Comment by jessesnyder** [comment]
@paregorios The issue we want in this project/iteration is actually this one: https://github.com/isawnyu/isaw.web/issues/328

This ticket (315) is considered "Done".

**Comment by skleinfeldt** [comment]
@paregorios @jessesnyder I believe we decided that this story's 8 points should go into iteration 3 since the work was completed them. I am moving it and recalculating total points.

**Comment by skleinfeldt** [comment]
Ah I see @paregorios you added it to iteration 3 but forgot to remove it from iteration 4. Done.
