### ISSUE TITLE
Implement SAML2 on production via Ansible: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#318]
*Governing Epic: #299 (SSO: PAS Plugin)*
*Blocked by #356*

**Comment by alecpm** [comment]
The SAML related changes to the Ansible buildout are now set to apply to production as they do on staging. We'll need the production SAML2 key files to be encrypted using ansible vault and placed in `keys/isaw-production.pem` and `keys/isaw-production.der`, once we have them.

**Comment by paregorios** [comment]
@jessesnyder @skleinfeldt I'll try to catch y'all on IRC to discuss how, whether, and when we could deploy this on production in conjunction with running #356

**Comment by paregorios** [comment]
NYU IDM reports "The New ISAW instance has been added to QA IdP. You can test it."

My test failed with "SAML request failed". Steps to replicate:

 - visit the new server instance
 - select the "LOGIN" link in the footer
 - watch the redirect occur, and then a redirect back to the home page with no obvious login having occurred
 - navigate to another page where one sees "SAML request failed"

**Comment by alecpm** [comment]
The logs show:

```
ERROR dm.zope.saml2.role failed SAML2 request:
<?xml version="1.0" ?>
<ns1:Response Destination="https://isaw-new.jazkarta.com/isaw/acl_users/saml2sp/post" ID="_dc1cbde1b7f6dca0caf084e2495f984e" InResponseTo="_4c56b486-7aa7-44f5-8f9f-225226e9b0fe" IssueInstant="2019-08-16T18:00:26.908Z" Version="2.0" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns3="http://www.w3.org/2000/09/xmldsig#">
  <ns2:Issuer>https://shibbolethqa.es.its.nyu.edu/idp/shibboleth</ns2:Issuer>
  <ns3:Signature>
    <ns3:SignedInfo>
      <ns3:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ns3:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <ns3:Reference URI="#_dc1cbde1b7f6dca0caf084e2495f984e"><ns3:Transforms>
      <ns3:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <ns3:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ns3:Transforms>
      <ns3:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
      <ns3:DigestValue>ZnONyCW3b/lnH2/yCzQ1Zs4jzP0=</ns3:DigestValue></ns3:Reference>
    </ns3:SignedInfo>
    <ns3:SignatureValue>...</ns3:SignatureValue>
    <ns3:KeyInfo>
      <ns3:X509Data>
        <ns3:X509Certificate>...</ns3:X509Certificate>
      </ns3:X509Data>
    </ns3:KeyInfo>
  </ns3:Signature>
  <ns1:Status>
    <ns1:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/>
    <ns1:StatusMessage>An error occurred.</ns1:StatusMessage>
  </ns1:Status>
</ns1:Response>

**Comment by alecpm** [comment]
Maybe @jessesnyder has a clue what might be happening here?

**Comment by paregorios** [comment]
NYU IDM asked me "try again" this morning, so I did. Now we have a new error:

Steps to replicate:

 - Visit new production
 - Select the "LOG IN" link in the footer
 - See redirect occur and then see the QA shibboleth login page
 - Enter the test credentials and select the "log in" link
 - Page refreshes and displays (firefox) the following notice:

> The page isn’t redirecting properly.
> An error occurred during a connection to isaw-new.jazkarta.com. 
>  - This problem can sometimes be caused by disabling or refusing to accept cookies.

In the location bar one sees the following URL:

```
https://isaw-new.jazkarta.com/acl_users/saml2sp/authenticate?fail=https%3A//isaw-new.jazkarta.com/acl_users/saml2sp/%40%40saml_failure&ok=https%3A//isaw-new.jazkarta.com/loggedin%3F&idp=https%3A//shibbolethqa.es.its.nyu.edu/idp/shibboleth
```

Selecting the "try again" button just displays the same error.

Safari has a similar behavior but I note the following additional information in the error message:

> Too many redirects occurred ...

With chrome, one reads:

> isaw-new.jazkarta.com redirected you too many times.

**Comment by alecpm** [comment]
I hadn't set the sharing permissions on the `/loggedin` page properly. It's fixed now, and @jessesnyder will be adding that to the install steps I believe.
