### ISSUE TITLE
open graph author property has invalid contents

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#32]
For example, the Facebook Open Graph Object Debugger reports the following "Error that must be fixed" for http://isaw.nyu.edu/visiting-scholar-program/frequently-asked-questions : 

    More Than One OG URL Specified
    Object at URL 'http://isaw.nyu.edu/visiting-scholar-program/frequently-asked-questions' of type 'article' is invalid because it specifies multiple 'og:url' values: http://isaw.nyu.edu/visiting-scholar-program/frequently-asked-questions, http://isaw.nyu.edu/visiting-scholar-program/frequently-asked-questions.

Search for "og:" in https://developers.facebook.com/tools/debug/og/echo?q=http%3A%2F%2Fisaw.nyu.edu%2Fvisiting-scholar-program%2Ffrequently-asked-questions

**Comment by paregorios** [comment]
News items also throw this error, e.g. https://developers.facebook.com/tools/debug/og/echo?q=http%3A%2F%2Fisaw.nyu.edu%2Fnews%2Fisaw-featured-in-nyu-alumni-magazine

**Comment by paregorios** [comment]
see if this still is going on

**Comment by paregorios** [comment]
The Facebook Open Graph Object Debugger is no longer reporting the duplication errors, so evidently they are no longer with us; however, it is reporting that the object is rendered invalid because we are inserting the Plone username of the Creator in the article:author property when Facebook expects a "profile" (i.e., a Facebook account profile). Here's the actual error message from an example:

> Object at URL 'http://isaw.nyu.edu/visiting-scholars/visiting-research-scholars-program' of type 'article' is invalid because the given value 'admin' for property 'article:author' could not be parsed as type 'profile'.

I will retitle this ticket to reflect this particular error.

**Comment by alecpm** [comment]
This fix is live on staging.

**Comment by paregorios** [comment]
This is working. @alecpm please deploy to staging at your leisure.

**Comment by alecpm** [comment]
This is now merged to master and will be deployed with the next tag update.

**Comment by alecpm** [comment]
This is merged and deployed
