### ISSUE TITLE
lead image placement on events covers title and does weird things to text

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#322]
So, this leaves a fair bit to be desired:

![screen shot 2018-09-12 at 10 41 05 am](https://user-images.githubusercontent.com/263285/45436505-919b3980-b678-11e8-84f4-7fbfd1d9ee6c.png)

A css rule addition as simple as the following **might** fix it:

```css
div.newsImageContainer {
    top: 1em;
}
```

thus:

![screen shot 2018-09-12 at 10 47 40 am](https://user-images.githubusercontent.com/263285/45436850-55b4a400-b679-11e8-83f2-b94c8507fe54.png)

**Comment by alecpm** [comment]
This should be addressed on staging with the fix for #219.

**Comment by paregorios** [comment]
The fix on staging has taken care of obscuring the title, which now wraps correctly; however, the image floats all the way to the bottom of the header:

![screen shot 2018-09-13 at 1 35 27 pm](https://user-images.githubusercontent.com/263285/45508259-fda19e80-b759-11e8-86cc-7fe93c407f8a.png)

This seems to be due to a CSS rule on ```.section-events #content div.newsImageContainer```:

```css
margin: -55px 10px 5px 10px;
```

If the first value (for top margin) is changed to "0px" it looks like we'll get something more visually appealing:

![screen shot 2018-09-13 at 1 43 55 pm](https://user-images.githubusercontent.com/263285/45508703-1a8aa180-b75b-11e8-86bb-4d6eecf64292.png)

This seems to be OK when authenticated too:

![screen shot 2018-09-13 at 1 45 56 pm](https://user-images.githubusercontent.com/263285/45508814-735a3a00-b75b-11e8-9d1a-be543e3c12c3.png)

**Comment by paregorios** [comment]
Now that I look back over this, getting rid of the right-hand margin on ```div.newsImageContainer``` might be nice too, so that the right-hand side of the image better lines up with the wrap-line for the text below and doesn't trap so much whitespace between the even content and the portlet.

**Comment by alecpm** [comment]
I believe that was the original intent of the design hence the original `-118px` top positioning. As you indicate, it's pretty trivial to make it flush with the title if that's preferred.

**Comment by alecpm** [comment]
See e.g. http://isaw.nyu.edu/events/archive/2017/the-prehistory-of-crete as a non-logged in user. I think it looks a bit funny, but also quite intentional.

**Comment by paregorios** [comment]
I suspect cruft from all the header re-re-redesign we went through and we missed it because it only shows up on events. In any case, it must be consigned to the dustbin of history ...

**Comment by alecpm** [comment]
OK, margins are removed.

**Comment by paregorios** [comment]
Brilliant! Please merge to master and deploy.

**Comment by paregorios** [comment]
this is working on production
