### ISSUE TITLE
old isaw-event types persist on add menu

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#33]
This behavior occurs on both production and dev at present. When an authenticated user with the correct permissions clicks on "add new" the menu of types includes not only the stock plone "Event" but also the deprecated custom event types: "Conference Event", "Exhibition Event", "General Event", "Lecture Event", "Performance Event", "Seminar Event", and "Sponsored Event".

There are a series of stories in scrumdo, related to the issue of getting rid of the old custom package and migrating content etc. They are all marked "done" and I was under the impression that we had once and for all migrated at the time of the site upgrade. 

How do we get rid of these menu options, the associated type definitions, etc. (and make sure that no new items have been accidentally created by our users since the last migration)?

![add-new-events](https://cloud.githubusercontent.com/assets/263285/7779954/01672726-009f-11e5-9839-eb1c101b426f.jpg)

**Comment by paregorios** [comment]
Not sure who to assign this to either @skleinfeldt

**Comment by skleinfeldt** [comment]
@paregorios I think this is now fixed?

**Comment by paregorios** [comment]
Yes, sorry I thought I'd closed this. Doing so now.
