### ISSUE TITLE
Eliminate page-title/section-title markup at end of header: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#333]
It appears that there is some old design cruft hanging around in our header causing accessibility issues related to heading hierarchy and empty tags. Specifically, something is trying to create a ```<div class="page-title">``` and putting an ```<h2 class="section-title">``` inside it. 

Sometimes, the ```<h2>``` has content, [for example on a profile page](view-source:http://isaw.nyu.edu/people/faculty/isaw-faculty/lorenzo-dalfonso), where we see:

```html
<div class="page-title">
    <h2 class="section-title">People</h2>
</div>
```
Elsewhere, the ```<h2>``` can be empty, e.g., [on the events page](http://isaw.nyu.edu/events):

```html
<div class="page-title">
    <h2 class="section-title"></h2>
</div>
```

We need to rip this out everywhere on the site. Get rid of ```<div class="page-title">``` and any/all markup or text content inside it.

**Comment by alecpm** [comment]
This is deployed to staging

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.
