### ISSUE TITLE
always wrap context title in h1 unless on home page: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#334]
Across the site, the title of a content item usually appears an ```<h1>``` element thus:

```html
<h1 id="parent-fieldname-title" class="documentFirstHeading">
    Community Guide
</h1>
```

This is good. But there are few templates that don't work this way and we need to fix them. Details:

## News (```/news```)

The "Tiled Listing" used for the news page does not display a large title like we do on many other pages. This is by design; however, we need to provide a page title in ```<h1>```, drawn from the context title for screen readers etc. but hide it visually using CSS. Note that the "Tiled Listing" is used elsewhere on the site, for example in the top page of the "events archive," so we can't just hard-code something like ```<h1>News</h1>``` into the template.

## Events (```/events```)

A similar situation obtains with the "Event Listing", which is used not only on the main "events" page, but also in the subfolders that make up the "Events Archive" (http://isaw.nyu.edu/events/archive). A solution such as that described for "news" (above) is desired.

**Comment by cguardia** [comment]
Added screen reader only class and used it for h1 elements in tiled and event listing views.

**Comment by paregorios** [comment]
I am seeing the content of ```h1.screen-reader-only``` in regular, visual browsers (e.g., Firefox, Safari) even after hard refresh. Our goal for these browsers, as laid out above, was no change in look and feel from production. @cguardia please advise

![screen shot 2018-10-29 at 9 10 13 am](https://user-images.githubusercontent.com/263285/47655267-a5ccc480-db5a-11e8-965d-d5da070ddc82.png)

![screen shot 2018-10-29 at 9 11 59 am](https://user-images.githubusercontent.com/263285/47655298-b67d3a80-db5a-11e8-876c-db31bf9b92c5.png)

**Comment by cguardia** [comment]
I was using chrome and it doesn't show up there. I can see it on firefox, though. The css might need some tweaking. Will try again.

**Comment by cguardia** [comment]
Weird, the new css class shows up in chrome, but it's like it doesn't exist in firefox. Looking at it.

**Comment by cguardia** [comment]
The hard reset didn't do it for me either. I restarted the cache and seems like the new css is being pulled in at last. Please test.

**Comment by paregorios** [comment]
Thanks @cguardia that looks good from here too. Please merge to master and deploy to production.
