### ISSUE TITLE
search doesn't work on dev

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#34]
Navigated to /search and entered various things that ought to be searchable text into the form. No luck. Also seemed to go away and not come back (i.e., when entering something new after getting 0 results, would get a "you already clicked submit, do you really want to click submit again" message.

**Comment by skleinfeldt** [comment]
Maybe because we haven't themed search yet? That's a story for next week.

**Comment by paregorios** [comment]
that would indeed explain it :)

**Comment by alecpm** [comment]
Is this still an issue?

**Comment by paregorios** [comment]
No, this works!
