### ISSUE TITLE
provide "alt" text for "Publication Object" thumbnail images: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#340]
In addition to the "lead image" on "Publication Objects" there are 0-n thumbnail images created on the basis of content items that have been placed inside the folderish "Publication Object" itself. Each of these thumbnails needs an ```alt``` attribute with appropriate content. In the absence of a better solution, which would require a fair bit of design and would deserve UX testing, I think we should just pick up the DC.description field from these content items and use that for the thumbnail ```alt``` attribute values.

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.
