### ISSUE TITLE
update/replace SSL certificate for isaw4: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#341]
Our current certificate expires October 3, 2018. We need to replace it manually on production.

**Comment by alecpm** [comment]
An auto-renewing Let's Encrypt certificate for isaw.nyu.edu and www.isaw.nyu.edu has bee manually created and installed on the production server. It is currently valid until Dec 24, 2018, but it should auto-renew before then.

**Comment by paregorios** [comment]
Works great, thanks!
