### ISSUE TITLE
add aria role="search" to site search form: 0.5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#343]
In the guidance that got incorporated into #236, Microassist incorrectly specified that the search form should have either role="form" or HTML5 ```<form>```, which actually makes no sense. [What the WAI Aria guidelines say](https://www.w3.org/TR/wai-aria/#search) is that that search forms should have ```role="search"```. 

So, please add ```role="search"``` site-wide to ```<form name="searchform" aria-label="site search" ```

**Comment by cguardia** [comment]
Deployed to staging.

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by cguardia** [comment]
Merged to master.
