### ISSUE TITLE
All breadcrumbs lead to Rome- I mean, home: 1

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#344]
I noticed yesterday that all of the breadcrumb links in the header are taking me back to the main home page. Is there a missing close tag causing the whole breadcrumb line to be linked to the top level?

**Comment by skleinfeldt** [comment]
@k2soule @paregorios can this wait until our iteration Monday or is it a drop-everything-do-it-now issue?

**Comment by paregorios** [comment]
Wait till Monday

**Comment by skleinfeldt** [comment]
That's good :-) 

I put this in the Iteration 5 ToDo column.

**Comment by jessesnyder** [comment]
(Went for the simplest option... now on staging.)

**Comment by paregorios** [comment]
@jessesnyder I'm not seeing it on staging. Does Varnish need a restart?

**Comment by jessesnyder** [comment]
Hard refresh was enough for me, but I'll restart varnish.

**Comment by paregorios** [comment]
@jessesnyder thanks! Confirm this is working. Please merge to master and queue for deployment to production.

**Comment by paregorios** [comment]
After restarting varnish on production I was able to verify that this fix was deployed.
