### ISSUE TITLE
horizontal scrollbar on front-page slider

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#347]
Recent changes to the slider seem to have caused a change that's producing a horizontal scrollbar under the front-page slider on production. I detect this in both Firefox and Chrome, but not Safari.

![screen shot 2018-10-30 at 2 24 52 pm](https://user-images.githubusercontent.com/263285/47744575-9ed3ae00-dc4f-11e8-92a2-985eb47a478b.png)

**Comment by skleinfeldt** [comment]
@jessesnyder could you take a look?

**Comment by jessesnyder** [comment]
Working on it...

**Comment by jessesnyder** [comment]
@paregorios @k2soule Fixed on staging I think? 🙏

**Comment by jessesnyder** [comment]
@alecpm This is merged to master... could use help with deployment.

**Comment by alecpm** [comment]
This should be deployed now.

**Comment by paregorios** [comment]
yes, this is fixed on production
