### ISSUE TITLE
Unable to link to exhibition objects

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#349]
Exhibition objects do not show up as linkable in the TinyMCE toolbar. 

Steps to reproduce: 

Steps to reproduce with an exhibition object:

1. Log into production
2. Navigate to an unobtrusive context.
3. Create [a folder entitled "Test 20181102"](https://isaw.nyu.edu/members/te20-40nyu.edu/test_20181102/)
4. Inside "Test 20181102", create a page entitled "Test Page" and put some arbitrary text in the Body Text field. Save. 
5. Inside "Test 20181102", create an exhibition object entitiled "Test Exhibition Object". Save.
6. Inside "Test 20181102", create and upload an image entitled "Test Image". Save.
7. Edit "Test Page." 
   - Select some of the text in the body field.
   - Select the "Insert/Edit link icon in the TinyMCE toolbar"
   - Notice that "Test Page" and "Test Image" are available in the default context, but not "Test Exhibition Object."
   - Cancel your edit.
8. Submit "Test Exhibition Object" for publication review.
9. Repeat step 7. Notice there is no change. Cancel your edit.
10. Publish "Test Exhibition Object".
11. Repeat step 7. Notice there is no change. Cancel your edit.

I wonder if this is the problem: https://stackoverflow.com/questions/22799301/new-dexterity-content-type-is-not-visible-from-the-add-link-dialogue

**Comment by alecpm** [comment]
I think this must have been reset when we reinstalled TinyMCE. The types that can be used as Images, Links, etc. Can be set here:

http://isaw.nyu.edu/portal_tinymce/@@tinymce-controlpanel

Under the resources tab.

**Comment by jessesnyder** [comment]
Yep.. all set.

**Comment by jessesnyder** [comment]
@paregorios It looks like the following content types are no longer in use. Confirm/deny?

"Seminar"
"Lecture"
"General"
"Sponsored"
"Performance"
"Conference"

**Comment by paregorios** [comment]
@jessesnyder yes, that's correct (unless there are some very old ones lurking under /events/archive, but it's my recollection that we migrated everything to plone events).

**Comment by paregorios** [comment]
Confirmed this is fixed.
