### ISSUE TITLE
Error loading mini calendar portlet

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#350]
I'm observing an oddity in the Events section, when navigating using the mini calendar portlet; after a few clicks, I get this mess (screen shot attached). So far, I have only been able to reproduce the glitch in Chrome, and while logged in. Tried on two different computers (both macs)

**Comment by k2soule** [comment]
<img width="1280" alt="screen shot 2018-11-13 at 3 27 41 pm" src="https://user-images.githubusercontent.com/7882896/48441372-5345f780-e759-11e8-88d2-60143bcf963a.png">

**Comment by paregorios** [comment]
@k2soule have you seen this reoccur?

**Comment by paregorios** [comment]
@k2soule I'm inclined to close this ticket unless you've seen the problem crop up more recently. OK?

**Comment by k2soule** [comment]
Agreed. I have not been able to reproduce this error recently. Closing ticket.
