### ISSUE TITLE
adjust news listing style to better cohere with other listings and new link styles: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#355]
**This ticket is blocked until #351 is complete.**

Currently, the news listing looks like this:

![screen shot 2018-12-05 at 2 31 20 pm](https://user-images.githubusercontent.com/263285/49542857-4457ee00-f89c-11e8-8c87-65560796b376.png)

We would like style adjustments to make the following changes:

![screen shot 2018-12-05 at 2 44 01 pm](https://user-images.githubusercontent.com/263285/49543056-c9430780-f89c-11e8-91a8-fcef97665a9d.png)

Specific steps:

 - Make lead image for each article have a border that behaves just as specified in #354.
 - Article heading adjustments:
    - reduce size to 22px
    - remove text-transform
    - make color same as that used elsewhere for headings and links (reddish-brick color)
    - make link event behaviors (:focus:, :hover:, :active:) match those implemented elsewhere on the site per #353 
  - byline adjustments
     - remove text-transform
     - make text color same as the summary below
     - add font-style: italic

**Comment by paregorios** [comment]
Almost there. Link events for the headlines and article lead images need a little more tweaking to make them work exactly as specified elsewhere via #353 and #354.

I think the following specific changes are needed:

 - Image: 
   - default/visited: 3px solid red brick outline
   - hover/focus: 3 px dashed blue underline
- Headine:
   - hover/focus: dashed underline (right now it's solid)
   - active: text color orange, no underline

**Comment by cguardia** [comment]
I see the dashed underline. Maybe you need a hard refresh?

**Comment by paregorios** [comment]
I have tried hard restart, purge history, and restart browser on both Firefox and Chrome, but still see solid blue underline. Safari shows me dashed underline.

**Comment by cguardia** [comment]
@paregorios I can't replicate the issue. I restarted varnish and haproxy in the hope that this is a caching problem on the server. @alecpm or @jessesnyder, do you see the dashed line in the images and links for news items when you hover over them?

**Comment by alecpm** [comment]
In FF on a Mac I see a dashed blue border around all but the right side of the image and also under the heading text. To fix the issue with the border being cut off on the right, I think we should add `box-sizing: border-box;` to `#content a img`

**Comment by paregorios** [comment]
This looks good to me. Please merge to master and deploy to production.

**Comment by paregorios** [comment]
Looks good on production.
