### ISSUE TITLE
improve accessibility of breadcrumbs focus indication

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#358]
As suggested by @alecpm:

> add padding: 5px; border: 3px solid transparent; and on hover/focus border-color: blue; with a reduction in right margin from 14px to 8px

Do this for all linked breadcrumbs site-wide, regardless of their background color. 

We should suppress text decoration (underlin) on the the links.

It may be necessary to change the text color and background colors on hover/focus in order to get sufficient contrast. If so, blue for the text color and seashell for the background color would probably work.

**Comment by paregorios** [comment]
blocker for #251

**Comment by alecpm** [comment]
This is up on staging.
