### ISSUE TITLE
fix footer to correct bad page heading hierarchy: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#361]
We've done a lot of work to clean up skipped heading levels and related problems in our templates, but the footer still needs some attention. Specifically, there are three bits of text that are currently wrapped in ```<h3>``` tags (the "support" link and the "gallery hours" and "library hours" headings). These three components need to be wrapped in ```<h2>``` instead. That's easy for us to do via the "ISAW Settings" control panel -> "footer HTML" editor, but some CSS modifications are required in order to preserve current look and feel.

There are currently two relevant CSS selectors:

 - ```.footer-row #portal-footer h3``` 
 - ```.footer-row #portal-footer h3.support a```

Why not duplicate each of these for h2 to read as follows and see if that takes care of the need:

 - ```.footer-row #portal-footer h2``` 
 - ```.footer-row #portal-footer h2.support a```

We don't anticipate using ```<h3>``` in the footer going forward.

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.
