### ISSUE TITLE
ISAW home page has two <h1> elements: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#362]
There should only be one. Right now we find:

```html
<h1 id="site-title">Institute for the Study of the Ancient World</h1>
```

and 

```html
<h1 id="parent-fieldname-title" class="documentFirstHeading">
    Institute for the Study of the Ancient World
</h1>
```

This redundancy appears to be an unexpected by product of what I asked for (and got) with #326. 

Let's correct this redundancy on the home page only by changing

```html
<h1 id="site-title">Institute for the Study of the Ancient World</h1>
```

to 

```html
<div id="site-title">Institute for the Study of the Ancient World</div>
```

and making sure that look and feel does not change.

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.
