### ISSUE TITLE
fix home page slider headings for hierarchy: 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#363]
We've done a lot of work to clean up skipped heading levels and related problems in our templates, and with #361 we will wrap up the site-wide work in this area by fixing our footer.

The home page has an additional problem. Specifically, we are in the habit of using ```<h3>``` for headings on the slider overlay text. This breaks hierarchy, and we should switch to always using ```<h2>```. That switch is easily accomplished using the through-the-web editor for the overlay text panes (via "slider settings"), but some CSS modifications are required in order to preserve current look and feel.

There is currently this CSS selector:

```css
#content #slider .slide .slideroverlay h3
```

Why not just add one just like it for  ```<h2>```?

We don't anticipate using ```<h3>``` in the slide overlays going forward.

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.
