### ISSUE TITLE
Staging site: 503 “Backend fetch failed” on certain post requests

### ISSUE THREAD

**Issue by jessesnyder** [isawnyu/isaw.web#367]
To recreate:
1. log in as admin
2. from Site Setup -> Users and Groups, attempt to add a new user

**Comment by alecpm** [comment]
I cleaned up the obsolete and insane code in the `isaw.register` custom user add view, but that doesn't appear to have fixed the issue. I've also adjusted timeouts and other settings in the varnish and haproxy configs, but that simply delayed the eventual timeout. I think we'll need to make use of the deadlock debugger to figure this one out.

**Comment by alecpm** [comment]
My guess is that it has some relation to the SAML2 changes.

**Comment by alecpm** [comment]
The only relevant looking errors are::

    2019-01-18T15:48:14 WARNING plone.app.controlpanel Skipped user without principal object: sauvage.caroline@mom.fr
    ------
    2019-01-18T15:48:14 WARNING plone.app.controlpanel Skipped user without principal object: cww6

**Comment by k2soule** [comment]
I can tell you that neither of those users is currently needed in the system - long gone, in fact - so I wouldn't be opposed to deleting whatever remnants of their accounts may be gumming up the plone.

**Comment by alecpm** [comment]
Unfortunately, it's not at all clear where those broken user records are coming from, they don't appear to correspond to entries in `portal_memberdata` or `acl_users`. Those errors seem to appear when viewing the user listing, so they aren't likely relevant to the issue at hand anyway.

**Comment by alecpm** [comment]
This is fixed now. There was a debug prompt sneakily inserted into a file on staging only and then apparently forgotten. I'm surprised it didn't trigger more deadlocks than just this one.
