### ISSUE TITLE
nav portlet disappears on profile after editing - 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#368]
This is an intermittent problem. We have not been able to identify a consistent mechanism for repeat. Fiddling with renaming, re-editing, blocking/unblocking parent portlet, and screaming into the void sometimes unpredictably seems to lead to things working again.

Known past/current victims:

 - rbagnall
 - dratzan

**Comment by paregorios** [comment]
cc @k2soule

**Comment by paregorios** [comment]
Here's the email thread dealing with this when it happened to dratzan's profile back in February:

> On Thu, Mar 1, 2018 at 1:23 PM, Kristen Soule <kristen.soule@nyu.edu> wrote:
> It worked. (and then I went back through two dozen pages that needed links updated... whee!)
>
> On Thu, Mar 1, 2018 at 12:18 PM, Kristen Soule <kristen.soule@nyu.edu> wrote:
> I'm going to try creating a new profile, copying in the relevant text (and the CV), and deleting the old one if that turns out looking ok...
>
> On Thu, Mar 1, 2018 at 10:56 AM, Thomas Elliott <tom.elliott@nyu.edu> wrote:
> That is freakin’ weird. It’s like it’s using the wrong view and everything (underlying page structure differs from all other profiles - it’s using single-column layout instead of dual-column), but I can’t find any reason for that. I’ve fiddled with a bunch of stuff, but not succeeded in making any changes. This may require a Jazkarta consult. :(
>
> On Wed, Feb 28, 2018 at 1:00 PM, Thomas Elliott <tom.elliott@nyu.edu> wrote:
Thanks, I'll take a look.
>

**Comment by paregorios** [comment]
Here's a chat transcript dealing with this when it happened to rbagnall's profile back in April:

> 2018-04-12T11:11:47-0500] <ksoule> oh, this oddity is happening again: the portlets disappeared when I checked in Roger’s working copy of his profile https://isaw.nyu.edu/people/faculty/emeritus-faculty/roger-bagnall
> [2018-04-12T11:12:22-0500] <ksoule> I tried toggling the parent portlet off and then on again… no change :(
> [2018-04-12T11:12:35-0500] <paregorios> urhghghghg
> [2018-04-12T11:15:11-0500] <paregorios> it's not a css thing; the portlet is missing from the page, so something's suppressing it in template application to generate the html
> [2018-04-12T11:15:31-0500] <ksoule> wheee
> [2018-04-12T11:16:14-0500] <paregorios> did this happen on Roger's profile before, or someone else's?
> [2018-04-12T11:29:51-0500] <ksoule> It happened to a different page before, I think David's
> [2018-04-12T11:30:09-0500] <paregorios> I bet this is a permissions thing.
> [2018-04-12T11:30:22-0500] <paregorios> Did it happen when you did something or when Roger did something?
> [2018-04-12T11:31:49-0500] <ksoule> I’m trying to remember whether the portlets were there or not when it was still a working copy… I’m not certain, but I think they were still there. However, they were gone after check-in
> [2018-04-12T11:32:07-0500] <ksoule> I was thinking it might have something to do with the permissions on the Emeritus Faculty folder,
> [2018-04-12T11:33:00-0500] <ksoule> because the portltets also disappeared at that level as soon as I had checked in his page. However, I was successful at bringing them back after blocking and then un-blocking the parent nav portlet (the good old hokey-pokey trick)
> [2018-04-12T13:00:49-0500] <ksoule> paregorios: I’m thinking I’ll just create a new profile and copy the contents into it
> [2018-04-12T13:01:15-0500] <paregorios> ksoule: I think that's what we have to do until I can get resources to get some troubleshooting/development help on this stuff.
> [2018-04-12T13:13:35-0500] <ksoule> …and it will only break eighteen links!
> [2018-04-12T13:13:40-0500] <ksoule> :D
> ...
> [2018-04-12T13:49:50-0500] <ksoule> paregorios: the strangest thing just happened...
> [2018-04-12T13:50:49-0500] <ksoule> parehyperbolic… I was editing the new profile, and it just flipped from normal to missing the portlet - again!
> [2018-04-12T13:51:14-0500] <parehyperbolic> [expletive deleted]
> [2018-04-12T13:51:26-0500] <parehyperbolic> there's something screwed up there for sure
> [2018-04-12T13:51:30-0500] <ksoule> I had deleted the old one, and renamed the new one (short name slug)
> [2018-04-12T13:51:43-0500] <parehyperbolic> ugh
> [2018-04-12T13:51:50-0500] <ksoule> so just for the heck of it, I renamed the profile to something else entirely, and the portlet is back
> [2018-04-12T13:51:58-0500] <parehyperbolic> ermagerd
> [2018-04-12T13:52:17-0500] <ksoule> wacky

**Comment by k2soule** [comment]
Thanks! I’m going to go chase after this peculiar yak some more, possibly with a different set of shears...

**Comment by paregorios** [comment]
Currently dratzan is exhibiting this behavior again. 

I renamed to dratzan2 and the nav portlet appeared. I renamed back to dratzan and it went away again.

I purged cache via the control panel. No change.

**Comment by skleinfeldt** [comment]
@alecpm @cguardia @jessesnyder Does this problem ring a bell? Or could you give @k2soule any tips about what information to look for while she is troubleshooting? (Hints to look for in the content, in the page source, in the portlet settings, etc.) Anything better than screaming into the void...

**Comment by paregorios** [comment]
On IRC @alecpm suggested that "this may just be [this root node issue](https://github.com/isawnyu/isaw.web/issues/277) cropping up again in another form."

**Comment by paregorios** [comment]
On IRC @alecpm follows up with:

> I do see the root node is being used, but changing that doesn’t fix the issue. It does really seem to be tied to the id somehow.

**Comment by alecpm** [comment]
The entire portlet column is missing from the page. It doesn't appear in the unthemed view either: http://66.35.39.43/people/staff/dratzan which rules out diazo rule issues.

**Comment by alecpm** [comment]
A couple additional notes on this weirdness. It seems to be tied in some way to the people section. If I add a navigation portlet to `dratzan` that is rooted at e.g. `/events` it will show up, but if I add one rooted at `/people` or even one from the root of the site that only shows the second level it does not appear. So somehow the portlet disappearance is tied to specific person ids and navigation portlets that include the `/people` section. Super weird, and I suspect someone will have to pdb into this to see what's really happening.

**Comment by paregorios** [comment]
See possibly related issue #277

**Comment by cguardia** [comment]
@paregorios  I have not been able to find what's causing this, but it turns out if I create a new profile and copy the data from the original, it works fine. I have an unpublished david-m-ratzan profile now ready to take over. The URL will change (from mratzan), but I can add an alias. I need a green light to make the substitution.

My proposal is we just make the switch and avoid using more time to find what caused the problem.

**Comment by paregorios** [comment]
@cguardia I've looked over the new profile and have just one concern for you to address before making the change:

There's a link in the prose using the text "[Curriculum vitae]" (it's at the end of the paragraph right before the "Recent Publications" subheading). It links to a PDF file that is contained inside the original profile (https://isaw.nyu.edu/people/staff/dratzan/20190110-ratzan-cv). Please put a copy of that PDF file inside the new profile and update the link accordingly.

Once that's addressed, please go ahead and make the switch and include the alias.

**Comment by paregorios** [comment]
My review of the results looks good. I used the ```/ownership_form``` to change from your userid to the user's. I've emailed him and asked him to look it over and make sure everything is ok and working right for him. I'm moving this ticket to "deployed" but will keep it open until I have confirmation from the user.

**Comment by paregorios** [comment]
User confirms: "Looks good to me!"
