### ISSUE TITLE
configure the site for split view caching

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#369]
per @alecpm :

> That will be completely necessary once the site is available under SSL for both logged in and non-logged in users. You’ve been able to ignore that sort of cache pollution because logged in and non-logged in users historically used different urls, but that won’t be the case anymore.

**Comment by alecpm** [comment]
Add apache config for `X-Anonymous` header

**Comment by cguardia** [comment]
Turns out the header was already inserted by varnish, but the code was missing the saml2 cookie names, and thus didn't work. This was fixed with #386.

**Comment by alecpm** [comment]
I think we can close this one.

**Comment by cguardia** [comment]
Yeah, just wanted to add idp_id cookie and simplify the expression a bit, which I did.
