### ISSUE TITLE
Move amheida.org files to Plone site

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#371]
- [x] Make a zip file of the Amheida /inc directory
- [x] Install zip uploader add-on on staging
- [ ] Upload all files to the /research/amheida folder on staging, laid out as it is now (/inc/pdf, /inc/img, /inc/img/plans, /inc/img/sat, /inc/js...)
- [ ] Uninstall zip uploader when done, unless we see a reason for keeping it around
- [ ] Report time on Freshbooks "ISAW Amheida Website" project

**Comment by alecpm** [comment]
I'll be installing [ftw.zipextract](https://pypi.org/project/ftw.zipextract/) today which should allow you to upload and extract the zipped files into the site.

**Comment by skleinfeldt** [comment]
👍

**Comment by alecpm** [comment]
This ZIP add-on is now installed on staging, I was able to test it locally and it worked well. First add a new file object with the zip. Then visit the url for that file with `/zipextract` appended. That will give you a UI for extracting some or all of the files into Plone.

To login you'll need to use:

https://isaw.jazkarta.com/portal_skins/plone_login/login_form

Unless you have an NYU login.

**Comment by skleinfeldt** [comment]
Awesome, thanks @alecpm. I'll work on this next week when I'm back from Italy. (FYI @paregorios )

**Comment by skleinfeldt** [comment]
@alecpm I'm finished with ftw.zipextract, you can uninstall and remove if you want.

I still need to bulk upload the images (zipextract turns them into files) so please install wildcard.foldercontents or one of the other bulk image upload tools.

**Comment by skleinfeldt** [comment]
Added "review" label, all files are moved and Amheida work on staging is under review.

@paregorios please comment if you would like us to remove ftw.zipextract and wildcard.foldercontents add-ons from staging. (They are not on production so should disappear the next time we clone production to staging - but that might not be for a while.)

Close this when you are satisfied.
