### ISSUE TITLE
clicking "previous" or "next" in events mini-calendar produces sheer madness

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#376]
Steps to recreate:

 - Visit http://isaw.nyu.edu/events/
 - Navigate to the mini calendar in the right portlet slot
 - Click "next" or "previous"
 - Observe that, apparently, the entire /exhibitions page gets served up through the portlet

<img width="633" alt="Screen Shot 2019-03-28 at 9 49 16 AM" src="https://user-images.githubusercontent.com/263285/55167340-c5ced700-513e-11e9-91fa-6110d436a1b6.png">

**Comment by cguardia** [comment]
This is working now. I spent too much time trying to figure out the difference with staging, then decided to try to re-save the JS, and that did it.

**Comment by paregorios** [comment]
Thanks!
