### ISSUE TITLE
http timeouts/503

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#377]
@k2soule  and I saw two of these incidents (last Friday and today). I tried to look at CPU utilization and briefly at apache logs but didn't spot anything obvious. I didn't have time to look at instance logs. 

Tummy reports:

> We received two alerts that HTTP was timing out on isaw4. HTTP was timing out during these periods yesterday.
> 04:40 - 04:59
> 22:48 - 23:07
> 
> While looking at our monitoring it looks like HTTP is timing out on isaw4 during other periods yesterday as well, just not long enough to alert.
> 09:14 - 09:23
> 03:14 - 03:20
> 01:39 - 01:48
>
> The timeouts seem to date back months and appear at seemingly random times though they seem to appear more frequently and for longer times in the recent past.
>
> Has anything changed recently on isaw4 where it would be timing out more frequently or for longer times? Should it be timing out at all?

**Comment by paregorios** [comment]
I have asked tummy to do an apache and process log analysis to look for excessive http request or process cpu/memory/disk utilization concurrent with the recent timeout periods.

I think we need to do a log analysis on the plone installation and other assocaited components to see if something is happening at that level.

**Comment by paregorios** [comment]
cc @skleinfeldt @alecpm @cguardia @jessesnyder

**Comment by paregorios** [comment]
Tummy has recommended we move to a new VM, which they are getting ready. Meantime also see #381 which may be related.

**Comment by paregorios** [comment]
@alecpm Do we need to put memon/superlance in place for this website like we recently did for pleiades?

**Comment by alecpm** [comment]
It's probably not a bad idea, generally. Are there indications that RAM usage is responsible for these outages? What's the intention of the new VM?

**Comment by paregorios** [comment]
Yes, tummy has noted:

>  isaw4 with only 4GB of memory, has been in need of memory for a while now, and is swapping heavily over time, as if there is a memory leak somewhere. We are provisioning a new virtual hosting solution and would like to get isaw4 migrated to a virtual machine on our new virtual host with a new OS, Ubuntu 18.04, and more RAM than the current isaw4 ...

**Comment by alecpm** [comment]
In that case, simply turning on memmon may be preferable to a new VM (though 4GM RAM is indeed pretty minimal, especially for a site with a decent amount of content and a potentially large number of logged in users). Upgrading from Ubuntu 16.04 to 18.04 could require more work than you want to take on at the moment.

**Comment by alecpm** [comment]
I've enabled `memmon` in the production buildout with a limit of 750MB for each ZEO client. I suspect that might still be a little high given the RAM limits on he machine and the huge amount of RAM being consumed by `shibd`. I may also switch varnish to use a disk cache instead of malloc'ing 256MB RAM.

**Comment by paregorios** [comment]
This seems to be helping. Until we transition to new server and upgrade SSO, there's not much else we can do here, so closing as resolved.
