### ISSUE TITLE
home page slider controls are a mess on mobile

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#379]
- they are too small
 - they block other text content

**Comment by paregorios** [comment]
![IMG_4941](https://user-images.githubusercontent.com/263285/58053125-3d582b80-7b1c-11e9-9b0e-6906910b0de4.jpg)
![IMG_4942](https://user-images.githubusercontent.com/263285/58053126-3d582b80-7b1c-11e9-8718-7a33461c06ea.jpg)
![IMG_4943](https://user-images.githubusercontent.com/263285/58053127-3d582b80-7b1c-11e9-893a-29c9e1959fd3.jpg)
![IMG_4944](https://user-images.githubusercontent.com/263285/58053128-3d582b80-7b1c-11e9-96d5-2d072ea742f6.jpg)
![IMG_4945](https://user-images.githubusercontent.com/263285/58053129-3df0c200-7b1c-11e9-83b1-402a84aa2af8.jpg)

**Comment by jessesnyder** [comment]
@paregorios Is there an easy way to trigger the auto-generated `<ul>` that's causing the biggest problems on the staging server? (Potential fix is deployed there.)

**Comment by alecpm** [comment]
I would also suggest maybe setting `#content #slider .slide .slideroverlay { background-color: transparent;}` on mobile to fix the issue with the text overlay color not blending with the background.

**Comment by paregorios** [comment]
This is a significant improvement. Please merge to master and deploy to production.

**Comment by paregorios** [comment]
Looks good. Thanks.
