### ISSUE TITLE
implementing story #98 "space aliens" (from isaw.theme)

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#38]
Copying over from .theme:
It appears that the emergency message element is being generated underneath the header bars on the home page (a layer that is not visible), rather than pushing the page header and contents down from above. On all other pages we've checked, the emergency message appears as intended. We'll need some assistance tweaking the home page to make the "aliens/bigfoot" message bar appear at the top.

**Comment by paregorios** [comment]
check on current behavior

**Comment by paregorios** [comment]
further testing and review is blocked until we can verify that staging is running the same code as production

**Comment by paregorios** [comment]
This is a pure themeing (CSS) issue. Transferring to tracker on isaw.theme: https://github.com/isawnyu/isaw.theme/issues/92
