### ISSUE TITLE
get rid of font Questrial - 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#380]
We use it in some headings and other places, but it is missing a lot of extended ASCII characters (let alone non-Roman characters) and things look weird when it cascades down to Noto Sans for just those characters (according to our CSS rules). Better if it were all Noto Sans IMO.

**Comment by paregorios** [comment]
Here's an example of a page where it is happening:

http://isaw.nyu.edu/events/archive/2017/AlextoIsk

![Screen Shot 2019-05-22 at 9 42 10 AM](https://user-images.githubusercontent.com/263285/58184088-0b5adc80-7c76-11e9-8f6d-9c54ac853b77.jpg)

**Comment by jessesnyder** [comment]
@paregorios On staging now.

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.
