### ISSUE TITLE
big log files on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#381]
From tummy: 

> We got another alert that the isaw.nyu.edu page was throwing a 503 server unavailable message at 16:11 - 16:27 Mountain time. I didn't see anything obvious in the apache logs. Load and cpu usage were next to nothing at the time. The issue seems to be memory related, so it could be that giving the new isaw4 will make this go away, or it may just mask the issue, not sure at this point.
>
> I did find the plone logs here, and found that they are over 4G in size and date back to 2014.
>
> \# du -sh /srv/isaw.web/var/log/client*-Z2.log
> 4.2G /srv/isaw.web/var/log/client1-Z2.log
> 4.2G /srv/isaw.web/var/log/client2-Z2.log
> 4.2G /srv/isaw.web/var/log/client3-Z2.log
> 
> You may want to take a look at these and start fresh log files or set up log rotation of these.
>
> The larger the log file, the more difficult it becomes to parse through it for investigation purposes. Also, because these log files are changing each day, the backup server is keeping a copy of each file in each snapshot which contributes to backup server usage.

**Comment by alecpm** [comment]
I've manually enabled log rotation on production for the plone related log files in `/srv/isaw.web/var/log`

**Comment by paregorios** [comment]
This seems to be working well. Closing as resolved.
