### ISSUE TITLE
Migrate to new VM for production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#383]
As an ISAW website user, I will experience the unmitigated joy of using the website as deployed on a new, snappier, more sassy production VM provided by tummy.

**Comment by paregorios** [comment]
Steps to implement:

 - [ ] get VM from tummy
 - [ ] upgrade all components of isaw.web (via ansible) to work with Ubuntu 18

**Comment by alecpm** [comment]
SSO did not work when masquerading as isaw.nyu.edu (`The application you have accessed is not registered for use with this service.`) or as isaw-new.jazkarta.com (`KeyError: 'https://shibbolethqa.es.its.nyu.edu/idp/shibboleth'`). This is not surprising, but means we need something updated on NYU/Yavor's end.
