### ISSUE TITLE
SAML2 login on staging redirect loop after authentication

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#386]
Steps to reproduce:

 - Visit staging server home page
 - Select the "LOG IN (SAML2)" link
 - On the "NYU Login" page (shibbolethqa...), enter the test netid and password, then select the "login" button
 - Watch the endless redirect loop between the production home page and the shibbolethqa page spool out

**Comment by alecpm** [comment]
@jessesnyder Any ideas about his one?

**Comment by paregorios** [comment]
On October 29, 2018, Yavor Yanakiev wrote: 

> The ISAW QA is in place. Authentication seems to work but there is a looping issue at SP end.

Subsequently, I wrote (at the encouragement of @jessesnyder): 

> Jesse has been troubleshooting the SP-side looping problem you mentioned in your email (below). This problem seems to be caused by  the fact that the assertions returned in the SAML2 response from NYU are now of type EncryptedAssertion instead of Assertion, and the Plone SAML2 code doesn't even check for EncryptedAssertions, so it doesn't know what to make of the "successful" response, and tries to authenticate all over again.

Yavor replied:

> Judging by the explanation of the problem, the issue is the encryption of the assertion. ...
Encrypting assertion is the default behavior in SAML protocol and it should be the default behavior for its implementations. I can disable assertion encryption for testing purposes but it's strongly recommended not to do it in production. 

> The isaw.jazkarta.com.isaw-saml-entity metadata suggests encrypted assertion, the default behavior, and since not encrypting the assertion was not requested in any other way, we left the default behavior in place. The assertion encryptions has been disabled. Please test.

**Comment by paregorios** [comment]
Here is where we got past this looping problem last time: https://github.com/isawnyu/isaw.web/issues/328#issuecomment-445390609

**Comment by paregorios** [comment]
In other words, this looks like it might be a code regression on staging.

**Comment by alecpm** [comment]
Yeah, looks like those changes to the Varnish VCL didn't make it into the ansible configs. The good news is that they also include the fixes needed for Split View Caching (#369). @cguardia Do you want to look at the VCL changes indicated on #328 and incorporate those into the ansible varnish config, or should I.

**Comment by cguardia** [comment]
I made the changes on staging and  they work nicely. Now will incorporate them into ansible.

**Comment by skleinfeldt** [comment]
Yeah but... Yavor's email above stated that he could "disable assertion encryption for testing purposes but it's strongly recommended not to do it in production." 

And Jesse said "the Plone SAML2 code doesn't even check for EncryptedAssertions."

I suspect we don't want to have to implement EncryptedAssertions, right @alecpm and @cguardia? So @paregorios I think you are going to have to beg and plead the impossibility of enabling it on production.

**Comment by paregorios** [comment]
@cguardia Please go ahead and incorporate current changes into ansible. @skleinfeldt let's discuss this other issue at standup tomorrow.

**Comment by cguardia** [comment]
Changes have been incorporated into ansible repository.

**Comment by jessesnyder** [comment]
Sounds like you found the cause of the looping: the varnish config needs an update to avoid stripping cookies, as I was struggling to remember on Slack.

**Comment by skleinfeldt** [comment]
> @skleinfeldt let's discuss this other issue at standup tomorrow.

Hopefully you mean the question of assertion encryption? If something else, please clarify.

**Comment by paregorios** [comment]
@skleinfeldt yes, assertion encryption
