### ISSUE TITLE
SSO logins failing on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#391]
As of sometime in the last couple of hours, logins for me on production are failing. The browser ends up on this page: https://shibboleth.nyu.edu/idp/profile/SAML2/POST/SSO with the message 

```
Error

The application you have accessed is not registered for use with this service.
```

I am testing further.

**Comment by paregorios** [comment]
This happens even when I clear cache.

**Comment by paregorios** [comment]
This happens in all browsers available to me.

**Comment by k2soule** [comment]
I'm also seeing this error when attempting to log into the production web.

**Comment by paregorios** [comment]
We are working this problem in collaboration with NYU Identity Management.

**Comment by k2soule** [comment]
Temporary fix in place (will last one day), according to thread with NYU IDM. I am currently able to log in, and seeing landing page "You are now logged in via SAML2 SSO."

Permanent fix is being negotiated with IDM...

**Comment by paregorios** [comment]
This seems to be resolved.
