### ISSUE TITLE
news rss link in footer redirects to non-existent page

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#393]
This is a regression that I've seen before, but I have no memory of how it was fixed previously.

**Comment by jessesnyder** [comment]
@paregorios Is the link supposed to be there and point somewhere else, or should it not be there at all?

**Comment by jessesnyder** [comment]
(I suspect it rose from the grave when we ran the install profile to enable SAML2. Standing by armed with shovel to re-bury now...)

**Comment by paregorios** [comment]
We're supposed to have news blog syndication and the link in the footer is supposed to point to it, but it's busted on staging too (but differently!) and I don't remember what the correct URL is (though I have some places I can look). And I can't find it just poking around.

**Comment by paregorios** [comment]
I've poked around in portal_actions through the ZMI to see if I can figure out how to get this link back in the footer that way, but I've had no success. So I could use some help here.

**Comment by jessesnyder** [comment]
@paregorios I had hidden it. I just updated the URL and re-enabled.

**Comment by paregorios** [comment]
And the people rejoiced!

**Comment by jessesnyder** [comment]
Installation profile updated on a branch. Will merge to master when deemed OK.

**Comment by paregorios** [comment]
reopening to track merge and deployment.

**Comment by paregorios** [comment]
As noted earlier, this is working on production. Please verify that the installation profile update has been merged to master and deployed successfully to production.
