### ISSUE TITLE
Error attempting to checkout Profile page

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#396]
User is attempting to check out a working copy of his profile (gm95@nyu.edu).
Get gets a message directing him to select a folder to put the working copy into... with no options to select. When he tries to proceed, he gets an error message that it "can't find that location", and it won't proceed.

(As a site administrator, I don't see the location selection message or the error - I'm able to check out a working copy of any profile item, as usual.)

**Comment by paregorios** [comment]
I have replicated this behavior using a test user account on **staging.** Here are the steps:

- As an admin user, navigate to ```/people/staff/tom-elliott```
- Using the ```ownership_form```, change the owner to jcarberry@nowhere.com
- Log out
- Log in as jcarberry@nowhere.com
- Navigate to ```/people/staff/tom-elliott```
- From the tertiary green menu bar, select "actions" -> "check out"
- See the checkout confirmation/cancel form (see screen shot below)
- Click the "Checkout" button
- Observe that the base view has reloaded in the browser, along with a notice that reads "Cannot find checkout location" and that no checkout seems to have been created

Here is what the checkout confirm/cancel form looks like:

![Screen Shot 2019-09-09 at 3 54 23 PM](https://user-images.githubusercontent.com/263285/64565894-5af31000-d31a-11e9-9db4-3476f6bed74d.png)

Here is what the base view looks like after failed checkout attempt:

![Screen Shot 2019-09-09 at 3 56 27 PM](https://user-images.githubusercontent.com/263285/64565933-6fcfa380-d31a-11e9-9cd3-b0c792b386cf.png)

**Comment by paregorios** [comment]
I have the sense that this may be related to changes we made to our workflow and permissions model, but I cannot find a ticket that is clearly the one at issue.

**Comment by alecpm** [comment]
It's interesting that the checkout form doesn't show any folders under "Checkout Folder". Seems like I'll need to look into the logic used for determining that location and possibly provide it with a fallback for cases where the default isn't accessible to the user making the checkout.

**Comment by alecpm** [comment]
So it looks like the default behavior of including the user's home folder in the list of default checkout locations was explicitly disabled in 2016 on the `no_home_locator` branch commit c230bf0f7271698094b614750113fd4b00cb6f4a. I'll re-enable to see if it works for this usecase, and if not we may need to implement a custom folder locator (which appears to be quite simple) or patch the `portal_membership.getHomeFolder()` method to return the proper directory for ISAW users if, for some reason, it doesn't currently.

**Comment by alecpm** [comment]
I think this fixes the issue, except the permissions on who can add `profile` content are limited to `Contributor` and `Manager` (curiously not `Site Administrator`), which seems a bit restrictive. If we allowed `Owner` and `Site Administrator` to add `profile` and `CV` objects that would probably be sufficient to address this issue. I've done that manually on staging for testing purposes.

**Comment by alecpm** [comment]
That appears to have worked (in combination with removing the patch to disable home folder checkouts):

https://isaw.jazkarta.com/members/jcarberry-40nowhere.com/tom-elliott

**Comment by alecpm** [comment]
For users/locations where the user has permission to check out into the parent folder of the original object, the checkout form will now have radio buttons to choose the checkout location (either the user home folder or the current parent folder).

**Comment by paregorios** [comment]
This is working as desired. Please merge to master and deploy to production.

**Comment by alecpm** [comment]
This is deployed to production.
