### ISSUE TITLE
footer editing

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#40]
Hours information has been updated, but the footer appears with a vertical scroll bar now.

**Comment by k2soule** [comment]
eventually, we're going to need a more intuitive mechanism for editing footer information.

**Comment by k2soule** [comment]
Alec fixed the footer height via CSS.

**Comment by paregorios** [comment]
Reopening. I assumed this ticket was only about CSS but now I see it's really about the editing content issue.

**Comment by paregorios** [comment]
Yes, we need the ability to modify footer content -- specifically gallery and library hours -- through the web. Pushing theme updates to change these will be a pain.

**Comment by cguardia** [comment]
I did this and pushed to master but I ran out of time to deploy. Note that since we were getting two dynamic bits already (support ISAW link and personal tools), the html structure needs to keep tags for "footer-support-link" and "personal-tools-links" intact.

**Comment by paregorios** [comment]
I just tried deploying this on staging and the entire footer is now missing. Will investigate, but please @alecpm @skleinfeldt @k2soule @cguardia no one deploy master on production until we sort this.

**Comment by paregorios** [comment]
On staging, ```/@@isaw-settings``` throws the following traceback:

```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.z3cform.layout, line 66, in __call__
Module plone.z3cform.layout, line 50, in update
Module plone.z3cform.fieldsets.extensible, line 59, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 132, in update
Module z3c.form.form, line 128, in updateWidgets
Module plone.app.registry.browser.controlpanel, line 48, in getContent
Module plone.registry.registry, line 74, in forInterface
KeyError: 'Interface `isaw.theme.browser.interfaces.IISAWSettings` defines a field `footer_html`, for which there is no record.'
```

**Comment by paregorios** [comment]
@cguardia @skleinfeldt I would prefer that we back this out of master ASAP until it has been thoroughly tested and accepted so its presence there is not a blocker for deploying other key capabilities.

**Comment by skleinfeldt** [comment]
Sent an urgent email to Carlos and Alec to make sure they see this; I'll be unavailable the rest of the morning.

**Comment by cguardia** [comment]
Sorry, I was away. That error means that you need to run the upgrade step I added for the theme.

**Comment by paregorios** [comment]
How is that upgrade step run?

**Comment by paregorios** [comment]
From @cguardia here's how to run the upgrade step:

> go to the add ons control panel, there should be an upgrade button next to the theme package

**Comment by paregorios** [comment]
Also a caveat from @cguardia:

> whoever is going to edit that should be careful with changing any css ids  or classes. That could wreck the layout. If  you focus on the wysiwyg text, changes like opening hours are super easy

I note that admin users could also make changes in raw HTML, thereby being able to see the structure and respect it.

**Comment by paregorios** [comment]
Thanks to guidance from @cguardia I am confident that this capability is now ready for deployment to production. I can perhaps do that this afternoon.

**Comment by paregorios** [comment]
There are now more problems on staging with the footer. A bunch of crazy stuff, including apparently all the content actions (like workflow transitions, cut, copy, paste, etc. is appearing in the footer now). Here is a screen capture:

![footermess](https://cloud.githubusercontent.com/assets/263285/9558708/679d5090-4dae-11e5-84dd-2f203ce8c478.jpg)

This doesn't seem to happen on control panels, but regular content items (including the home page) it does (for authenticated users).

This is once again a blocker for deploying anything to production, including the fixes that have been made for #42, #48, and #49.

**Comment by cguardia** [comment]
I can take a look at that in a few minutes.

**Comment by cguardia** [comment]
I was pulling the wrong css class in the rule, sorry. Fixed that on the theme product and on staging.

**Comment by paregorios** [comment]
looks good on staging, thanks!

**Comment by paregorios** [comment]
This looks fixed to me. @k2soule do you agree? If so, please close.

**Comment by k2soule** [comment]
Yes, this is working. Closing ticket...
