### ISSUE TITLE
do not include bare URIs in the publications listing - 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#400]
Currently the publication listing includes a plain-text URI that seems to be the "access URI". There should be no bare URIs in the listing. 

![listing](https://user-images.githubusercontent.com/263285/64796876-67f84500-d54e-11e9-9caa-846a203b0cb9.jpg)

**Comment by alecpm** [comment]
@paregorios Could you provide a URL where you're seeing this issue. I want to make sure I'm looking for this stray URL in the correct place.

**Comment by paregorios** [comment]
It looks to me now like these are coming in with the "formatted citation" from the Zotero CSL call, so the listing view may not need changing at all. 

What we may need to do is set up a custom CSL transform that we can feed to the Zotero API (they have a mechanism for that -- we'd just have to post our custom CSL at a stable URI and feed it to their API in a query parameter). I'll get the details sorted. 

I'll try to get this sorted before standup today.

**Comment by paregorios** [comment]
This is not a problem with the publications listing. Closing "not a bug so nothing to fix".

**Comment by alecpm** [comment]
I was bit concerned that was the issue. In that case I think it may make sense to wrap this into #402, or make it dependent on those changes.

**Comment by paregorios** [comment]
@alecpm see now #404

**Comment by paregorios** [comment]
@alecpm for the short run, since we know this is coming from the formatted citation field, we can just edit out any URI that comes along with the citation when fetched from Zotero.
