### ISSUE TITLE
add link@rel=alternate to base view on publications type - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#403]
When a publication object has content in its Zotero URI field of the form ```https://www.zotero.org/users/465/items/9ET8PPYI```, construct ```<link>``` elements in the ```<head>``` element of the base view as follows:

```
<link rel="alternate" type="text/html" href="https://www.zotero.org/users/465/items/9ET8PPYI"/>
<link rel="alternate" type="application/json" href="https://api.zotero.org/users/465/items/9ET8PPYI?v=3&format=json"/>
```

**Comment by alecpm** [comment]
This is on staging for review.

**Comment by paregorios** [comment]
I'm looking at https://isaw.jazkarta.com/members/paregorian/fun-with-publications-3/the-moon-phase-anomaly-in-the-antikythera-mechanism but don't see the expected tags. Perhaps the URI matching doesn't extend to URIs like ```https://www.zotero.org/groups/242005/items/IG5FSTMD```. In other words, we need to trigger on any URI that meets all the following criteria:

- netloc = "www.zotero.org"
- path matches a regex like ```"^(groups|users)/\d+/items/[A-Z1-9]+$"```

It's working fine for https://isaw.jazkarta.com/members/paregorian/fun-with-publications-3/aksum-and-nubia

**Comment by alecpm** [comment]
Initially I had cast a wider net that included `groups` zotero links, but the one group link I tested with gave an error when turned into the JSON format:

https://api.zotero.org/groups/pleiades/items/7F7NHNWS?v=3&format=json

This one works though:

https://api.zotero.org/groups/242005/items/IG5FSTMD?v=3&format=json

So I guess it's semi-safe to do this anyway.

**Comment by paregorios** [comment]
Yeah, the difference in those two links is the use of the numeric code for the group ID as opposed to the alpha short-name for same. The HTML web interface supports both (and does a redirect from the numeric to a variant of the alpha version of the URI). But the API only seems to support the numeric version.

**Comment by alecpm** [comment]
This is up on staging.

**Comment by paregorios** [comment]
This looks good, thanks. Please merge to master and deploy to production.

**Comment by paregorios** [comment]
I'm not seeing this on production.

**Comment by alecpm** [comment]
I'm certain the code is deployed, could you provide an example url of a piece of content where you'd expect the links to appear and they are not?

**Comment by paregorios** [comment]
I would expect to see it here, but I don't:

https://isaw.nyu.edu/members/te20-40nyu.edu/benito-2009

**Comment by alecpm** [comment]
This should be working on staging now, e.g.:

https://isaw.jazkarta.com/members/te20-40nyu.edu/benito-2009

The problem is that the API urls can't be generated without a numeric group or user id and the [zotero URL](https://www.zotero.org/groups/pleiades/items/LNIFF9U7) for that entry didn't have one in the URL. Visiting that URL directs to [the real url with numeric id](https://www.zotero.org/groups/2533/pleiades/items/LNIFF9U7). I've updated the url parser to better handle this url format, and I've also updated the bibliographic data fetcher to update the url to the final redirected url.

Once the fix is in place the link tags won't appear until you edit the item and use the "Fetch Bib Info" button to update the url.

**Comment by alecpm** [comment]
Additionally, there was an issue with making SSL connections to the Zotero API which was resolved by updating the python SSL library versions.

**Comment by paregorios** [comment]
OT: this feature is an investment in the future: https://forums.zotero.org/discussion/93270/support-for-importing-ris-via-connector

**Comment by alecpm** [comment]
@paregorios This is live on production now. Existing publications may need their bibliographic information refreshed in order to get a correct canonical zotero url.

**Comment by paregorios** [comment]
Looks good.
