### ISSUE TITLE
isaw website does not return to operation after a host reboot

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#412]
This has happened twice in a row after tummy reboots the server to apply patches. Host is up and running, but any site URL returns 503. In both cases I've connected to the host via ssh, and observed via supervisorctl that the following processes are running and have times consistent with having started running after system reboot:
```
primary_memmon                   RUNNING   pid 731, uptime 11:00:50
primary_zeoclient1               RUNNING   pid 735, uptime 11:00:50
primary_zeoclient2               RUNNING   pid 733, uptime 11:00:50
primary_zeoclient3               RUNNING   pid 734, uptime 11:00:50
primary_zeoclient4               RUNNING   pid 736, uptime 11:00:50
primary_zeoserver                RUNNING   pid 732, uptime 11:00:50
```

Issuing "restart all" seemed to fix it the first time this happened, but not when it happend this morning. Issuing "service varnish restart" seemed to fix it this morning.

**Comment by alecpm** [comment]
I'll check that varnish, supervisor, haproxy, and nginx are enabled at boot.

**Comment by alecpm** [comment]
And when I say nginx, I mean apache2 of course ;-)

**Comment by alecpm** [comment]
There does seem to be something funny with the varnish systemctl config. Looking into it now.

**Comment by alecpm** [comment]
I believe this is fixed now both on the server and in the ansible config. Let me know if you'd like me or Tummy to do a test reboot late tonight or similar.

**Comment by paregorios** [comment]
Sorry I wasn't able to close the loop on a test. The good news is that Tummy did a reboot last night to apply patches and everything looks good this morning! Closing as resolved.
