### ISSUE TITLE
items "published externally" are no longer visible to anonymous

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#418]
Steps to recreate:

- As an anonymous user, navigate to https://isaw.nyu.edu/guide/it/web-profile-edit
- Note that authentication is required
- Login to the plone
- Note that the above page has workflow status "published externally"

**Comment by paregorios** [comment]
Blocks issue #426

**Comment by alecpm** [comment]
FWIW, the permissions on the page (via `/manage_access`) looked fine to me, but retracting the page and publishing it again seems to have fixed it. 🤷‍♂️ Since this issue seemed to be isolated to this one page, I don't think there's much to do here.
