### ISSUE TITLE
intranet workflow not properly applied to child folders

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#42]
For items assigned placefully to "intranet workflow", we expect to have the following states available:

* private
* internal draft
* pending
* internally published
* externally published

But we only have:

* private
* internal draft

**Comment by paregorios** [comment]
Actually, it seems to be inconsistent. Getting more data...

**Comment by paregorios** [comment]
Actually, content areas that already had "intranet workflow" assigned before the design rollout seem to be fine (e.g., /about/employee and /guide), but when I newly apply the policy to a context, I only see the two options indicated above ("private" and "internal draft"), e.g., /about/latest

**Comment by paregorios** [comment]
I think this is fixed. Double-check.

**Comment by paregorios** [comment]
This is not fixed. Will provide details shortly.

**Comment by paregorios** [comment]
I have an example folder where this is happening: .

 * I logged in via Shibboleth using my netid
 * I navigated to my personal folder
 * I created a folder therein with the id ```workflow-tests-intranet```
 * I added placeful workflow "intranet" to folder and to below the folder
 
The folder shows "State: Internal Draft". When I click the state transition menu, I only see the following options:

 * Make private
 * Advanced ...
 * Policy ...

As noted earlier in the issue comment thread, folders that had the "intranet" placeful workflow applied prior to new theme rollout seem to be working fine (i.e., I get the proper state transition options). An example is ```/guide```.

**Comment by paregorios** [comment]
In addition to the example immediately above, I have also been able to cause this failure to occur by adding a folder to ```/permission-tests/intranet-workflow-tests```. The added folder is ```https://isaw.nyu.edu/permission-tests/intranet-workflow-tests/foo/```. This new folder acquired the initial state as expected on creation: ```internal draft```. But the only options, even for an admin user, on the "state" menu are:

 * "Make private"
 * "Advanced..."
 * "Policy..."

**Comment by paregorios** [comment]
FYI: It turns out this is blocking time-critical internal content publishing (new employee/student guide) ahead of this coming Monday's orientation.

**Comment by alecpm** [comment]
It looks like the intranet policy is not using the custom ISAW intranet workflow, but is instead using the standard "Intranet/Extranet Workflow" for standard content, with "Intranet Workflow for Folders" for Folders and Collections (which is a limited two state workflow with a badly named "internal daft" state), and no custom workflow for other add-on/custom content.  That shouldn't be the case, but it appears this was never customized.

I propose we create a new policy, ISAW Intranet Policy, which uses ISAW intranet workflow for all content types.  We can export that and include it in the policy profile.  That will require manually changing the workflow policy for any existing intranet folders.

**Comment by alecpm** [comment]
Do you want a simplified (non-reviewed) workflow for folders in the intranet, similar to the "Intranet Workflow for Folders" or the "Folder Workflow"?  Do you want to be able to publish folders in the intranet externally?

**Comment by paregorios** [comment]
To the degree that I understand this, we want our custom workflow to be
uniformly applicable to all content in the sub tree to which it is
assigned. Folders treated same as everything else so:  draft, pending,
internally published, externally published.

Sent from aboard the Liveware Problem.

On Aug 27, 2015, at 4:47 PM, Alec Mitchell <notifications@github.com> wrote:

It looks like the intranet policy is not using the custom ISAW intranet
workflow, but is instead using the standard "Intranet/Extranet Workflow"
for standard content, with "Intranet Workflow for Folders" for Folders and
Collections (which is a limited two state workflow with a badly named
"internal daft" state), and no custom workflow for other add-on/custom
content. That shouldn't be the case, but it appears this was never
customized.

I propose we create a new policy, ISAW Intranet Policy, which uses ISAW
intranet workflow for all content types. We can export that and include it
in the policy profile. That will require manually changing the workflow
policy for any existing intranet folders.

—
Reply to this email directly or view it on GitHub
<https://github.com/isawnyu/isaw.web/issues/42#issuecomment-135564992>.

**Comment by alecpm** [comment]
OK, try out the new ISAW Intranet Policy here https://isaw.nyu.edu/permission-tests/intranet-workflow-tests/foo/ and let me know if it does what you expect.

**Comment by paregorios** [comment]
Yes, these are the states and transitions that we need. I've tested with this item and also with ```/permission-tests/intranet-workflow-tests/new-folder-test``` and a subordinate folder. 

We have one further challenge, which only came into clear focus today: we need to be able to limit viewability for items in under the "isaw intranet workflow" that are in the "internally published state" to particular groups of users. Right now it looks to me (naturally enough) like anything in ```isaw-intranet:internally-published``` is viewable by all authenticated users. We would like the default for anything in ```isaw-intranet:internally-published``` to not be visible by authenticated users. One would need either global "can view" or local/inherited "can view" via the Sharing tab. By contrast, items in ```isaw-intranet:externally-published" are doing exactly what we want them to do as is.

**Comment by alecpm** [comment]
I've implemented this change, but I do have a couple questions about it.  This request seems to contradict item 1 on #49.  Also, if "Internally Published" is only visible to those with "Can Read" isn't it effectively identical to "Draft" and "Pending", except with more restrictive editing permissions?

**Comment by paregorios** [comment]
Will test but blocked for resolution of latest problems with #40.

**Comment by paregorios** [comment]
I am closing this ticket as resolved; however, I may be opening a new ticket with regard to the question @alecpm asked above about restricting viewability of arbitrary internally published items to arbitrary groups of authenticated users. Since the last development iteration on this workflow, the requirement for selective viewability has been walked back.
