### ISSUE TITLE
Tiled listing fails to show lead images for batches of items beyond first

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#422]
It works great on [the news blog](https://isaw.nyu.edu/news) and on [the library blog](https://isaw.nyu.edu/library/blog), but not on [the newsletters page](https://isaw.nyu.edu/publications/newsletters). Does this have something to do with the fact that the showcased content on the blogs consists entirely of news items, but the showcased content on the newsletter pages is folders and files?

**Comment by paregorios** [comment]
In the newsletter section, the first batch of content has img src attributes like:

```https://isaw.nyu.edu/publications/newsletters/021/@@images/7937ea04-87ef-4d9d-b107-488d5bb1de43.png
```

But in subsequent batches the non-working ones look like:

```
https://isaw.nyu.edu/publications/newsletters/isaw-newsletter-17-winter-2017/@@images/image/blogtile
```

**Comment by paregorios** [comment]
One finds the same difference in URL constructs on the news blog, but there they work.

**Comment by paregorios** [comment]
FWIW the "folder_leadimage_view" we have doesn't seem to work at all.

**Comment by paregorios** [comment]
I've poked around in the code for the various views that, one way or another, make use of lead image. I've poked around the web and plone documentation for guidance. I've fiddled with view customization. I don't know what the problem is.

**Comment by alecpm** [comment]
Should be fixed
