### ISSUE TITLE
news page does not update reliably to show newly published news items

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#43]
caching?

**Comment by paregorios** [comment]
this may be fixed; check

**Comment by paregorios** [comment]
Review and prioritization is blocked for testing on staging.

**Comment by k2soule** [comment]
even after clearing my browser cache, closing the browser, and re-launching it, I can't see the changes I've made to a published news item. In this case, Lorenzo's excavation.

**Comment by paregorios** [comment]
There is definitely something wonky going on on staging. I visited the news page in an anonymous tab. In another tab, I authenticated and created and published a new news item. I went back to the anonymous tab and reloaded. I saw the new item in the tiled listing as expected. Back in the authenticated tab, I edited the news item I had just published (modified the summary). I went back to the anonymous window, hit reload, and the new news item completed disappeared from the view. I tried a couple of times. After writing up this ticket comment, I went back to the anonymous tab and hit reload again. Magically, the new news item reappeared in the tile listing, complete with my most recent summary edits.

Varnish rules?

**Comment by paregorios** [comment]
We will have to watch for this behavior on production.

**Comment by k2soule** [comment]
Still seeing this behavior, and not just in /news. Not being able to see one's most recent changes is starting to confuse Marc and Maggie.

**Comment by paregorios** [comment]
Investigate caching policy for folders and for collections.

**Comment by paregorios** [comment]
this is a duplicate for #39
