### ISSUE TITLE
plugin for finding broken links?: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#433]
IIRC years ago we had a plugin product, which I never understood very well, that purported to be able to scour the site for broken links. Does it or a replacement still exist and work well (with a path for Plone 5)? If so, we could use it.

**Comment by jessesnyder** [comment]
When I run the linkcheck process, I get an error which appears to be due to an API mismatch with the version of the `requests` library:
```
2022-04-29 13:38:15 INFO linkcheck.processor looking for sites...
Traceback (most recent call last):
  File "/Users/jesses/projects/plone/isaw/parts/client2/bin/interpreter", line 366, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/jesses/projects/plone/.buildout/eggs/collective.linkcheck-1.2-py2.7.egg/collective/linkcheck/processor.py", line 46, in run
    session = requests.Session(timeout=5)
TypeError: __init__() got an unexpected keyword argument 'timeout'
```
Looking into when this API changed (it is the current version of `requests` which doesn't take kw args).

**Comment by paregorios** [comment]
Based on most recent comment, this ticket apparently needs to be re-estimated. It was previously rated a two-pointer, but I'm removing that designation ahead of planning poker.

**Comment by jessesnyder** [comment]
Inexplicably, I'm now getting a different error, without having made any changes to `collective.linkcheck`:
```
2023-03-14 20:19:31 INFO linkcheck.processor looking for sites...
2023-03-14 20:19:31 INFO linkcheck.processor found site 'isaw'.
Traceback (most recent call last):
  File "/Users/jesses/projects/plone/isaw/parts/client1/bin/interpreter", line 377, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/jesses/projects/plone/isaw/src/collective.linkcheck/src/collective/linkcheck/processor.py", line 181, in run
    registry = api.portal.get_tool('portal_registry')
  File "<string>", line 2, in get_tool
  File "/Users/jesses/projects/plone/.buildout/eggs/plone.api-1.2.1-py2.7.egg/plone/api/validation.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "/Users/jesses/projects/plone/.buildout/eggs/plone.api-1.2.1-py2.7.egg/plone/api/portal.py", line 88, in get_tool
    return getToolByName(get(), name)
  File "/Users/jesses/projects/plone/.buildout/eggs/plone.api-1.2.1-py2.7.egg/plone/api/portal.py", line 52, in get
    "Unable to get the portal object. More info on "
plone.api.exc.CannotGetPortalError: Unable to get the portal object. More info on https://ploneapi.readthedocs.org/en/latest/api/exceptions.html#plone.api.exc.CannotGetPortalError
```

**Comment by jessesnyder** [comment]
Solved by running the run script with the `-O` option:
```
bin/client1 -O isaw linkcheck
```

**Comment by jessesnyder** [comment]
Package is installed on staging, and the required helper process is running in the foreground:
```
$ sudo -u plone_buildout bin/client1 -O isaw linkcheck
```

Hoping this is enough to evaluate the basics. To deploy, we will need to set up another zeoclient under supervisor in Ansible with some possible re-balancing of resources for the other zeoclients.

**Comment by jessesnyder** [comment]
Accessible via control panel:


![Image](https://user-images.githubusercontent.com/63560/225401153-051f65fe-cd55-47a3-9f77-0c431acf1b1f.png)

**Comment by paregorios** [comment]
@jessesnyder functionality on staging meets my expectations. Please move forward in the direction of deployment to production.

**Comment by skleinfeldt** [comment]
I moved it to Approved for Merge, hoping that's the right place.

**Comment by jessesnyder** [comment]
@alecpm I'll need your guidance on how to integrate this into the ISAW world. I'm guessing we'll want:
1. a dedicated zeoclient
2. managed by supervisor
3. with different config than the standard instances (does it need blobstorage?, different cache size?)
4. and do other zeoclients need to give up some resources to compensate?

**Comment by alecpm** [comment]
I think the config can mostly be the same (just a single thread a lower object-cache size is probably fine). The docs have some suggestion of using a ZODB mount point, I guess to reduce ZEO traffic and perhaps conflict errors, but I really doubt that optimization would help much of anything as those aren't usually a bottleneck. I think it's likely we'll need to either reduce the number of running zeo clients or reduce the object-cache size for those clients and lower the RAM cap on the auto-restart script to ensure that the server doesn't run out of RAM.

**Comment by jessesnyder** [comment]
@paregorios Does it make sense for this thing to run all the time, or could this be a fire-it-up-every-x-months kind of thing?

**Comment by paregorios** [comment]
@jessesnyder honestly, I think a scenario in which we start up and use this thing periodically (say, quarterly) would work well for us. If that implies running something at the command-line on the server, that's ok.
