### ISSUE TITLE
"OK" button disappears on some tabs of the "insert/edit link" dialog box: 5pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#435]
This has been observed by both admin users in both chrome and firefox. To reproduce, try to add a link to some text in a rich text field via tinymce and then toggle back and forth between the tabs, looking for the ok button.

**Comment by silviot** [comment]
@paregorios I deployed a fix to staging. To test it you'll need to either
* use an incognito window
* have your dev tools open when you click the "link" button in TinyMCE
* wait one day (86400 seconds)

**Comment by paregorios** [comment]
I cannot provoke the bug on staging now using the same general technique that I can use to provoke it on production. So, let's merge and deploy to production1

**Comment by paregorios** [comment]
I have moved this ticket to "merge for deploy" on the project board.

**Comment by paregorios** [comment]
Was this ticket merged and deployed, or will we wait till the next support funding interval?

**Comment by paregorios** [comment]
This is working on prodo
