### ISSUE TITLE
"Event Listing" is not showing all content

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#437]
This is affecting the "display item" (a collection) in every subfolder of [the "Past Events" section (aka "Events Archive")](https://isaw.nyu.edu/events/archive). For example, https://isaw.nyu.edu/events/archive/2020/index should show us all 25 published "event" content items in the /events/archive/2020 folder, but instead we only get 12 items and clicking on the "View More" affordance at the bottom of the page fails to add more items to the view. This error is new to us, but we are unsure when it started happening. We have high confidence that it was not a problem in September 2021 when the archive was last updated.

## Steps to reproduce:

- Log into the website.
- Visit the Events Archive and select (click through) to any academic year subfolder (ignore Recent Events for now).
- Select "contents" tab on the green tertiary menu bar (i.e., go to ./folder_contents).
- Select the content item with the red dot next to its title in the table (i.e., the selected "display item" for this folder). 
- Count the number of content items appearing in the listing (clicking "View More" at the bottom as necessary, though that is not working for us).
- Click "display" on the green, tertiary menu bar and select "Title-only Listing" (**NOTE: this changes the live, public view**).
- Note the much longer list of events.
- **IMPORTANT:** Click "display" on the green, tertiary menu bar and select "Event Listing" to put the listing back to user-expected settings.

**Comment by alecpm** [comment]
@paregorios This is interesting. It seems like different instances may be running different code. If I log in and visit the AJAX url for the second page of results:

https://isaw.nyu.edu/events/archive/2020/index/@@event-listing-page?page=2

I sometimes get a result list, and I sometimes (about half the time) get this traceback:
```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module five.customerize.zpt, line 83, in __call__
Module Products.PageTemplates.ZopePageTemplate, line 338, in _exec
Module Products.PageTemplates.ZopePageTemplate, line 435, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 821, in do_loop_tal
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 620, in do_insertText_tal
Module Products.PageTemplates.Expressions, line 225, in evaluateText
Module zope.tales.tales, line 696, in evaluate
URL: /isaw/events/archive/2020/index/zope.interface.interface-event-listing-page
Line 5, Column 6
Expression: <PythonExpr view.format_date(item.start)>
Names:
{'container': <Collection at /isaw/events/archive/2020/index>,
 'context': <Collection at /isaw/events/archive/2020/index>,
 'default': <object object at 0x7fcfd5bb07f0>,
 'here': <Collection at /isaw/events/archive/2020/index>,
 'loop': {u'item': <Products.PageTemplates.Expressions.PathIterator object at 0x7fcfbaa90450>},
 'nothing': None,
 'options': {'args': ()},
 'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fcf8a999890>,
 'request': <HTTPRequest, URL=https://isaw.nyu.edu/events/archive/2020/index/@@event-listing-page>,
 'root': <Application at >,
 'template': <TTWViewTemplate at /isaw/events/archive/2020/index/zope.interface.interface-event-listing-page>,
 'user': <PropertiedUser 'alecpm'>,
 'view': <five.customerize.zpt.TTWView object at 0x7fcf93297dd0>}
Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
__traceback_info__: view.format_date(item.start)
Module PythonExpr, line 1, in <expression>
AttributeError: 'TTWView' object has no attribute 'format_date'
```

Taking a look at the code now to see what might be the culprit here.

**Comment by alecpm** [comment]
Looks like the `EventListingView` has a `format_date` method but for some reason the generated `TTWView` created by the TTW template customization isn't pulling that in as a base class. It's probably best to delete that template customization after ensuring that any desirable changes it includes are merged into the original template `isaw.theme.browser.templates.list_events.pt`.

**Comment by alecpm** [comment]
I think this is complete. All of the template changes were moved to the git codebase and the TTW customizations were removed. The ansible config and buildout appear to be up to date and running well.
