### ISSUE TITLE
permissions: "can edit" doesn't seem to imply "can add*

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#44]
We have created some groups for managing content in (e.g.) the news blog. They are "News Writers" and "News Editors". We have given the writers "can add" via the "sharing" tab on /news and have given the editors "can edit". 

**As expected:**
 * **writers** can navigate to /news, add a content item, and then edit it subsequently. 
 * **writers** are not able to edit content items created by others, but **editors** can
 * **writers** cannot submit their own content for review.

**Unexpected:**
 * **editors** cannot navigate to /news, add a content item, and then edit it subsequently

In previous conversation with @alecpm I thought he'd said that giving a user or group "can edit" via sharing would automatically also give them "can add". I'm not seeing that effect. Did I misunderstand the comment, or just dream it up?

**Comment by alecpm** [comment]
Editors can edit, but not add.  Contributors can add, but not edit (anything except the content they created).  You want to give your Editor group both the Editor and Contributor roles (Can Edit and Can Add), if you want them to be able to create content.  Alternatively, we could change the default site permissions for the global Editor role to include the various Add permissions.

**Comment by paregorios** [comment]
@alecpm evidently I misunderstood previously. The first solution you suggest -- giving them both "can edit" and "can add" is fine and that's what we'll do. I just wanted to make sure I wasn't missing something. Thanks.
