### ISSUE TITLE
exhibition object displays empty "description" field: 2pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#441]
There is a field on the custom exhibition object content type that gets labeled "description" (not its schema name) in the default view. That label shows up even when the field is empty. We would like for it to have the same behavior as other fields on this object: it is not displayed if the field is empty.

**Comment by paregorios** [comment]
In the edit view on the object, the field in question is called "Title Detail".

**Comment by paregorios** [comment]
Here's a screen shot showing the undesirable
![Screen Shot 2022-08-30 at 5 21 41 PM](https://user-images.githubusercontent.com/263285/187553998-28dbeb58-e227-460d-a341-c5c5fc863007.png)
 behavior:

**Comment by paregorios** [comment]
Production is currently running a through-the-ZMI view template customization that does what we want:

```
isaw.exhibitions.interfaces.IExhibitionObject: view (zope.publisher.interfaces.browser.IDefaultBrowserLayer)
```

We would like this change moved to code, the view customization removed, and the new code rolled out on production.

**Comment by silviot** [comment]
Deployed to staging.

**Comment by paregorios** [comment]
@silviot this looks good to me on staging, both with respect to the behavior of the object view through the plone and also the removal of the view customization in ZMI. I would be happy to see this merged to master and deployed to production once any pending PRs are complete.

**Comment by paregorios** [comment]
Looks great on production (I removed the template customization).
