### ISSUE TITLE
news item type does not work uniformly with lead image view: 1pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#443]
Consider this folder, which has "lead image view" applied via the actions toolbar > display > lead image view: https://isaw.nyu.edu/members/te20-40nyu.edu/lead-image-testing

# Undesireable appearance (byline/dateline is appearing along with summary)

![Screen Shot 2022-11-01 at 1 22 33 PM](https://user-images.githubusercontent.com/263285/199311324-bb06bb46-6a0e-4580-bff8-a501f7d53279.png)

# Desired appearance

![newsitem](https://user-images.githubusercontent.com/263285/199312182-29d20ee2-b1b6-4660-b592-02e7c1c06968.png)

# Explanation

- Suppress the byline/dateline in "lead image view" (note: DO NOT suppress byline/dateline on any other view that we use)
- Adjust spacing in CSS if needed to make sure the news item summary is spaced vertically just like the other summaries in this view.

**Comment by silviot** [comment]
Visible [on staging](https://isaw.jazkarta.com/members/te20-40nyu.edu/lead-image-testing/).

**Comment by paregorios** [comment]
This is working on production, thanks!
