### ISSUE TITLE
make the "Collection Portlet" just like the fixed "related items" portlet: 2pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#445]
We would like the "Collection Portlet" to produce output indistinguishable from the output produced by the "related items" portlet once it is fixed per #444. [See example page here](https://isaw.nyu.edu/skunkworks/portlet-experiments/page-for-collection).

We think there are only two necessary changes:

1. Include content-item "description" text as specified in #444 for items returned by the referenced collection that have it.
2. Produce accessibility-and-CSS-friendly HTML as specified in #444.

**Comment by alecpm** [comment]
I included some CSS changes that should have addressed those issues, but they don't seem to be live. Weird.

**Comment by alecpm** [comment]
@paregorios Should be looking better now after a CSS registry refresh and a couple more CSS tweaks.

**Comment by paregorios** [comment]
Perfect on Production(TM)
