### ISSUE TITLE
create new "summary view (alt)" listing: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#449]
As a user with appropriate permissions I will be able to apply a new "summary view (alt)" that looks like this:

- No images are used
- Bylines from content are not displayed
- No "read more" links
- Titles are vertically left-aligned
- Summaries are vertically left-aligned
- Entire line is clickable as a single link and has mouseover style to match our main menu behavior (i.e., blue outline on hover)
   - Title is underlined in standard appearance for links with href and changes to blue dashed underlining when any part of the line is moused over
   - Summary text, even though it is part of the big link, is not underlined

For the underlying HTML, we would prefer an unordered list be used, rather than a table, with CSS providing the formatting. This is an accessibility concern.

##Other style considerations:

- Long titles must wrap within the apparent visual title column
- Long summaries must wrap within the apparent visual title column
- Summary text must be top-aligned with the corresponding title
- All text is left-aligned within its block
- No pagination

![summary](https://user-images.githubusercontent.com/263285/200365738-5c78b281-595d-4629-bd3e-8056d83c946a.jpeg)

## For mobile

Drop the two-column look and instead format like the standard summary listing:

- **Title**
- Summary

but omit bylines, lead/news/profile images, read more links.

**Comment by alecpm** [comment]
@paregorios This is up for review [here](https://isaw.jazkarta.com/news/collector/@@simple-summary-listing) and also avaliable as `Summary View (alt)` in the display menu on Folders, Collections, and Topics.

**Comment by paregorios** [comment]
This is beautiful @alecpm. Please merge and deploy.

**Comment by paregorios** [comment]
@alecpm like #448, I am attempting to test this functionality on production at https://isaw.nyu.edu/skunkworks/financial-resources, but I do not see the new display listing available on the actions menu. This is after fully dumping cache in my browser and performing a new login.

**Comment by alecpm** [comment]
Should be there now, needed to run an upgrade step.

**Comment by paregorios** [comment]
Looks great!
