### ISSUE TITLE
permissions: "can edit" doesn't include "can submit"

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#45]
See the groups setup description in #44.

We would like our "news editors" to be able to submit any draft item in /news for review, but giving them "can edit" via sharing doesn't confer this ability. Giving them "can review" makes it possible not only for them to submit for review, but to publish. We do not want them to be able to publish.

Can this be modified?

**Comment by paregorios** [comment]
Is there by chance a quick "you are doing it wrong" answer that can be given on this question without doing a bunch of work? @alecpm @skleinfeldt

**Comment by skleinfeldt** [comment]
It sounds to me like there is a flaw in the workflow (it's a custom WF right? The default Plone WF allows editors to submit for review.) A quick glance at the code would confirm this, which you can probably do, that code is pretty obvious.

**Comment by alecpm** [comment]
If you want Editors to be able to submit content written by others regardless of the workflow in place, then we'll want to change the global assignment for the "Request review" permission (this permission is also not managed via WF by default).

**Comment by paregorios** [comment]
Thanks. I will refactor this ticket to make it a request for the intervention suggested by @alecpm

**Comment by alecpm** [comment]
Hm, it appears the Editor role already has the "Request review" permission that is required by the isaw_standard_workflow to "submit" content.  It's both set on the site and in the profile, so this is a bit mysterious.  Could you point me to a specific piece of content where you've seen this problem, so that I can check the local permissions?

**Comment by paregorios** [comment]
The issue addressed in this ticket has been subsumed into and superseded by nos. #48 and #49. Therefore I am closing this ticket as "duplicate"; however, I will put a back reference from those newer tickets because of the discussion above from @alecpm about the ```Editor``` role and "Request review" permission.
