### ISSUE TITLE
ensure isaw4staging is ready for March 2023 iteration

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#460]
- [x] ensure OS and server package updates match production isaw4 (**close enough**)
- [x] ensure all staging branches at github are up-to-date vs. production branches and that these are cleanly deployed on isaw4staging
- [x] copy production zope database and blob storage from isaw4 to isaw4staging

**Comment by alecpm** [comment]
Production could use a reboot for a kernel update to match staging, but the code and OS/package versions are all identical and up to date. I'm starting the data sync now.

**Comment by alecpm** [comment]
isaw4 is currently running on Ubuntu 18.04. It may be worth considering the (free for non-commercial use up to 5 servers) [Ubuntu Pro with Extended Security Maintenance](https://discourse.ubuntu.com/t/ubuntu-pro-faq/34042), which provides additional package security updates. ISAW currently uses a few packages (including `fail2ban` and `python-pip`) which have additional security updates available via the ESM channel.

**Comment by paregorios** [comment]
@alecpm should we create a separate ticket for discovery and decision-making around Ubuntu Pro with Extended Security Maintenance?

**Comment by alecpm** [comment]
Probably a good idea. Getting OS vendor Python 2 updates would probably be wise until we're ready to go to Plone 5.2 + Python 3.

**Comment by paregorios** [comment]
Now that [the ticket for Ubuntu Pro ESM](https://github.com/isawnyu/isaw.web/issues/463) has been created, I am closing this ticket as complete.
