### ISSUE TITLE
upgrade GA on isaw production to GA4

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#467]
in slack @skleinfeldt said:

> we should set up GA4 next week so it can run in parallel with classic analytics before that is discontinued in July

**Comment by alecpm** [comment]
@paregorios Would it be possible to grant me (alecpm@gmail.com) access to the ISAW analytics account? If you have a Google Tag Manager account it would be great to have access to that as well. If you don't have Google Tag Manager, I do recommend setting it up and doing the integration from there, if possible.

**Comment by alecpm** [comment]
@paregorios I've installed the GTM container with both Universal Analytics and GA4 tags on https://isaw.jazkarta.com/.

You should be able to use https://tagassistant.google.com/ to visit that url and see the tags firing. You should also see [realtime data in the GA4 property](https://analytics.google.com/analytics/web/#/p361644700/realtime/overview) while visiting the staging site. Right now I'm seeing a little more traffic than I'd expect for the staging site.

**Comment by paregorios** [comment]
@alecpm we do seem to have continued collecting data. What else/next needs to be done on this task?

**Comment by alecpm** [comment]
This is now live on production.

**Comment by paregorios** [comment]
@alecpm I do not know how to test this to verify everything is working on the GA interface side, but I'm going to assume it's fine and close as complete. I do see data in a "property" titled "ISAW Website - G4" (361644700), but I don't know how to examine details for that property like what server IP it is actually monitoring.

**Comment by alecpm** [comment]
@paregorios One thing worth looking at (may be Chrome only) is https://tagassistant.google.com/ which will let you inspect the Google tags at a given site and see what triggers as you browse around. When I look at https://isaw.nyu.edu/ in the Tag Assistant I see the following tags:

`GTM-P23QDZX` (The GTM Tag), `G-7CGT1Q8SSY` (The GA4 Tag loaded by the GTM tag)

On the "Container Loaded" event the following GTM tags are fired:

`GA4 Analytics`, `Universal Analytics Page View`

After those are fired the `Config` event fires the `Page View` event in your GA4 tag. That all looks correct to me, so I think we're good to go.
