### ISSUE TITLE
add collection body text to "Summary View (alt)" 2 pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#468]
One of the available display views for Folders and Collections is our custom "Summary View (alt)". It currently provides the desired view for all visible items inside the folder or collection to which it is applied; however, if applied to a Collection, the Body Text field on the Collection is suppressed. 

Remedy: When applied to a Collection object, the Summary View (alt) must display any Body Text in the collection as rich text between the closing `</h1>` tag and the list of subordinate content items. The body text should be displayed exactly as it would be in a Page content item.

**Comment by alecpm** [comment]
This is on staging for review see e.g. [here](https://isaw.jazkarta.com/publications/all/simple-summary-listing).

**Comment by paregorios** [comment]
This looks great! Please merge to master, deploy to production, do a victory dance, etc.

**Comment by paregorios** [comment]
@alecpm it looks like this has been deployed to production. Is this ticket ready to close in your view?
