### ISSUE TITLE
verify no need and remove addon: SAML2 1.0

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#488]
This addon is currently `available` but `inactive` in our 4.3 build.

Is anything in this addon actually being used somehow? If not, we should get rid of it so it doesn't confuse things in the future.

**Comment by alecpm** [comment]
This is required for SSO, and cannot be removed. It does not need to be installed in the site for its functionality to be used/available. The default installation is not necessary/useful for ISAW's SAML SSO setup.

**Comment by paregorios** [comment]
No action. closing ticket.
