### ISSUE TITLE
Fix README.txt documentation

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#50]
Bring the isaw.web/README.txt up to date, including what branches are being used etc. Add documentation about production and staging - how to deploy new code, how to restart, etc. (You can take much of this from Tom's text file plus clarifying when to use sudo and when not to, and add info on using the upstart supervisor service.)

**Comment by alecpm** [comment]
The HOSTING.txt and README.txt have been updated.

**Comment by skleinfeldt** [comment]
@alecpm the README.txt looks good.

In HOSTING.txt a few things to fix:

Lines 15, 19, 27,28 are confusing. The README said we needed Python 2.7, why are we talking about 2.6 and Plone < 4.3? 

Fix discrepancy between line 24 and lines 31-34. And don't make it either/or, choose the one we are using.

Line 78 should that really be "get"?

Lines 95 to the end, what is the idea here, what are we syncing to? staging? Explain the context please.

**Comment by paregorios** [comment]
status?

**Comment by skleinfeldt** [comment]
I believe nothing has happened since my comments on Sept 14. Take a look and if you agree with me, we can reassign to Alec to fix.

**Comment by paregorios** [comment]
concur. I'm removing review tag. Please assign for completion in accordance with priority tags.

**Comment by alecpm** [comment]
Updated.

**Comment by paregorios** [comment]
Closing resolved.
