### ISSUE TITLE
migrate/replace active addons: Related Items 0.3.9 and Relation Field 1.2.3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#512]
I assume that these two `active` addons are needed, but I don't know how to trace the dependencies. 

## Question

- [ ] How do we find the dependencies for these addons in order to determine what we need to do to make sure functionality works in 5.1?

**Comment by alecpm** [comment]
These are Plone core functionality and should be handled automatically as part of the upgrade to Plone 5.1.

**Comment by paregorios** [comment]
No independent action required. Closing.
