### ISSUE TITLE
What is the purpose of addon: Session refresh support 3.5.6

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#514]
This addon is currently `active` in our 4.3 build.

What is the purpose of this addon? Are we currently making use of its functionality it any way? If not, what is the potential impact to removing it from our build and/or keeping it out of our Plone 5.1 build?

**Comment by alecpm** [comment]
This is a core part of Plone and can be retained, it is the install name of `plone.session`, which provides configurable user session support.

**Comment by paregorios** [comment]
@alecpm am I correct then in thinking there's no independent work to be done on this because it will be handled simply by the migration and therefore we can close this ticket?

**Comment by alecpm** [comment]
Correct

**Comment by paregorios** [comment]
nothing to do here. Move along.
