### ISSUE TITLE
Do we need active addon: Static resource storage 1.2.3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#515]
This addon is currently `active` in our 4.3 build. Are we actually using it and if so where?

What is the purpose of this addon? Are we currently making use of its functionality it any way? If not, what is the potential impact to removing it from our build and/or keeping it out of our Plone 5.1 build?

**Comment by alecpm** [comment]
I believe this will be taken care of automatically during the upgrade/install process for Plone 5.1

**Comment by paregorios** [comment]
No action required. Closing.
