### ISSUE TITLE
upgrade/replace addon for Plone 5: Workflow Policy Support (CMFPlacefulWorkflow) 1.5.15

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#517]
This addon is `active` in our current build.

We use placeful workflow. We will need it in 5.1, with all current permissions, groups, roles, etc. properly migrated and functioning. What to do?

**Comment by alecpm** [comment]
This is part of core Plone and will be upgraded automatically,

**Comment by paregorios** [comment]
Nothing else needs to be done.
