### ISSUE TITLE
upgrade/replace for Plone 5:  Working Copy Support (Iterate) 2.1.18

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#518]
This addon is currently `active` in our build. We use working copy support extensively, and will need it to work in 5.1.

**Comment by paregorios** [comment]
@alecpm have we incorporated into 5.1 buildout or whatever the "explicit enablement" for this addon? If so, can this ticket be closed?

**Comment by alecpm** [comment]
Since it’s already enabled, it should continue to be enabled. @paregorios Do you have thoughts on whether you want to attempt to preserve versions/working copies during the type migration? I would recommend against it.

**Comment by paregorios** [comment]
So this will be a ticket for me to clear out working copies throughout the site before we do the final migration. 

@alecpm if there are working copies hanging around at migration, and we choose not to preserve them, will there be any weird stuff brought forward or funky database conditions? i.e., do we have to find and purge them all, or can we just let them get trashed during the migration?

I have no problem dumping versions.

**Comment by alecpm** [comment]
I think we can choose to dump versions, keeping them around can cause issues because they will have the wrong underlying class. It's probably best to manually remove any working copies floating around before final migration. I don't believe there's a process for handling those automatically. @sauzher does that sound right to you?

**Comment by paregorios** [comment]
I am closing this ticket as resolved. I will create a new ticket for myself to hunt down and eliminate derelict working copies from the database prior to final migration to 5.1.
