### ISSUE TITLE
layout oddities in event page

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#52]
I'm discovering some problems in the layout of events (individual event display), now that we're adding new events and including images. The lead image for an event is showing up in an odd place; in the same div with the subtitle, and very small. If we include a caption, it gets even stranger. The caption takes up much more lateral room than the image, and shoves the image over (squishing the subtitle).

When I went looking for the original design spec for event display, I couldn't find the most recent layout - however, I feel like we intended the lead image to show up as the top portlet... above the Event Details block. I could be mis-remembering. In any case, we need to have another look at the styling.

**Comment by k2soule** [comment]
As an example, take a look at this working copy of a new event item: 
https://isaw.nyu.edu/events/copy_of_levy-lecture-scythian-burials

**Comment by paregorios** [comment]
Yeah, that’s screwed up. Sigh.

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
Can you transfer this ticket to isaw.theme and assign to me? Thanks.

**Comment by k2soule** [comment]
done. closing this ticket.
