### ISSUE TITLE
verify no need and remove active addon: isaw.bibitems 0.1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#522]
The only `isaw.bibitems.bibitem` objects we have in the database are [test items in subfolders of my personal folder](https://isaw.nyu.edu/search?portal_type%3Alist=isaw.bibitems.bibitem), and they are all currently throwing errors like this when you try to view them in the browser:

```
AttributeError('image',) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: image)
```

Unless there is functionality provided by this addon that we actively use somewhere else besides in the `isaw.bibitems.bibitem` type, I would like to remove this addon and type from our build for 5.1, since nobody is using it. 

## Questions:

- [ ] Are there any active dependencies on this addon other than the `isaw.bibitems.bibitem` type?

**Comment by sauzher** [comment]
Product removed by the migration script and from the basecode in the plone51/52 branches

**Comment by paregorios** [comment]
@sauzher therefore ok to close this ticket?

**Comment by sauzher** [comment]
Found today elements like this one https://isaw.jazkarta.com/exhibitions/catalogues/a-wonder-to-behold. It is a isaw.policy.publication type, but its views depend from "isaw.bibitems.browser.view"

Need to revert those views

**Comment by paregorios** [comment]
assigning to myself to test
