### ISSUE TITLE
do we need active addon: plone.app.intid: install utility 1.0.5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#526]
What is the purpose of this addon? Are we currently making use of its functionality it any way? If not, what is the potential impact to removing it from our build and/or keeping it out of our Plone 5.1 build?

**Comment by alecpm** [comment]
This is necessary for DX relation/reference support will be retained with the upgrade. It is part of core Plone.

**Comment by paregorios** [comment]
Nothing manual to do here. Closing.
