### ISSUE TITLE
cropping option missing from multiple content types (events, pages, possibly more)

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#53]
When editing an Event Item with a lead image, I don't have the Cropping option to adjust cropping settings for that lead image (the way that it's an option for news items).

**Comment by paregorios** [comment]
This also happens with page items.

**Comment by skleinfeldt** [comment]
For you @alecpm

**Comment by skleinfeldt** [comment]
Unfortunately we don't have enough time left to take this one, reassigning to @paregorios

**Comment by paregorios** [comment]
not a director's issue

**Comment by cewing** [comment]
@paregorios this is ready for review on staging.  The missing types which supported lead images but do not have image cropping enabled were the page, event, folder and collection type.  All should now have image cropping enabled.  

Please be aware that the types selected for having lead images are not automatically granted the cropping ability.  If you make changes in the future to what types have lead images, you will want to review the code changes made here to see how to enable the cropping tab.

**Comment by paregorios** [comment]
Great! Reassigning this to @k2soule for review.

**Comment by k2soule** [comment]
Looks good to me on staging.

**Comment by k2soule** [comment]
Changing to deploy...

**Comment by paregorios** [comment]
please deploy to production at your leisure

**Comment by k2soule** [comment]
Looks good on production. Closing ticket.
