### ISSUE TITLE
Dump a list of all URIs in links in the database

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#535]
In order to perform various content review and improvement activities, we need to be able to dump a list of all URIs in content in the database. This includes all URIs in fields designated for the purpose (e.g., in "Link" content items), as well as all URIs found in `href` attribute values on `a` elements in HTML in any field. Ideal output format would be CSV, with columns for the URI, context path, field name, HTML `a` text value (if any). A command-line script run on the server would be a fine solution for this, as only admins will need to be able to perform this function.

**Comment by alecpm** [comment]
Here's the CSV: [urls.csv.gz](https://github.com/user-attachments/files/18029601/urls.csv.gz)

There's now a script in `/scripts/dump_urls.py` which you can run with `bin/client1 run scripts/dump_urls.py --site isaw urls.csv` to output all non-internal urls.

**Comment by paregorios** [comment]
@alecpm The CSV contains exactly what I needed and I was able to run the script on production without difficulty. If there's anything that still needs to be done in terms of merges etc. to make this a permanent part of `isaw.web`, please go ahead and then let me know when this issue can be closed as "resolved". Thanks.

**Comment by alecpm** [comment]
Since it's standalone I just worked from master, so we should be all set. Ready to close.
