### ISSUE TITLE
intermittent 502 and 503 errors

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#536]
Normally when they occur another user (or the same user with a different browser) can logon and perform the same operation without difficulty (perhaps they’re getting a different backend instance?). We’ve never been able to get the problem to repeat for the same action. In any case, the user having once experienced the problem will continue to see the error message for that particular content item interaction for days if the problem is unaddressed. The only solution we have found is to delete “cookies and other site data” for whatever most recent time period includes the first moment the error was thrown and after that everything is fine.

See one example for which we have an open ticket still: #423 

There was a long discussion about this problem in the Jazkarta slack, nyu-client channel on 4 September 2024 that includes the following suggestions from @alecpm:
- Generally 502 and 503 errors are fixed by increasing timeouts on your front end servers (varnish, apache, haproxy).
- If the error were generated in Varnish I don’t think Varnish would ever cache it. Maybe if HAProxy generated it Varnish would cache it if poorly configured, but that should be easy to fix in the Varnish config (5xx responses should never be considered for caching).
- That would imply that the 5xx response is being sent with Cache-Control header other than no-cache or an Expires header set, which wouldn’t be great and we can probably fix somewhere in the stack.

Both @alecpm and David Glick recommended having our users capture screenshots and, if possible, "look in web inspector and look at the Network HTTP Response Headers". I have distributed this request to users, but we have received no reports in the intervening weeks.

**Comment by alecpm** [comment]
@paregorios I've pushed some changes to the varnish configuration on staging that should help prevent error responses (and other un-cacheable responses) from being cached. Additionally, I've increased the HAProxy timeout to match the Varnish timeout, which should help prevent some of these timeouts to begin with. These changes are up on staging, but since we don't know how to reproduce the problem it will be hard to test. It may be best to just test that caching stuff generally continues working as expected. The cache config changes are fairly significant, but they are identical to the caching config that will be used on the migrated server so there's a dual benefit to testing these changes now.

**Comment by paregorios** [comment]
A user has just reported a 503 error in the wild. Here's what they did:

- Saw a link to a draft news item in a slack channel and clicked on it: https://isaw.nyu.edu/news/isaw-graduate-conference-2025
- Their browser was already authenticated with NYU SSO, but they had not logged in with it to the ISAW website recently, so "when I clicked through the link, there was a momentary SSO screen that then logged in a second automatically, automatically reloaded, and this came up:"

![Slack 2024-10-03 10 31 59](https://github.com/user-attachments/assets/f24689e1-9dbc-4b14-bbc7-a1ca2fc084c1)

**Comment by paregorios** [comment]
@alecpm I have not spotted any unexpected behaviors on staging. Please merge and deploy these changes to production.

**Comment by alecpm** [comment]
@paregorios do you know if this 503 got cached (e.g. trying to view the same page resulted in the same 503 from then on)?

**Comment by paregorios** [comment]
@alecpm I do not know. Another senior member of staff accessed the content object, edited it, and checked it in.

**Comment by paregorios** [comment]
I'm going to close this ticket assuming changes we've deployed to production will address the problem. We can re-open it if the problem recurs.

**Comment by alecpm** [comment]
Changes have been deployed to prod
