### ISSUE TITLE
retracted to "drafting" people profiles remain publicly viewable in cache

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#537]
This morning I retracted a person profile to "drafting" state and informed the requestor I had done so. 40 minutes later a third party informed me that the profile was "still visible". I checked (authenticated) and the profile showed "draft". I checked (anonymous) and the profile was available. After manually purging the cache proxy, the anonymous view correctly stopped showing the profile. 

This is a significant liability and needs to be corrected ASAP.

**Comment by alecpm** [comment]
This should be fixed on staging. There were some issues with the cache purging configuration, but also there's apparently a known [Plone Issue](https://github.com/plone/plone.app.caching/issues/134) where workflow transitions don't result in cache purges. I've added a workaround for that, as well as TTW configuration fixes for cache purging. Additionally, I've made some updates to the varnish config (mostly for #536), which should help prevent un-cacheable responses from being cached.

**Comment by skleinfeldt** [comment]
@alecpm Would it make sense to contribute a PR to fix this in plone.app.caching? Would that be quick? @paregorios Would you be OK using ISAW time for that?

**Comment by paregorios** [comment]
Yes, I'd be fine with that if it's not additional huge.

**Comment by paregorios** [comment]
@alecpm this appears to be working well on staging. Please merge and deploy to production.

**Comment by paregorios** [comment]
This is working now on production.

**Comment by alecpm** [comment]
The fix was deployed, though not 37 minutes ago. Interesting.
