### ISSUE TITLE
event item contact info does not appear

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#54]
When the Name, Email and Phone fields are filled out in an Event Item, they don't appear anywhere for the visitor viewing the item.

**Comment by skleinfeldt** [comment]
For you @cguardia

**Comment by cguardia** [comment]
Pushed fix for this to master.

**Comment by skleinfeldt** [comment]
@cguardia please deploy this to staging so ISAW can review.

**Comment by cguardia** [comment]
Deployed to staging.

**Comment by skleinfeldt** [comment]
Over to @paregorios for review.

**Comment by paregorios** [comment]
This appears to be working on my local instance.

**Comment by paregorios** [comment]
this appears to be working in my local instance

**Comment by paregorios** [comment]
working
