### ISSUE TITLE
Missing Title as image caption in Page template

### ISSUE THREAD

**Issue by sauzher** [isawnyu/isaw.web#544]
https://isaw-migration.jazkarta.com/graduate-studies/admissions-and-financial-aid
migration:
![immagine](https://github.com/user-attachments/assets/605bf7fb-d61d-46f9-af64-a7c77e500d83)

production:
https://isaw.nyu.edu/graduate-studies/admissions-and-financial-aid

![immagine](https://github.com/user-attachments/assets/51d14922-ff04-41c1-8b28-0437b447e565)

**Comment by sauzher** [comment]
fixed with: https://github.com/isawnyu/isaw.web/commit/e7a40e17191b45a083c031d1905cd8196372a751

**Comment by paregorios** [comment]
@sauzher this caption is missing on `/graduate-studies/admissions-and-financial-aid` on 5.x. Re-opening issue.
