### ISSUE TITLE
Make workflow for profiles behave like workflow for Guide

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#546]
Presently, our user profiles in the `/people` container (and below) make use of our standard site-wide workflow (drafting -> pending -> published), but the content in `/guide` makes use of a more complex workflow, permitting an end state of either "published external" or "published internal". We would like to change the governing workflow for content in the `/people` container to match that currently used for the `/guide`.

**Comment by alecpm** [comment]
Should be working on production.

**Comment by paregorios** [comment]
This is working on production. Closing as resolved.
