### ISSUE TITLE
Page template renders Alt text for images / images showing unwanted bordeaux border

### ISSUE THREAD

**Issue by sauzher** [isawnyu/isaw.web#548]
https://isaw-migration.jazkarta.com/research/antikythera-mechanism
![immagine](https://github.com/user-attachments/assets/929237d6-e6b8-41f7-869f-767190d7bb5c)

In production:
https://isaw.nyu.edu/research/antikythera-mechanism
![immagine](https://github.com/user-attachments/assets/73a74ff7-114e-4217-9254-a18265665802)

May be we lost some related content during migration.

**Comment by paregorios** [comment]
This remains ok on 5.x staging, so ticket can remain closed.
