### ISSUE TITLE
Event type info not carrying through to Calendar View

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#55]
In the Calendar View of events, all event types are showing up with the same color instead of different colors for different event Types. The Types are selected by the content creators when creating and editing events; but that data is not being carried over to display on the calendar.
![isaw-09-calview](https://cloud.githubusercontent.com/assets/7882896/9914234/d7e7a39e-5c7e-11e5-9c2c-30040647de5e.jpg)

**Comment by paregorios** [comment]
closing won't fix
