### ISSUE TITLE
Get rid of webcouturier.dropdownmenu?

### ISSUE THREAD

**Issue by sauzher** [isawnyu/isaw.web#558]
Abandoned:
https://github.com/mishunov/webcouturier.dropdownmenu

Is it used in the portal?

I don't see it installed on staging nor it's referred into the basecode.

May this be removed?

@paregorios

**Comment by sauzher** [comment]
I was wrong.
There are references in the theme as an override 

[isaw/theme/browser/template-overrides/webcouturier.dropdownmenu.browser.dropdown_recurse-orig.pt
](https://github.com/isawnyu/isaw.web/blob/master/src/isaw.theme/isaw/theme/browser/template-overrides/webcouturier.dropdownmenu.browser.dropdown_recurse-orig.pt)

Still not sure if it's really needed.

**Comment by sauzher** [comment]
https://github.com/isawnyu/isaw.web/blob/8636e8c9a2e5f50fe1336fcf6f1b986e283188e9/src/isaw.theme/isaw/theme/profiles/default/skins.xml#L27

Here there is a clear removal intention, IMHO

**Comment by alecpm** [comment]
@sauzher As far as I can tell, we aren't using the add-on in the theme anymore (no obvious dropdown menus in top navigation). So we can probably just uninstall it and remove the browser layer. Dumbarton Oaks appears to be using the add-on under Python 3, so it's not a dealbreaker if we do need to retain it for some functionality.

**Comment by sauzher** [comment]
Thanks @alecpm, for what I see, in the case, perhaps there will be necessary to convert configlet from formlib  into a z3cform one.

**Comment by paregorios** [comment]
Product has been removed in migration scripts per @sauzher

**Comment by skleinfeldt** [comment]
What about this comment from @sauzher: "perhaps there will be necessary to convert configlet from formlib into a z3cform one."

**Comment by sauzher** [comment]
it means that in the case we want to use this product in 5.2 It will need to be adapted in some way. But it seems that's not the case, we just removed it in the migration. so this can be closed @skleinfeldt
