### ISSUE TITLE
check-in breaks the default view for a folder

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#56]
When a folder is set to display a particular content item as its default view, and that item is checked out + checked in (as per our workflow procedure), the folder reverts to "standard" view upon check-in. This creates a serious problem for editors, who have no way to edit a published file that acts as the default view of its container (without making a mess).

**Comment by skleinfeldt** [comment]
For you @cewing

**Comment by cewing** [comment]
@paregorios I can verify that the same behavior happens with a default installation of Plone.  I am investigating to discover why, but it appears to be an issue in the package that provides working copy support.  I'll keep you posted.

**Comment by cewing** [comment]
@alecpm please mark reviewing after this is merged and deployed, and assign to @paregorios so he can verify the fix.

**Comment by alecpm** [comment]
Didn't mean to close the issue, but it is merged and deployed to dev.

**Comment by skleinfeldt** [comment]
over to @paregorios for review

**Comment by paregorios** [comment]
this appears to be working on my local instance

**Comment by paregorios** [comment]
This is indeed fixed. Closing.
