### ISSUE TITLE
can't add internal image as lead image

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#58]
When creating a news item or event item, the creator doesn't have an option to use an existing image on the web site as the lead image. The only option is to upload a new image from the user's computer. The same image may end up being uploaded repeatedly for different items.

**Comment by skleinfeldt** [comment]
That is correct. Lead images are part of the content item, you can't use an existing image. In the normal use case, the lead image is unique to the content item.

**Comment by paregorios** [comment]
@k2soule how often is this coming up as an issue?
