### ISSUE TITLE
"news editors" cannot "submit for review" unless they are authors

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#59]
more workflow frustrations

**Comment by paregorios** [comment]
blocked for #99

**Comment by paregorios** [comment]
@k2soule so far in my testing attempts (see shared google doc) I have not been able to duplicate this problem on staging (using our test users). I think we may need for you to arrange to sit with the individual(s) having this problem (with me on Skype) and see them walk through it (with test data added if we need it).

**Comment by paregorios** [comment]
@k2soule disregard my comment above for now and instead confirm or deny my impression that this ticket is actually a partial duplicate for #51

**Comment by k2soule** [comment]
I think you're right; this seems to be connected to #51.

**Comment by paregorios** [comment]
Thanks. I'm going to close this ticket as a duplicate for #51.
