### ISSUE TITLE
isaw.exihibitions template overrides were removed, but not incorporated into product

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#60]
Pre-upgrade, ZMI had been used to customize the checklist template in the isaw.exhibitions product by commenting out some hard-coded HTML relevant to only one of our early exhibitions. This ZMI customization was apparently removed, as directed, but the second step (incorporating the change back into the project code) was evidently never implemented or merged. This caused all of our exhibitions checklists to start including the old, deprecated HTML. A new ZMI override has been added, but this needs to be fixed once and for all in code as originally directed.

**Comment by paregorios** [comment]
not a director's issue

**Comment by cguardia** [comment]
@alecpm already did this one. It's already released.

**Comment by paregorios** [comment]
Can @alecpm or @cguardia point me to the commit(s) where this was incorporated into code and when it was deployed to production? Was the ZMI override removed at that time?

**Comment by alecpm** [comment]
The checklist view was the only remaining ZMI customized template from the isaw.exhibitions skins layer. I incorporated the ZMI changes (commenting out the header copy) when implementing the pagination for that view in #64. The commit is here: https://github.com/isawnyu/isaw.web/commit/932a1c359b6f914c461de2dd4058175045d693f0

**Comment by paregorios** [comment]
Thanks!
