### ISSUE TITLE
need content rule for item checkin

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#61]
Our publications process (workflow) depends on email notifications. Right now, we have the following rules set up:
- email those with publishing authority (i.e., @rogerbagnall) when an item has been submitted for review
- email the creators etc. of an item when it has been moved to "published" status

Our revision process works like this: 
- check out working copy (defaults to drafting) of a presently published item
- modify the working copy
- submit the working copy for review (existing content rule mentioned above executes)
- user with publishing authority checks in the working copy, which automatically assumes the published state of the baseline item but doesn't trip the "on publish" rule mentioned above, so the person who modified the item doesn't get an email indicating that it has been published.

There does not seem to be a way to set up a rule to fire on check in.

What can we do?

**Comment by k2soule** [comment]
Can we trip a rule to notify the creator of a working copy when that working copy is renamed?

**Comment by paregorios** [comment]
duplicate for #62

**Comment by paregorios** [comment]
closing as duplicate
