### ISSUE TITLE
checklist view template limited to 100 items

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#64]
Question; what is causing the limitation of checklist view to show only the first 100 items in the folder? Is it something that we can change?

**Comment by alecpm** [comment]
Currently, the template sets batch=True in the arguments to getFolderContents, which batches the results (default batch size 100). We can remove batching to ensure all results are shown, or add the batch navigation macros to the page so that you can easily navigate between batches of 100 (like on folder_contents and other pages). Which would be preferred?

**Comment by k2soule** [comment]
My first instinct is to enable the batch navigation macros, so that we
don't have to worry about an exhibition checklist with 400 object
thumbnails trying to load all at once.

Tom, any objections?

-Kristen

**Comment by k2soule** [comment]
Yes that's my inclination as well. Let's make it so.

On Tuesday, June 7, 2016, Kristen Soule <kristen.soule@nyu.edu> wrote:

> My first instinct is to enable the batch navigation macros, so that we
> don't have to worry about an exhibition checklist with 400 object
> thumbnails trying to load all at once.
>
> Tom, any objections?
>
> -Kristen
>
>
> On Mon, Jun 6, 2016 at 7:00 PM, Alec Mitchell <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Currently, the template sets batch=True in the arguments to
>> getFolderContents, which batches the results (default batch size 100). We
>> can remove batching to ensure all results are shown, or add the batch
>> navigation macros to the page so that you can easily navigate between
>> batches of 100 (like on folder_contents and other pages). Which would be
>> preferred?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/isawnyu/isaw.web/issues/64#issuecomment-224114669>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AHhIkNrkJZQ8T0CVkHL2KpcI2LyAXPz_ks5qJKaegaJpZM4GXuJC>
>> .
>>
>
>

-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
This is deployed to staging. See here for an example:

http://isaw4-dev.atlantides.org/exhibitions/aesthetics/checklist/

**Comment by k2soule** [comment]
Nice - that has the desired effect. Thanks!

**Comment by paregorios** [comment]
thanks, please deploy to production at your leisure

**Comment by alecpm** [comment]
Done: http://isaw.nyu.edu/exhibitions/aesthetics/checklist/
