### ISSUE TITLE
remove uppercase transform on tables in content-core

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#66]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Friday May 22, 2015 at 21:00 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/5_

---

Text inside tables within `<div id="content-core"``is picking up a text-transform to uppercase and a font assignment, etc. from a rule in isaw.theme/theme.css that applies style to``#portal-columns table tbody tr td`` https://github.com/isawnyu/isaw.theme/blob/master/isaw/theme/static/theme.css#L157. 

Here's some example HTML that it's happening to, following by a screen capture of the visual effect:

``` html
<div id="content-core">
    <div class="" id="parent-fieldname-text-dca38de971dd4dccdda4fcfe5636afe0">
        <table class="plain">
            <tbody>
                <tr>
                    <td>
                        <h3> <b>FIRST YEAR</b>
                        </h3>
                        <p class="FreeFormLetterV"> <i>Doctoral Committee:</i>
                            Your doctoral  committee is determined at the beginning of the first semester. The  committee, consisting of your main ISAW adviser and other ISAW or  affiliated faculty, is responsible for guiding you in your studies.  Students meet with their committee on an annual basis to review their  progress and discuss future coursework, fieldwork, research, etc.
                        </p>
                        <p class="FreeFormLetterV"> <i>Doctoral Contract:</i>
                            Students fill out a  doctoral contract with their planned course of study and this is  revised and approved by the committee accordingly each year.
                        </p>
                        <p class="FreeFormLetterV">
                            <i>Coursework:</i>
                            Seminars, courses, and directed study at ISAW and other NYU and consortium universities
                        </p>
                        <p class="FreeFormLetterV">
                            <i>Languages</i>
                            : Pass two language exams by the end of the year.
                        </p>
                    </td>
                </tr>
                <tr>
⋮
```

![shouting-table-dev](https://cloud.githubusercontent.com/assets/263285/7779536/ec0d8c8e-009a-11e5-9a39-aecda67b63d8.jpg)

Compare to how that table looks right now on production:

![quite-table-prodo](https://cloud.githubusercontent.com/assets/263285/7779539/f925efe2-009a-11e5-9870-8965a70d52f9.jpg)

Of course we're not trying exactly to match the old production styles(!), but something more restrained is probably what we're after for default behaviors.

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Tuesday May 26, 2015 at 15:48 GMT_

----

@paregorios Looking at this, I'm not really clear on why this information is laid out in a table? If I remove the table markup the content looks much nicer. 
![screen shot 2015-05-26 at 11 47 35 am](https://cloud.githubusercontent.com/assets/1392386/7816569/203da9da-039d-11e5-93fa-ad0605399546.png)

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday May 26, 2015 at 21:19 GMT_

----

That's a fine solution for this page. But I think our users will want to have some tables in other places, and I'm thinking all caps is still not what we want to see for style. Has anything been done intentionally to table styles yet, using, e.g. the various default table classes plone provides? Or is this all arbitrary inheritance right now?

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Tuesday May 26, 2015 at 21:23 GMT_

----

This is all based on the design comps which we can certainly adapt to suit
the best and most frequent use cases. Are there any other examples that
come to mind on staging we could base some adjustments off of?

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday May 26, 2015 at 21:55 GMT_

----

I'll gather them up

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday Jun 09, 2015 at 18:46 GMT_

----

I need to determine whether there's anything that needs immediately to be done about this.

**Comment by paregorios** [comment]
<a href="https://github.com/k2soule"><img src="https://avatars.githubusercontent.com/u/7882896?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k2soule](https://github.com/k2soule)**
_Tuesday Aug 04, 2015 at 19:41 GMT_

----

This issue looks like one that we could potentially move out of pre-deployment.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Thursday Aug 06, 2015 at 14:36 GMT_

----

Agreed. Moving out of pre-deployment. CSS issue that we'll wrangle later.

**Comment by paregorios** [comment]
transferred from https://github.com/isawnyu/isaw.theme/issues/5

**Comment by alecpm** [comment]
The relevant page is no longer using a table, but I've removed that ill advised text-transform. Table headings will still be uppercased by default, but not normal table cell contents.

**Comment by alecpm** [comment]
Deployed to production along with other changes from master.
