### ISSUE TITLE
coping with giant titles in page headings and breadcrumbs

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#67]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Monday May 25, 2015 at 11:21 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/8_

---

Given our propensity for very long titles (especially for events), the current all-caps, all-the-time style for main headings is problematic (note also what happens to breadcrumbs). Any ideas (other than not using long titles, which is not an option) about what we can do in this regard? See, for example:

![giant-titles-events](https://cloud.githubusercontent.com/assets/263285/7796578/3c2ffb9a-02a6-11e5-84fd-0cb6833e2324.jpg)

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Monday May 25, 2015 at 11:22 GMT_

----

NB: on the current site we have a solution for breadcrumbs: custom code that truncates what's displayed at the first colon (if there is one, which in these long titles, there often is).

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Tuesday May 26, 2015 at 15:38 GMT_

----

@paregorios I like the idea of breaking breadcrumbs at the colon to keep those under control.

For long titles like this, would it be possilbe / advisable to break this up into a title and a subtitle field? Whether obvious to the user or done automatically at the colon?

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday May 26, 2015 at 20:58 GMT_

----

@skleinfeldt @alecpm what's harder and more time-consuming, do you think? Writing custom code to truncate/split titles and breadcrumbs on colons, or adding subtitle field to the "event" type? Or has someone by chance written a super-cool product that does for subtitles what "lead image" does for images?

**Comment by paregorios** [comment]
<a href="https://github.com/alecpm"><img src="https://avatars.githubusercontent.com/u/202854?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecpm](https://github.com/alecpm)**
_Tuesday May 26, 2015 at 21:04 GMT_

----

I think it probably makes sense to do this in JS.  Splitting the heading on the semi-colon into title/subtitle and truncating the breadcrumb on the semi-colon and/or a set number of characters. @cewing any thoughts on this?

**Comment by paregorios** [comment]
<a href="https://github.com/cewing"><img src="https://avatars.githubusercontent.com/u/417109?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cewing](https://github.com/cewing)**
_Tuesday May 26, 2015 at 21:10 GMT_

----

What does "subtitle" mean in terms of the site theme?  Is it the larger font that we had previously though would be the first paragraph of body text?  If so, do we need to watch out for and deal with cases where the title gets split into title/subtitle and suppress that first paragraph display?  And do we do this for any title that contains a colon?  Only for those on events?  What happens if the title contains a colon but is short?  (I know, *academia*, unlikely, but still possible).

If we can come up with a full understanding of this and how it interacts with other parts of the page, then yeah, I think we can certainly do it in javascript.  That would save any special Python coding or adapters, the editors/authors could continue to behave as they always have and things would "just work"™

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Tuesday May 26, 2015 at 21:21 GMT_

----

As far as styling, we'd likely come up with some CSS for this new element
to differentiate between a subtitle and an introductory piece of content.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday May 26, 2015 at 21:58 GMT_

----

Ah, if only it were easy to search the ZODB via the portal catalog for all titles containing a colon. I tried playing around with the ZMI to do this, but no luck. I guess one has to write Python? @alecpm or @cewing can you advise?

**Comment by paregorios** [comment]
<a href="https://github.com/skleinfeldt"><img src="https://avatars.githubusercontent.com/u/1198463?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skleinfeldt](https://github.com/skleinfeldt)**
_Wednesday Jun 03, 2015 at 17:55 GMT_

----

@alecpm it is clear what needs to happen here? Is the JS task some you would do or @kevintbrooks ?

**Comment by paregorios** [comment]
<a href="https://github.com/alecpm"><img src="https://avatars.githubusercontent.com/u/202854?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecpm](https://github.com/alecpm)**
_Wednesday Jun 03, 2015 at 18:01 GMT_

----

I can do the JS.  My initial thought is to split on a ':' for both the main title and the breadcrumb.  For the main page title, we'd add a "p.sub-title" below the title tag containing the part after the colon.  For the breadcrumbs we'd just truncate (perhaps also have a word or character limit for truncating long titles with or without colons there).  Not sure what to do in listings/search though.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Wednesday Jun 03, 2015 at 18:07 GMT_

----

+1 on @alecpm's ideas, including the length limit for truncation, which in my view should only truncate on word breaks. My instinct is to leave listings/search alone for now; we're backing away from some of the all caps usage around the site, and it will look less crazy if we go that direction on search, but I want to see it before pushing for a CSS change.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday Jun 09, 2015 at 18:42 GMT_

----

Right, so the remaining issue here is truncation in breadcrumbs and <br/> insertion (or similar) in headings?

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday Jun 09, 2015 at 18:43 GMT_

----

Put this on the backlog because it's not job one at the moment.

**Comment by paregorios** [comment]
transferred from https://github.com/isawnyu/isaw.theme/issues/8

**Comment by paregorios** [comment]
This remains an issue, and is particularly evident in events. It's too bad the old template custom code for this didn't get carried forward. Perhaps it's not too difficult to find and fold in.

**Comment by alecpm** [comment]
I've implemented a first pass of the script described above for the event view only. Please take a look at e.g.:

https://isaw4-dev.atlantides.org/events/archive/ay-2010-2011/lycian-funerary-monuments

We'll probably want to style the "subtitle" paragraph in some special way as well as adjust the truncation point for the breadcrumbs (currently at the nearest word break less than 70 chars).

**Comment by paregorios** [comment]
I like this direction. Some suggestions:

 - Use only the title in creating the breadcrumb (i.e., ignore subtitle), then truncate at nearest word break less than **50** characters if necessary.
 - For styling the subtitle, how about something like: 

```css
{
    font-family: Questrial, 'Nimbus Sans', Univers, Geneva, sans-serif;
    font-size: 22px;
    font-weight: 900;
}
```

**Comment by paregorios** [comment]
And just to be clear, I think I'd like to see the breadcrumb truncation behavior everywhere they appear, not just in events.

**Comment by alecpm** [comment]
OK, these changes (styling of subtitle and making breadcrumb truncation universal) are live on staging.

**Comment by paregorios** [comment]
@alecpm this looks good. Please deploy to production.

**Comment by alecpm** [comment]
This is deployed to production.

**Comment by paregorios** [comment]
Looks good, thanks.
