### ISSUE TITLE
styles missing from editor drop-down

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#68]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Thursday Jun 04, 2015 at 18:20 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/27_

----

as discussed in standup today, we're not seeing what the story and comps would expect us to see (e.g., byline, lead item, etc are missing).

**Comment by paregorios** [comment]
<a href="https://github.com/cewing"><img src="https://avatars.githubusercontent.com/u/417109?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cewing](https://github.com/cewing)**
_Thursday Jun 04, 2015 at 18:46 GMT_

----

I've fixed the problem with the lead image not appearing.  There was a block for content-type portlets set at the root of the news folder.  Removing that allows the image portlet I'd assigned to news items to appear.  

@paregorios I have questions for you:
1.  The byline that appears, should this just be the normal content byline?  Should it appear on all content types?  Or should I have created a custom byline for news items only in the template?  I was under the impression that that element was just the site-wide byline.
2.  The lead paragraph in fancy text.  Is that still desired?  If so, a simple css rule on the first paragraph of body text should do that, and that would be a good ticket for @kevintbrooks 
3.  The next-previous navigation elements showing at the bottom of the news item.  Are those in fact desired?

**Comment by paregorios** [comment]
<a href="https://github.com/skleinfeldt"><img src="https://avatars.githubusercontent.com/u/1198463?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skleinfeldt](https://github.com/skleinfeldt)**
_Thursday Jun 04, 2015 at 18:57 GMT_

----

@paregorios I discussed 3.) with @cewing and we agree that next/previous nav is a bad idea here since it does not come native with collections (as opposed to folders) and would be extra work. If this is desired, please write a separate "deferred" ticket or story to consider adding the feature in the future.

Regarding 1.) I don't see bylines on the event item comp (http://isaw.icscreative.com/event.html) so I am going to suggest we leave bylines off of everything (for anonymous) unless otherwise indicated on a design.

Regarding 2.) and everything else I am going to reassign this ticket to @kevintbrooks now to work on the CSS for news items. See http://isaw4-dev.atlantides.org/news/vrs-research-spotlight-maria-doerfler for example - it looks better now that it has its image but the body text needs styling.

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Thursday Jun 04, 2015 at 19:07 GMT_

----

Is there a reason Plone is using divs for body output instead of <p> tags? 

http://isaw4-dev.atlantides.org/news/vrs-research-spotlight-maria-doerfler

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Thursday Jun 04, 2015 at 19:39 GMT_

----

I'll try to answer all the questions in the above thread in order:

 1. bylines
    1. I would be happy to see the byline + date that's currently appearing on each tile in the news item listing view be used site-wide (i.e., wherever we want a byline).
    1. @skleinfeldt is correct that bylines should not appear on event items nor in the event listing
 1. fancy first paragraph: I think this is a question for @kevintbrooks together @alecpm : how hard would it be to just define a css class selector for that fancy text and let our content creators apply it to the first paragraph in body text if they want to? I'm thinking of what we did with the BIG RED LIST ITEMS. 
 1. I concur with @skleinfeldt on punting on next/previous. 

I don't think I can answer @kevintbrooks question about "why Plone is using divs"? Can @skleinfeldt interact with @kevintbrooks and bring in others as necessary to address?

Thanks

**Comment by paregorios** [comment]
<a href="https://github.com/cewing"><img src="https://avatars.githubusercontent.com/u/417109?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cewing](https://github.com/cewing)**
_Thursday Jun 04, 2015 at 19:41 GMT_

----

I will make a new issue for q1 above.  It would be easier, given a custom view, to suppress the byline on events and event listings than to special-case it everywhere else.  We should override the byline viewlet template and then include it in the site theme.

**Comment by paregorios** [comment]
<a href="https://github.com/alecpm"><img src="https://avatars.githubusercontent.com/u/202854?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecpm](https://github.com/alecpm)**
_Thursday Jun 04, 2015 at 19:41 GMT_

----

2) Is quite easy to do as long as people are comfortable using the style dropdown.  Essentially the would be "Normal Paragraph" and "Highlighted Paragraph" or something like that.

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Thursday Jun 04, 2015 at 19:44 GMT_

----

I've added a CSS class ("intro") to trigger this behavior.

**Comment by paregorios** [comment]
<a href="https://github.com/alecpm"><img src="https://avatars.githubusercontent.com/u/202854?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecpm](https://github.com/alecpm)**
_Thursday Jun 04, 2015 at 19:45 GMT_

----

"Intro Paragraph" it is then.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Thursday Jun 04, 2015 at 19:49 GMT_

----

awesome!

**Comment by paregorios** [comment]
<a href="https://github.com/kevintbrooks"><img src="https://avatars.githubusercontent.com/u/1392386?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevintbrooks](https://github.com/kevintbrooks)**
_Monday Jun 08, 2015 at 15:58 GMT_

----

@paregorios is this ready to close?

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Tuesday Jun 09, 2015 at 18:18 GMT_

----

I do not see "Intro Paragraph" in the editor "Style" menu. Reassigning to @alecpm but putting on the backlog for now as it's more of a nice-to-have than a must-have for deployment.

**Comment by paregorios** [comment]
Transferred from https://github.com/isawnyu/isaw.theme/issues/27

**Comment by cewing** [comment]
Implemented, awaiting merge and deploy to staging.

**Comment by cewing** [comment]
deployed to staging.

**Comment by paregorios** [comment]
After running the upgrade step on staging, the style name appears as desired. Please deploy to production and run the upgrade as convenient.

**Comment by alecpm** [comment]
This should be deployed to staging now.

**Comment by k2soule** [comment]
Confirmed on production; the Intro Paragraph style is showing up now. Closing ticket.
