### ISSUE TITLE
unauthorized access via link throws an error instead of login prompt

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#7]
i've seen this on the current production site as well and would hoping it was a 4.2 problem, but it looks now as if the cause is something else. To reproduce on staging:

* Visit, as anonymous, /research/bukhara-project/news
* At the end of the "Upcoming: June through August 2014 " paragraph click on the link "here"
* Get redirected to /acl_users/credentials_cookie_auth/require_login?came_from=http%3A//66.35.48.8/research/bukhara-project/fieldwork-2013 wherewith the good old "the error has been logged with entry number..." is displayed

**Comment by paregorios** [comment]
I'm resurrecting this ticket because we still have the behavior and I want to make sure that, once we've been through the design implementation process, we've succeeded in getting rid of the behavior.

**Comment by paregorios** [comment]
I have the impression that this is resolved. @k2soule do you concur?

**Comment by k2soule** [comment]
Yes, this is fixed; visitors are directed to the NYU shibboleth login screen now, as expected. Closing ticket.
