### ISSUE TITLE
allow users to upload a PDF or create a page as CV, instead of using the structured maker

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#71]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Tuesday Sep 29, 2015 at 22:10 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/108_

----

**Comment by paregorios** [comment]
Transferred from https://github.com/isawnyu/isaw.theme/issues/108

**Comment by cguardia** [comment]
This could be as easy as adding "File" to the list of addable objects for the profile type. The user could then add the file and put a link in their profile text.

If not this, what are you looking for here?

**Comment by paregorios** [comment]
Yes. I think we'd like to add file, page, and image.

On Tuesday, December 8, 2015, Carlos de la Guardia <notifications@github.com>
wrote:

> This could be as easy as adding "File" to the list of addable objects for
> the profile type. The user could then add the file and put a link in their
> profile text.
>
> If not this, what are you looking for here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isawnyu/isaw.web/issues/71#issuecomment-162822908>.
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cguardia** [comment]
Took advantage of the security patch deployment to update staging with this. Ready to test.

**Comment by paregorios** [comment]
Thanks. Taking this ticket for review.

**Comment by paregorios** [comment]
Looks good. Please deploy to production.

**Comment by cguardia** [comment]
Deployed.
