### ISSUE TITLE
suppress "download curriculum vitae" link on profiles

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#72]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Tuesday Sep 29, 2015 at 22:09 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/107_

----

PDF generation for CVs is imperfect, and more importantly, this link appears even when the CV is substantively empty. It's a distraction since the full CV content (if filled out) appears in the profile.

**Comment by paregorios** [comment]
Transferred from https://github.com/isawnyu/isaw.theme/issues/107

**Comment by cguardia** [comment]
Removed all (two) cv pdf_view links.

**Comment by paregorios** [comment]
Sounds good. I look forward to testing on staging, perhaps after #71 has been implemented as well?

**Comment by cguardia** [comment]
Ready to test on staging.

**Comment by paregorios** [comment]
Thanks, I'm taking this ticket for review too.

**Comment by paregorios** [comment]
Looks good. Please deploy to production.

**Comment by cguardia** [comment]
Deployed.
