### ISSUE TITLE
too much all caps in profiles

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#73]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Wednesday Sep 23, 2015 at 19:18 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/106_

---

![allcaps](https://cloud.githubusercontent.com/assets/263285/10055835/f45761de-61fd-11e5-9133-4dfd27e526ec.jpg)

**Comment by paregorios** [comment]
Transferred from https://github.com/isawnyu/isaw.theme/issues/106

**Comment by alecpm** [comment]
I've remove the uppercase transform for the profile titles. Should it be removed for the name/h1 as well?

**Comment by alecpm** [comment]
This initial fix was deployed to production. Let me know about the name/h1.

**Comment by paregorios** [comment]
I think it's ok for now. Closing as resolved.
