### ISSUE TITLE
google analytics is horked

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#75]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Thursday Sep 17, 2015 at 15:16 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/104_

----

Evidently stopped working on 2 september.

**Comment by paregorios** [comment]
Transferred from https://github.com/isawnyu/isaw.theme/issues/104

**Comment by paregorios** [comment]
Have verified that tracking code / javascript snippet is set in ```/@@site-controlpanel```. This script never makes it into rendered page HTML. Is it being filtered out in the Diazo theme?

**Comment by skleinfeldt** [comment]
@paregorios sounds likely... Easy to fix if that's the case.

**Comment by alecpm** [comment]
GA code fix is on staging, I can tag and release to production when confirmed:

http://isaw4-dev.atlantides.org

**Comment by paregorios** [comment]
I am seeing javascript on staging with the correct tracking ID; however, what Google Analytics tells me the full "tracking code" should look like is different from what I see on staging. Has google updated do you suppose?

Here's what google says we should use:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3702316-4', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by alecpm** [comment]
The code is entered in the site control panel e.g.:

http://isaw4-dev.atlantides.org/@@site-controlpanel

and can be whatever you choose. What's currently appearing in the themed site seems to match what's in the staging control panel presently.

**Comment by paregorios** [comment]
@alecpm thanks. Please deploy to production.

**Comment by alecpm** [comment]
GA code is now live on production.

**Comment by paregorios** [comment]
GA has been successfully unhorked!
