### ISSUE TITLE
add NYU links in header and footer: 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#81]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Monday Aug 17, 2015 at 16:35 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/91_

---

From @k2soule: "have the "New York University" text in the header and the NYU logo in the footer both link to the main NYU site"

**Comment by k2soule** [comment]
Assigning to myself, to see whether I can at least get the footer link done.

**Comment by k2soule** [comment]
We need to have the text "New York University" in the header link to the main NYU web site: www.nyu.edu
Also, we need to have the image with the "NYU | ISAW" logo in the footer link to the main NYU web site.

**Comment by cguardia** [comment]
This is not trivial, because it would require changing the layout. "New York University" is not actual html, but plain text content added using CSS, and the footer image is a background CSS image. I can do that, but just wanted to point out it's not as simple as adding a link (translation: I'm scared of CSS tweaks).

**Comment by paregorios** [comment]
Ah, right. This kind of implementation -- as well as the bigger fact that we got a *responsive* theme from the designers instead of a truly "mobile-first" theme as requested -- really makes maintenance and future modification harder than we hoped it would be. This is a case in point.

@cguardia and @skleinfeldt please allow @k2soule and me to discuss this in the context of priorities before spending more time on it. Thanks.

**Comment by paregorios** [comment]
Now that we understand the scope of this, I'm going to create a story in scrumdo as discussed earlier today with @skleinfeldt and we can estimate how big a job this would be the next time we do planning poker.

**Comment by paregorios** [comment]
Meantime, kicking this to the backlog.

**Comment by paregorios** [comment]
Assigned to self to try to figure out whether I created a story for this already or not.

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
These are the right links. Can we add CSS styles for focus/hover like we have on other links in the header and footer?

**Comment by cguardia** [comment]
Done.

**Comment by paregorios** [comment]
Is there any way we can avoid the words "New York University" in the header link jumping around when the hover/focus behavior is activated? I think @alecpm may have had to deal with sort of thing in a couple of other contexts so he might be able to point the way to a quick fix.

**Comment by alecpm** [comment]
The solution I used is to always have a border in place, but make it transparent by default. Then just change border-color in the activated state. Generally that will mean adjusting the any padding or sizing to account for the additional border size as well.

**Comment by paregorios** [comment]
This looks to be fixed now on staging. If so, please merge to master and deploy to production.

**Comment by cguardia** [comment]
Merged. @alecpm, not sure if you plan to deploy other things.

**Comment by alecpm** [comment]
Not planning to deploy anything anytime soon. I'll be switching production over to an Ansible setup at some point, but we shouldn't tie any releases to that I think.

**Comment by paregorios** [comment]
So, it looks like this might have gotten deployed at some point, but there are problems. 

 - "New York University" in the header is now a link, and that looks fine
 - "NYU/ISAW" logos are missing from the footer, which is not what I expected

What I expected to see:

![Screen Shot 2019-07-25 at 1 20 23 PM](https://user-images.githubusercontent.com/263285/61898520-1da7ff80-aedf-11e9-9947-1600b3e3934c.png)


What I actually see:

![Screen Shot 2019-07-25 at 1 21 47 PM](https://user-images.githubusercontent.com/263285/61898545-2e587580-aedf-11e9-9418-d2038c947271.png)

**Comment by cguardia** [comment]
Apologies, lost track of when this was deployed, and a new image and footer text needed to be edited in isaw-settings. Done.

**Comment by paregorios** [comment]
Looks good, thanks.
