### ISSUE TITLE
breadcrumbs bar is too tall in collapsed/mobile view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#83]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Wednesday Aug 12, 2015 at 20:41 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/89_

----

The bottom of the breadcrumbs bar should be even with the bottom of the ISAW logo, not thus:

![img_0582](https://cloud.githubusercontent.com/assets/263285/9236118/7a6518e6-4108-11e5-956d-a6507927f6f2.PNG)

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Wednesday Sep 02, 2015 at 14:10 GMT_

----

This is in work in branch:issue89

**Comment by paregorios** [comment]
temporarily assigned to myself pending writing of a story for development

**Comment by alecpm** [comment]
This fix is deployed to staging.

**Comment by alecpm** [comment]
One note, when the breadcrumbs trail is long it may break onto two lines and once again extend past the site logo, but I'm not sure what we can do about that that doesn't reduce functionality of the breadcrumbs.

**Comment by paregorios** [comment]
@alecpm the changes on staging fix this from some browser widths, but not all (I've played with it in responsive view on chrome). For example, on the iphone 6, both safari and chrome show me the following:

![img_1809](https://cloud.githubusercontent.com/assets/263285/18356067/f2a57ffc-75b0-11e6-80a3-d62ddae78aeb.PNG)

**Comment by alecpm** [comment]
Ugh, Safari and Chrome's responsive testing modes seem to disagree on this, but (suprisingly!) Chrome is representing the iPhone 6 more accurately. It's working in all modes in the Safari responsive design mode, but there appear to be some unexpected font-size changes happening at certain widths/devices. I suspect we're hitting a device minimum font size issue or something, I'll get it fixed shortly using an actual device.

**Comment by alecpm** [comment]
Should be good now. I set a fixed height (which also avoids the line breaking issue above) and disabled mobile "text-size-adjust".

**Comment by paregorios** [comment]
@alecpm that's got it! Please deploy to production.

**Comment by alecpm** [comment]
Deployed.

**Comment by paregorios** [comment]
looks good, thaks.
