### ISSUE TITLE
Tag code going to production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#85]
<a href="https://github.com/skleinfeldt"><img src="https://avatars.githubusercontent.com/u/1198463?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [skleinfeldt](https://github.com/skleinfeldt)**
_Friday Aug 07, 2015 at 17:17 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/87_

----

Just before we do the upgrade, so we know what we deployed.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Wednesday Aug 12, 2015 at 12:21 GMT_

----

Is this done? Can we close?

**Comment by paregorios** [comment]
<a href="https://github.com/cguardia"><img src="https://avatars.githubusercontent.com/u/324415?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cguardia](https://github.com/cguardia)**
_Thursday Aug 13, 2015 at 18:31 GMT_

----

There is already a tag production08112015 for the code as it was when we deployed. There have been a couple of fixes, though, and there might be more.

**Comment by paregorios** [comment]
This might be the topest of top 10. If it hasn't been done completely, we might not be able to walk back to a known good state without regressing some other changes.

**Comment by alecpm** [comment]
There are a few different ways to pin versions in a buildout like this, where multiple repositories are involved.  The simplest is to make a "release" branch of the buildout where sources.cfg (https://github.com/isawnyu/isaw.web/blob/master/cfg/sources.cfg) points to specific tags or revisions of each of the add-ons.  Any time an addon is updated and the changes are ready for release, that sources.cfg would need to be updated with the new tag/revision.

That process would be fairly manual, which could lead to missed revision updates.  A similar more automated way would be to make "release" branches of all the ISAW branches, and point the sources.cfg atat the release branches of the internal dependencies and pinned revisions of any external dependencies.  Any changes that are ready for deploy to production would be merged from master into the release branch.  The disadvantage is that there's no record of which package versions go with a given released version of the buildout, but it does provide a simple and reliable release process for each add-on and the buildout.

Finally, the option that provides the easiest release process would be to merge all of the add-on repos into the buildout repo under ``src/`` (specifically isaw.facultycv, isaw.theme, isaw.policy, and isaw.exhibitions).  History can be retained when merging the repos, and once they are merged then there's a single revision for buildout and all the add-ons, and the production server can either run off of a tagged release or a single release branch, with no need for version pins on the internal add-ons.

**Comment by skleinfeldt** [comment]
Assigning this to @paregorios to decide which approach to take. We recommend Alec's last option as the most trouble-free and simplest, if that is feasible.

**Comment by paregorios** [comment]
+1 on Alec's "most trouble-free and simplest" solution please!

Unassigning myself to reflect my desire to see implementation proceed. Also removing question tag.

**Comment by alecpm** [comment]
I've created a new branch with the repos merged together (https://github.com/isawnyu/isaw.web/tree/merged-repos).  I suggest you give it a try (you'll need to delete the contents of src/ before doing a git checkout).  Once we switch development and deploy over to this branch, we can simply create tags to mark release points for the full code base and configuration.

**Comment by paregorios** [comment]
I can run the buildout using both "master" and "merged-repos" branches (the latter after following instructions above to delete the contents of src/ before checking out the branch). Both run without fatal errors and I can view the instance locally on 8081; however, I'm not seeing the ISAW theme. Here's what my local instance looks like (with replicated filestorage and blobstorage from production): 

![ugly](https://cloud.githubusercontent.com/assets/263285/11868439/6309833e-a47d-11e5-98ce-31c90670ef39.jpg)

**Comment by alecpm** [comment]
Hm, I'm not seeing this locally (or at least I see unthemed on 127.0.0.1 but themed on localhost, as expected based on the config in the theming control panel).  If you don't have any uncommitted changes, try doing a 'git reset --hard' followed by a buildout run and restart both your zeoserver and client.

**Comment by paregorios** [comment]
Thanks. Was using the URL popped up in the terminal by the instance when it's started, and that's the bare 127.0.0.1 (I have a vague recollection I made this mistake before). Will check localhost momentarily.

**Comment by paregorios** [comment]
Yes. That was the issue. It's the README that says to view the site at 127.0.0.1 and doesn't mention localhost. I'll make a modification.

So, what's the next step on this ticket?

**Comment by alecpm** [comment]
The next steps are to switch dev over to this branch, test there a bit, and then make a tag on the branch and deploy that to production.  Optionally, we could merge this branch into master so we can keep work on master.  From this point forward, all development should be done on this new branch (whatever it may be called) and the packages therein.

**Comment by paregorios** [comment]
It seems to me that eventually this branch should be merged into "master" but it would probably be good to test on staging first, in the manner you suggest. 

@alecpm can you coordinate with @cewing and @cguardia on when best to make this change, given that both have work in progress on affected components (and @cewing even has an outstanding pull request)?

**Comment by alecpm** [comment]
I'm already in contact with them regarding the new branch, and @cewing has a patch ready for it.

**Comment by alecpm** [comment]
It looks like I'm going to have to merge your changes from isaw.theme staging branch into this new repo first though.

**Comment by cewing** [comment]
FYI, my PR from the isaw.policy package has already been patched to a new branch here and a new PR opened against the `merged-repos` branch, so I'm all cleared.

**Comment by paregorios** [comment]
What changes on isaw.theme:staging? I don't see any as compared to isaw.theme:master https://github.com/isawnyu/isaw.theme/compare/master...isawnyu:staging

**Comment by alecpm** [comment]
You are correct.  I was fooled by looking at the differences between staging and master on the dev server  (where staging is being used, and master hasn't been updated apparently).

**Comment by alecpm** [comment]
merged-repos is deployed to isaw4-dev

**Comment by paregorios** [comment]
I've poked around some on staging and don't see any problems. Is there any systematic testing we should do?

**Comment by alecpm** [comment]
Not really, there's no reason to think that anything should be different at this point besides the repo structure.  @cewing and @cguardia, it's probably a good time to make your commits to the new branch at this point.  I'll tag a release (assuming there's nothing currently on staging that's not OK to deploy to production currently).

**Comment by paregorios** [comment]
I haven't had a chance to review @cewing's changes, which I think represent a work in progress that hasn't yet been deployed even to staging. In any case, I don't think we should deploy his workflow changes to production yet. I can't speak to where @cguardia is on that score. But otherwise I think all the code that is running on staging should be fine to deploy also to production.

**Comment by alecpm** [comment]
Indeed, I made a tag (2.0) for what's currently committed and live on staging (does not include recent changes from @cewing or @cguardia), and can deploy that tag to production whenever you are ready.

**Comment by paregorios** [comment]
go for it: please deploy to production

**Comment by paregorios** [comment]
If this was deployed yesterday on production, it seems to be fine. No reports of problems so far.

**Comment by alecpm** [comment]
Great!

**Comment by alecpm** [comment]
OK, I've merged "merged-repos" back to master, so we can now resume development (and branching and tagging) on master.  I'll be switching the dev server back over to master today (prod is on a tag rather than on a branch, so it will remain unchanged).

**Comment by alecpm** [comment]
@cguardia, @cewing make any new changes/pull requests can go to master now (once you've pulled down the current master)
