### ISSUE TITLE
css: address margin/padding for missing images in people pages

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#89]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Wednesday Jul 08, 2015 at 11:06 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/63_

----

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Thursday Aug 06, 2015 at 14:35 GMT_

----

This is still an issue (see) below, and presumably only requires a minor CSS tweak, which I'll undertake.

![peeps](https://cloud.githubusercontent.com/assets/263285/9114258/7685415e-3c1e-11e5-890b-c5fc3fef3790.jpg)

**Comment by paregorios** [comment]
<a href="https://github.com/alecpm"><img src="https://avatars.githubusercontent.com/u/202854?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecpm](https://github.com/alecpm)**
_Friday Aug 07, 2015 at 19:34 GMT_

----

I've committed a fix; not sure it's what you want though:

http://isaw4-dev.atlantides.org/people/staff

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Monday Aug 10, 2015 at 16:44 GMT_

----

Not ready to close this, but I don't think it needs to be addressed ahead of rollout. Punting to backlog for now.

**Comment by paregorios** [comment]
It is ISAW policy to have a photo for everyone. And placeholders are now used when we don't have them. I'm inclined to close "won't fix". @k2soule what do you think?

**Comment by k2soule** [comment]
agreed.
