### ISSUE TITLE
Need to display current logged-in user

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#92]
The site currently does not display the name of the current user when one is logged in. This will be important, particularly for admins who log in as test users as well as for machines that are shared by multiple users. However, it is not currently an urgent or high priority.

Still, I'd like to start this off by asking the question; where could we put that information? Maybe in the footer?

**Comment by paregorios** [comment]
This got closed inadvertantly. Reopening with apologies.

**Comment by skleinfeldt** [comment]
The user name label that should be part of the "user actions"  should show in the footer in the same place as the login link.

**Comment by cguardia** [comment]
Deployed change to staging.

**Comment by paregorios** [comment]
Looks good! Please deploy to production at your leisure.

**Comment by alecpm** [comment]
This should be live on production now.

**Comment by k2soule** [comment]
Confirmed on production; logged in user is displayed in the footer. Closing ticket.
