### ISSUE TITLE
insert/edit dialog radio buttons misaligned

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#93]
On the insert/edit dialog (e.g., for adding an internal link while editing) one gets a list of things. One is supposed to select the radio button associated with the item one wants, but this is hard and error-prone because the radio buttons are horizontally misaligned with the text in the list.

![insertmenu](https://cloud.githubusercontent.com/assets/263285/11375006/8e257fa0-929e-11e5-8c0f-a075ddcc471e.jpg)

**Comment by paregorios** [comment]
not a director's issue

**Comment by paregorios** [comment]
bumping to high priority because it causes slow-down and hassle for content creators

**Comment by cewing** [comment]
@paregorios this is now merged, but not yet deployed to staging.  Will assign to you when it is ready for review.

**Comment by cewing** [comment]
deployed and ready for review.  In your hands, @paregorios!

**Comment by paregorios** [comment]
Looks good. Please deploy to production at leisure.

**Comment by k2soule** [comment]
This looks good on production. Closing ticket.
