### ISSUE TITLE
special search function for events only (including archive)

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#95]
Requested by @rogerbagnall

**Comment by skleinfeldt** [comment]
This may need some discovery - is this a hidden feature for staff only, or a general search improvement or ...? Food for thought:

Customized site search that lets you choose what type of thing to look for: http://www.upress.umn.edu/@@search?SearchableText=elliott

A faceted search could also offer this option, along with date range picker, sorting, etc: http://www.upress.umn.edu/test-division/bibliography/search-bibliography

**Comment by paregorios** [comment]
Yes. At present I'm thinking of this as a downstream concern, but let's see where we get to this month on more fully defined tasks. Looking back at scrumdo, this might well fit into a larger story (presently unfunded) about implementing SOLR etc.

**Comment by skleinfeldt** [comment]
Yes - although Solr is not necessary for faceted searches, and although they are easy to implement technically, they do need attention paid to layout and styling to make them user friendly and attractive

**Comment by paregorios** [comment]
blocked by #115

**Comment by paregorios** [comment]
director's issue

**Comment by k2soule** [comment]
New search feature has been added in staging. It allows searching future events or all (future and past) events. Not sure whether this will search through archived events, or just recent past.

**Comment by k2soule** [comment]
Tested search; it does not currently search subfolders.

**Comment by paregorios** [comment]
Steps to reproduce on staging:

- visit ```/events```
- select "Search all events" radio button
- enter the word "province" in the search box (no quotes)
- press "search"
- get nothing
- wish fondly that it had found ```/events/archive/ay-2010-2011/death-in-the-province-mortuary-practices-and-roman-imperialism-in-syria-and-lebanon```

**Comment by cguardia** [comment]
The view was only using folder_contents. Switched to using the catalog. Should work now on staging.

**Comment by paregorios** [comment]
looks good, please deploy to production

**Comment by cguardia** [comment]
Deployed.
