### ISSUE TITLE
make "tiled listing" available throughout the site

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#97]
Although the tiled listing template will work with folders and collections full of all manner of content types, it only finds archetype embedded images, such as those found in news items. It should be upgraded to also look for lead images, where they exist.

**Comment by paregorios** [comment]
marked high priority because it would be an easier way of getting a good entry look to the events archive ( #115 ) than figuring out how to win the style battle with collective.cover and the isaw theme.

**Comment by cewing** [comment]
So to clarify here @paregorios, the issue here is that the tiled view does not show "lead image" images if present, not that the tiled listing view should be made available on other content types?

**Comment by cewing** [comment]
implementation of above description finished and PR opened.  Will alert when deployed to staging for review.

**Comment by paregorios** [comment]
@cewing you've got it right in terms of what I'm looking for; I'll wait to hear from you for review

**Comment by cewing** [comment]
This has been deployed to staging.

**Comment by paregorios** [comment]
Looks good. Please deploy to production at your convenience.

**Comment by skleinfeldt** [comment]
@cguardia can you deploy this one please?

**Comment by alecpm** [comment]
This should be live on production now.

**Comment by k2soule** [comment]
Confirmed on production. Closing ticket.
