### ISSUE TITLE
pump news and event summaries into homepage slider overlays

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#98]

**Comment by k2soule** [comment]
This issue has been identified by key stakeholders as a high priority, since it is a very visible aspect of the web site, and the delay caused by manual updating of the sliders for Upcoming Events and News has been noticed. I'm bumping this up to a higher priority.

**Comment by k2soule** [comment]
Ideal site behavior: the overlay text for the Upcoming Events slider automatically updates to show the next three upcoming events chronologically, and the overlay text for the News slider automatically updates to list the three most recently-posted news items.

**Comment by paregorios** [comment]
downgrading to medium priority because it is not a top issue for the director

**Comment by k2soule** [comment]
For a given slide overlay, we need the ability to choose between (a) content pulled automatically in a feed from Events or News, vs (b) rich text that we enter manually ourselves.

**Comment by paregorios** [comment]
This was resolved with deployment of [Scrumdo Story 120](https://www.scrumdo.com/projects/story_permalink/1097525).
